#pragma once
// HW H1.1: procedural test scenes and ray sets, generated by our own code (no external
// models; evidence/hw-h1-1-bounds.json). Deterministic for a given seed.
#include "raw/math/primitives.hpp"
#include "raw/rhi/hw.hpp"
#include <string>
#include <vector>
namespace raw {
struct HwRayKind { std::string kind; size_t begin{0}, end{0}; };
struct HwScene {
    std::string name;
    std::vector<Tri> tris;
    std::vector<rhi::hw::RayIn> rays;
    std::vector<HwRayKind> kinds;   // contiguous ranges of rays by kind
};
// terrain, hall, debris; each with camera, random and ambient-occlusion rays.
std::vector<HwScene> hwScenes(uint64_t seed = 0x5EEDu);
// Triangles as 9 floats each, for the GPU.
std::vector<float> flatten(const std::vector<Tri>& tris);
}
