// Generated by scripts/wgsl_to_hlsl.py from src/gpu/common.wgsl and src/gpu/passes.wgsl. Do not edit.
// WGSL sha256 1f3a12a8c502c8dfac04b02202010f42d83fa4b50040d9c7f7f2982aed39144b
// Pass: motion

// raw-native GPU passes: definitions shared by every pass.
// This WGSL is the one shader source. WebGPU runs it as written; the D3D12
// backend runs src/gpu/hlsl/, which scripts/wgsl_to_hlsl.py generates from it
// (CI fails when the two differ). The translator needs every let and var to
// carry an explicit type.
// Each function mirrors one C++ function in src/ line for line, with the same
// operation order, so the GPU computes the same float32 expressions as the CPU
// reference. Shader compilers may still fuse or reorder; the reconcile
// certificate (raw/gpu_reconcile.hpp) measures what that costs.

struct Params {
    float4 vp[4]; // current view-projection, rows (raw/mat.hpp is row-major)
    float4 pvp[4]; // previous view-projection, rows
    float4 light; // xyz direction, w intensity
    float4 misc; // x AO radius (world), y SSAO pixel radius
    uint w; uint h; uint ntri; uint rt_samples;
    uint ss_samples; uint rtao; uint pad0; uint pad1;
};

// Triangle input: 24 floats each. 0..8 world positions a,b,c; 9..17 normals; 18..20 albedo.
static const uint TRI_STRIDE = 24u;
// Triangle setup output: 16 floats each.
// 0 valid, 1..3 screen x, 4..6 screen y, 7..9 view distance, 10..12 1/w, 13 area,
// 14 unused, 15 unused. Integer bounds live in the parallel u32 array (4 per triangle).
static const uint SETUP_STRIDE = 16u;

// Motion vectors by reprojection (src/motion.cpp). w of the output is 1 for a
// valid vector, 0 otherwise; the host counts them.
ConstantBuffer<Params> P : register(b0);
RWStructuredBuffer<float4> position : register(u1);
RWStructuredBuffer<float4> albedoMask : register(u2);
RWStructuredBuffer<float4> motion : register(u3);

float vlen(float3 v) { return sqrt(v.x * v.x + v.y * v.y + v.z * v.z); }
// raw::normalize: l > 0 ? v * (1/l) : v
float3 vnorm(float3 v) {
    const float l = vlen(v);
    if (l > 0.0f) { const float s = 1.0f / l; return float3(v.x * s, v.y * s, v.z * s); }
    return v;
}
float3 vcross(float3 a, float3 b) {
    return float3(a.y * b.z - a.z * b.y, a.z * b.x - a.x * b.z, a.x * b.y - a.y * b.x);
}
float vdot(float3 a, float3 b) { return a.x * b.x + a.y * b.y + a.z * b.z; }
// raw::mul(Mat4, Vec4), row by row, left to right.
float mrow(float4 r, float4 v) { return r.x * v.x + r.y * v.y + r.z * v.z + r.w * v.w; }
float4 mmul(float4 m[4], float4 v) {
    return float4(mrow(m[0], v), mrow(m[1], v), mrow(m[2], v), mrow(m[3], v));
}
// The deterministic per-pixel hash of src/ssao.cpp and src/ray_ao.cpp.
float hash01(uint x, uint y, uint s) {
    uint h = x * 374761393u + y * 668265263u + s * 2246822519u;
    h = (h ^ (h >> 13u)) * 1274126177u;
    h = h ^ (h >> 16u);
    return float(h & 0xFFFFFFu) / 16777216.0f;
}
// std::lround: halves round away from zero (WGSL round() rounds halves to even).
int lround(float v) {
    if (v >= 0.0f) { return int(floor(v + 0.5f)); }
    return -int(floor(-v + 0.5f));
}
uint pix(uint x, uint y) { return y * P.w + x; }

float2 uvOf(float4 m[4], float3 wp, inout bool ok) {
    const float4 cs = mmul(m, float4(wp, 1.0f));
    if (cs.w <= 1e-6f) { ok = false; return ((float2)(0.0f)); }
    const float inv = 1.0f / cs.w;
    return float2(cs.x * inv * 0.5f + 0.5f, 1.0f - (cs.y * inv * 0.5f + 0.5f));
}

[numthreads(8, 8, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    if (gid.x >= P.w || gid.y >= P.h) { return; }
    const uint i = pix(gid.x, gid.y);
    motion[i] = ((float4)(0.0f));
    if (albedoMask[i].w == 0.0f) { return; }
    const float3 wp = position[i].xyz;
    bool ok = true;
    const float2 cur = uvOf(P.vp, wp, ok);
    if (!ok) { return; }
    const float2 prev = uvOf(P.pvp, wp, ok);
    if (!ok) { return; }
    const float2 mv = cur - prev;
    if (!(abs(mv.x) <= 3.40282347e+38f) || !(abs(mv.y) <= 3.40282347e+38f)) { return; }
    motion[i] = float4(mv, 0.0f, 1.0f);
}
