// Generated by scripts/wgsl_to_hlsl.py from src/gpu/common.wgsl and src/gpu/passes.wgsl. Do not edit.
// WGSL sha256 1f3a12a8c502c8dfac04b02202010f42d83fa4b50040d9c7f7f2982aed39144b
#pragma once
// Root parameter i of each pass binds WGSL binding i: a root CBV (b0) or a root UAV (u<i>).
namespace raw::d3d12_passes {
enum class Bind : unsigned char { Cbv, Uav };
struct PassInfo { const char* name; int bindCount; Bind binds[8]; };
inline constexpr PassInfo kPasses[] = {
    {"setup", 4, {Bind::Cbv, Bind::Uav, Bind::Uav, Bind::Uav}},
    {"raster", 8, {Bind::Cbv, Bind::Uav, Bind::Uav, Bind::Uav, Bind::Uav, Bind::Uav, Bind::Uav, Bind::Uav}},
    {"motion", 4, {Bind::Cbv, Bind::Uav, Bind::Uav, Bind::Uav}},
    {"ssao", 5, {Bind::Cbv, Bind::Uav, Bind::Uav, Bind::Uav, Bind::Uav}},
    {"rtao", 6, {Bind::Cbv, Bind::Uav, Bind::Uav, Bind::Uav, Bind::Uav, Bind::Uav}},
    {"shade", 6, {Bind::Cbv, Bind::Uav, Bind::Uav, Bind::Uav, Bind::Uav, Bind::Uav}},
};
}
