// Generated by scripts/wgsl_to_hlsl.py from src/gpu/common.wgsl and src/gpu/passes.wgsl. Do not edit.
// WGSL sha256 1f3a12a8c502c8dfac04b02202010f42d83fa4b50040d9c7f7f2982aed39144b
// Pass: ssao

// raw-native GPU passes: definitions shared by every pass.
// This WGSL is the one shader source. WebGPU runs it as written; the D3D12
// backend runs src/gpu/hlsl/, which scripts/wgsl_to_hlsl.py generates from it
// (CI fails when the two differ). The translator needs every let and var to
// carry an explicit type.
// Each function mirrors one C++ function in src/ line for line, with the same
// operation order, so the GPU computes the same float32 expressions as the CPU
// reference. Shader compilers may still fuse or reorder; the reconcile
// certificate (raw/gpu_reconcile.hpp) measures what that costs.

struct Params {
    float4 vp[4]; // current view-projection, rows (raw/mat.hpp is row-major)
    float4 pvp[4]; // previous view-projection, rows
    float4 light; // xyz direction, w intensity
    float4 misc; // x AO radius (world), y SSAO pixel radius
    uint w; uint h; uint ntri; uint rt_samples;
    uint ss_samples; uint rtao; uint pad0; uint pad1;
};

// Triangle input: 24 floats each. 0..8 world positions a,b,c; 9..17 normals; 18..20 albedo.
static const uint TRI_STRIDE = 24u;
// Triangle setup output: 16 floats each.
// 0 valid, 1..3 screen x, 4..6 screen y, 7..9 view distance, 10..12 1/w, 13 area,
// 14 unused, 15 unused. Integer bounds live in the parallel u32 array (4 per triangle).
static const uint SETUP_STRIDE = 16u;

// Screen-space AO (src/ssao.cpp).
ConstantBuffer<Params> P : register(b0);
RWStructuredBuffer<float4> position : register(u1);
RWStructuredBuffer<float4> normal : register(u2);
RWStructuredBuffer<float4> albedoMask : register(u3);
RWStructuredBuffer<float> aoSS : register(u4);

float vlen(float3 v) { return sqrt(v.x * v.x + v.y * v.y + v.z * v.z); }
// raw::normalize: l > 0 ? v * (1/l) : v
float3 vnorm(float3 v) {
    const float l = vlen(v);
    if (l > 0.0f) { const float s = 1.0f / l; return float3(v.x * s, v.y * s, v.z * s); }
    return v;
}
float3 vcross(float3 a, float3 b) {
    return float3(a.y * b.z - a.z * b.y, a.z * b.x - a.x * b.z, a.x * b.y - a.y * b.x);
}
float vdot(float3 a, float3 b) { return a.x * b.x + a.y * b.y + a.z * b.z; }
// raw::mul(Mat4, Vec4), row by row, left to right.
float mrow(float4 r, float4 v) { return r.x * v.x + r.y * v.y + r.z * v.z + r.w * v.w; }
float4 mmul(float4 m[4], float4 v) {
    return float4(mrow(m[0], v), mrow(m[1], v), mrow(m[2], v), mrow(m[3], v));
}
// The deterministic per-pixel hash of src/ssao.cpp and src/ray_ao.cpp.
float hash01(uint x, uint y, uint s) {
    uint h = x * 374761393u + y * 668265263u + s * 2246822519u;
    h = (h ^ (h >> 13u)) * 1274126177u;
    h = h ^ (h >> 16u);
    return float(h & 0xFFFFFFu) / 16777216.0f;
}
// std::lround: halves round away from zero (WGSL round() rounds halves to even).
int lround(float v) {
    if (v >= 0.0f) { return int(floor(v + 0.5f)); }
    return -int(floor(-v + 0.5f));
}
uint pix(uint x, uint y) { return y * P.w + x; }

[numthreads(8, 8, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    if (gid.x >= P.w || gid.y >= P.h) { return; }
    const uint i = pix(gid.x, gid.y);
    if (albedoMask[i].w == 0.0f) { aoSS[i] = 1.0f; return; }
    const float3 p = position[i].xyz;
    const float3 n = normal[i].xyz;
    const float R = P.misc.y;
    int occ = 0; int used = 0;
    for (uint s = 0u; s < P.ss_samples; s++) {
        const float a = hash01(gid.x, gid.y, s) * 6.2831853f;
        const float rad = (0.3f + 0.7f * hash01(gid.x, gid.y, s + 97u)) * R;
        const int sx = int(gid.x) + lround(cos(a) * rad);
        const int sy = int(gid.y) + lround(sin(a) * rad);
        if (sx < 0 || sy < 0 || sx >= int(P.w) || sy >= int(P.h)) { continue; }
        const uint j = pix(uint(sx), uint(sy));
        if (albedoMask[j].w == 0.0f) { continue; }
        used++;
        const float3 d = position[j].xyz - p;
        const float dist = vlen(d);
        if (dist < 1e-4f || dist > P.misc.x) { continue; }
        const float ndl = vdot(n, vnorm(d));
        if (ndl > 0.15f) { occ++; }
    }
    float v = 1.0f;
    if (used > 0) { v = 1.0f - float(occ) / float(used); }
    aoSS[i] = ((v < 0.0f) ? (0.0f) : (v));
}
