// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/common.wgsl and passes.wgsl. Do not edit.
// WGSL sha256 79182cc9fc4f0de1d951908f66f66344413be0c6a92a6f527495dfeb7d95a038
#pragma once
// Binding i of each pass is WGSL @group(0) @binding(i), with the access its
// declaration states. The D3D12 backend binds the uniform as a root CBV (b0) and
// every storage buffer as a root UAV (u<i>), read-only ones included.
#include "raw/rhi/rhi.hpp"
namespace raw::light_passes {
struct PassLayout { const char* name; int bindCount; rhi::Binding binds[8]; };
inline constexpr PassLayout kPasses[] = {
    {"light_cluster", 3, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite}},
    {"light_prefilter", 3, {rhi::Binding::Uniform, rhi::Binding::StorageReadWrite, rhi::Binding::StorageRead}},
};
}
