// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/common.wgsl and passes.wgsl. Do not edit.
// WGSL sha256 ede4a85a5c1ba1e853eafba0db26432e4b871ecdb4a7d0c9e5b38c7ca44f170f
#pragma once
// Binding i of each pass is WGSL @group(0) @binding(i), with the access its
// declaration states. The D3D12 backend binds the uniform as a root CBV (b0) and
// every storage buffer as a root UAV (u<i>), read-only ones included.
#include "raw/rhi/rhi.hpp"
namespace raw::pbr_passes {
struct PassLayout { const char* name; int bindCount; rhi::Binding binds[8]; };
inline constexpr PassLayout kPasses[] = {
    {"pbr_eval", 4, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite}},
};
}
