// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/common.wgsl and passes.wgsl. Do not edit.
// WGSL sha256 1d0c5c7d36be2c6aa954cc3c5c1ab987ab213f0463c8246ae69e76d3b66754c1
#pragma once
// Binding i of each pass is WGSL @group(0) @binding(i), with the access its
// declaration states. The D3D12 backend binds the uniform as a root CBV (b0) and
// every storage buffer as a root UAV (u<i>), read-only ones included.
#include "raw/rhi/rhi.hpp"
namespace raw::post_passes {
struct PassLayout { const char* name; int bindCount; rhi::Binding binds[8]; };
inline constexpr PassLayout kPasses[] = {
    {"post_gtao", 3, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite}},
    {"post_ssr", 3, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite}},
    {"post_taa", 6, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite}},
};
}
