// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/common.wgsl and passes.wgsl. Do not edit.
// WGSL sha256 33bf5032533b409282c3f931d1244cc04b6dd7e6d452c66557c7dae67663f644
#pragma once
// Binding i of each pass is WGSL @group(0) @binding(i), with the access its
// declaration states. The D3D12 backend binds the uniform as a root CBV (b0) and
// every storage buffer as a root UAV (u<i>), read-only ones included.
#include "raw/rhi/rhi.hpp"
namespace raw::pt_passes {
struct PassLayout { const char* name; int bindCount; rhi::Binding binds[8]; };
inline constexpr PassLayout kPasses[] = {
    {"pt_trace", 8, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite}},
    {"pt_finish", 3, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite}},
};
}
