// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/raster.wgsl. Do not edit.
// WGSL sha256 899319093bd45fd62feb145418c5590edf5674c435a67884e0fdd43960ec439b
#pragma once
// Binding i of each raster pass is WGSL @group(0) @binding(i). The D3D12 backend
// binds the uniform as a root CBV (b0), each texture as an SRV table (t<k>) and
// each sampler as a sampler table (s<k>), k counting that kind in order.
#include "raw/rhi/rhi.hpp"
namespace raw::raster_passes {
struct RasterLayout { const char* name; int bindCount; rhi::RasterBinding binds[8]; };
inline constexpr RasterLayout kRasters[] = {
    {"texture_identity", 3, {rhi::RasterBinding::Uniform, rhi::RasterBinding::Texture, rhi::RasterBinding::Sampler}},
    {"fmt_pattern", 1, {rhi::RasterBinding::Uniform}},
    {"depth_tris", 1, {rhi::RasterBinding::StorageRead}},
    {"gbuffer", 2, {rhi::RasterBinding::Uniform, rhi::RasterBinding::StorageRead}},
};
}
