// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/raster.wgsl. Do not edit.
// WGSL sha256 f963b0081476df6029aa6cf7c157bf4274ad834fe9b1022f9b016b6234d2cca0
#pragma once
// Binding i of each raster pass is WGSL @group(0) @binding(i). The D3D12 backend
// binds the uniform as a root CBV (b0), each texture as an SRV table (t<k>) and
// each sampler as a sampler table (s<k>), k counting that kind in order.
#include "raw/rhi/rhi.hpp"
namespace raw::raster_passes {
struct RasterLayout { const char* name; int bindCount; rhi::RasterBinding binds[8]; };
inline constexpr RasterLayout kRasters[] = {
    {"texture_identity", 3, {rhi::RasterBinding::Uniform, rhi::RasterBinding::Texture, rhi::RasterBinding::Sampler}},
};
}
