// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/common.wgsl and passes.wgsl. Do not edit.
// WGSL sha256 cd3acdcace9cfcf57f877947265290e24f5e21148b70a95c05651dc3c909a114
#pragma once
// Binding i of each pass is WGSL @group(0) @binding(i), with the access its
// declaration states. The D3D12 backend binds the uniform as a root CBV (b0) and
// every storage buffer as a root UAV (u<i>), read-only ones included.
#include "raw/rhi/rhi.hpp"
namespace raw::rt_passes {
struct PassLayout { const char* name; int bindCount; rhi::Binding binds[8]; };
inline constexpr PassLayout kPasses[] = {
    {"rt_bounds_chunk", 3, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite}},
    {"rt_bounds_final", 2, {rhi::Binding::Uniform, rhi::Binding::StorageReadWrite}},
    {"rt_morton", 5, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite, rhi::Binding::StorageReadWrite}},
    {"rt_sort_step", 3, {rhi::Binding::Uniform, rhi::Binding::StorageReadWrite, rhi::Binding::StorageReadWrite}},
    {"rt_leaves", 6, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite, rhi::Binding::StorageReadWrite, rhi::Binding::StorageReadWrite}},
    {"rt_ploc_nn", 4, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite}},
    {"rt_ploc_flags", 4, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite, rhi::Binding::StorageReadWrite}},
    {"rt_scan_chunk", 3, {rhi::Binding::Uniform, rhi::Binding::StorageReadWrite, rhi::Binding::StorageReadWrite}},
    {"rt_scan_top", 2, {rhi::Binding::Uniform, rhi::Binding::StorageReadWrite}},
    {"rt_scan_add", 3, {rhi::Binding::Uniform, rhi::Binding::StorageReadWrite, rhi::Binding::StorageRead}},
    {"rt_ploc_merge", 8, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite, rhi::Binding::StorageReadWrite, rhi::Binding::StorageReadWrite}},
    {"rt_trace", 6, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite}},
};
}
