// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/common.wgsl and passes.wgsl. Do not edit.
// WGSL sha256 298ebcda3c307af916c88771edfe7df93b08ff734dc684c31b1a6278e129efe6
#pragma once
// Binding i of each pass is WGSL @group(0) @binding(i), with the access its
// declaration states. The D3D12 backend binds the uniform as a root CBV (b0) and
// every storage buffer as a root UAV (u<i>), read-only ones included.
#include "raw/rhi/rhi.hpp"
namespace raw::sdf_passes {
struct PassLayout { const char* name; int bindCount; rhi::Binding binds[8]; };
inline constexpr PassLayout kPasses[] = {
    {"sdf_march", 3, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite}},
    {"sdf_terms", 4, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite}},
    {"sdf_fog", 4, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite}},
    {"sdf_god", 4, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite}},
    {"sdf_composite", 6, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite}},
};
}
