// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/common.wgsl and passes.wgsl. Do not edit.
// WGSL sha256 c2cbfdb3e556b4212aade08181ec416f712c3ea1068862e2bc60b23e729edec0
#pragma once
// Binding i of each pass is WGSL @group(0) @binding(i), with the access its
// declaration states. The D3D12 backend binds the uniform as a root CBV (b0) and
// every storage buffer as a root UAV (u<i>), read-only ones included.
#include "raw/rhi/rhi.hpp"
namespace raw::shadow_passes {
struct PassLayout { const char* name; int bindCount; rhi::Binding binds[8]; };
inline constexpr PassLayout kPasses[] = {
    {"shadow_lookup", 5, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite}},
    {"shadow_contact", 4, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite}},
};
}
