// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/common.wgsl and passes.wgsl. Do not edit.
// WGSL sha256 8fa08424ec68ee1de040b090e671897ce9897be2cb75cca59c2f4637b1c30632
#pragma once
// Binding i of each pass is WGSL @group(0) @binding(i), with the access its
// declaration states. The D3D12 backend binds the uniform as a root CBV (b0) and
// every storage buffer as a root UAV (u<i>), read-only ones included.
#include "raw/rhi/rhi.hpp"
namespace raw::threads_passes {
struct PassLayout { const char* name; int bindCount; rhi::Binding binds[8]; };
inline constexpr PassLayout kPasses[] = {
    {"threads_init", 2, {rhi::Binding::Uniform, rhi::Binding::StorageReadWrite}},
    {"threads_rd_seed", 2, {rhi::Binding::Uniform, rhi::Binding::StorageReadWrite}},
    {"threads_rd", 3, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite}},
    {"threads_decay", 2, {rhi::Binding::Uniform, rhi::Binding::StorageReadWrite}},
    {"threads_advance", 4, {rhi::Binding::Uniform, rhi::Binding::StorageReadWrite, rhi::Binding::StorageReadWrite, rhi::Binding::StorageRead}},
    {"threads_pyr_first", 3, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite}},
    {"threads_pyr_next", 3, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite}},
    {"threads_finish", 5, {rhi::Binding::Uniform, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageRead, rhi::Binding::StorageReadWrite}},
};
}
