#!/usr/bin/env python3
"""Generate the D3D12 compute shaders from the WGSL passes.

The WGSL in src/renderer/gpu/shaders/common.wgsl and passes.wgsl is the one
shader source. This script translates each "//@pass <name>" section, with the
shared code in front of it, into src/renderer/gpu/shaders/hlsl/<name>.hlsl, and
writes every pass's binding layout (binding i and its access, read from the
WGSL declaration) into src/renderer/gpu/shaders/pass_layout.hpp. The renderer
declares each pass's frame-graph accesses from that layout and the RHI builds
pipeline layouts from it, so no binding list is written by hand. The files are
committed so the build needs no Python; CI runs this script with --check and
fails when a WGSL edit was not regenerated.

The translator accepts a deliberately small WGSL subset and stops with an error
on anything outside it, so an unsupported construct can never be translated
silently wrong:
  - every `let` and `var` carries an explicit type;
  - statements and expressions fit on one line;
  - bindings are group 0, numbered 0..n-1 in order: binding 0 is the uniform,
    every other binding is a storage buffer (array<T>);
  - pointer parameters are ptr<function, T> and become HLSL inout parameters.

Usage: python scripts/wgsl_to_hlsl.py [--check | --selftest]
"""
import hashlib
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

ROOT = Path(__file__).resolve().parents[1]
GPU = ROOT / "src" / "renderer" / "gpu" / "shaders"
OUT = GPU / "hlsl"
LAYOUT = "pass_layout.hpp"   # written beside the WGSL, not into hlsl/
HEADER = ("// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/common.wgsl and passes.wgsl."
          " Do not edit.\n")

from wgsl_hlsl_expr import (RESERVED, TranslateError, signature, statement,  # noqa: E402
                             TYPE_RE, htype, literals)


def split_comment(line):
    i = line.find("//")
    return (line, "") if i < 0 else (line[:i], line[i:])


def items(text):
    """Top-level items: (kind, lines). Comments and attributes join the next item."""
    out, cur, depth = [], [], 0
    for line in text.split("\n"):
        code = split_comment(line)[0]
        cur.append(line)
        depth += code.count("{") - code.count("}")
        stripped = code.strip()
        if depth == 0 and stripped and not stripped.startswith("@compute") and stripped.endswith(("}", ";")):
            first = next(split_comment(l)[0].strip() for l in cur if split_comment(l)[0].strip())
            kind = ("struct" if first.startswith("struct") else "const" if first.startswith("const")
                    else "binding" if first.startswith("@group") else "fn")
            out.append((kind, cur))
            cur = []
    if any(split_comment(l)[0].strip() for l in cur):
        raise TranslateError("trailing code outside any item")
    return out


def raster_binding(code, s, binds):
    """A raster pass's binding: an optional uniform first, then textures, samplers and
    read-only storage buffers (RHI version 3: vertex pulling). A storage buffer is a UAV,
    u<k> with k counting storage bindings in order, like the compute passes' buffers."""
    st = re.fullmatch(r"\s*@group\(0\)\s*@binding\((\d+)\)\s*var<storage(?:,\s*read)?>\s*(\w+)\s*:\s*array<\s*(\w+)\s*>\s*;\s*", code)
    if st:
        if int(st.group(1)) != len(binds):
            raise TranslateError(f"bindings must be group 0 and numbered in order: {s!r}")
        binds.append("StorageRead")
        return f"RWStructuredBuffer<{htype(st.group(3))[0]}> {st.group(2)} : register(u{binds.count('StorageRead') - 1});"
    m = re.fullmatch(r"\s*@group\(0\)\s*@binding\((\d+)\)\s*var(?:<(uniform)>)?\s*(\w+)\s*:\s*([\w<>]+)\s*;\s*", code)
    if not m or int(m.group(1)) != len(binds):
        raise TranslateError(f"bindings must be group 0 and numbered in order: {s!r}")
    if m.group(2) == "uniform":
        if binds:
            raise TranslateError(f"a raster pass's uniform must be binding 0: {s!r}")
        binds.append("Uniform")
        return f"ConstantBuffer<{m.group(4)}> {m.group(3)} : register(b0);"
    if m.group(4) == "texture_2d<f32>":
        binds.append("Texture")
        return f"Texture2D<float4> {m.group(3)} : register(t{binds.count('Texture') - 1});"
    if m.group(4) == "sampler":
        binds.append("Sampler")
        return f"SamplerState {m.group(3)} : register(s{binds.count('Sampler') - 1});"
    raise TranslateError(f"raster bindings are a uniform, texture_2d<f32>, sampler or read-only storage: {s!r}")


def struct_field(code, struct_name):
    """One struct field. Stage attributes become HLSL semantics: @builtin(position) is
    SV_Position; @location(k) is TEXCOORDk (an interpolant), or SV_Targetk in a struct whose
    name ends in Targets (a fragment output); @interpolate(flat) is nointerpolation."""
    m = re.fullmatch(r"(\s*)((?:@\w+\([^)]*\)\s*)*)(\w+)\s*:\s*(" + TYPE_RE + r")\s*,\s*", code)
    if not m:
        raise TranslateError(f"unsupported struct field {code.strip()!r}")
    lead, attrs, name, typ = m.groups()
    t, suffix = htype(typ)
    sem, mod = "", ""
    for a in re.findall(r"@\w+\([^)]*\)", attrs):
        loc = re.fullmatch(r"@location\((\d+)\)", a)
        if a == "@builtin(position)":
            sem = " : SV_Position"
        elif loc:
            sem = f" : SV_Target{loc.group(1)}" if struct_name.endswith("Targets") else f" : TEXCOORD{loc.group(1)}"
        elif a == "@interpolate(flat)":
            mod = "nointerpolation "
        else:
            raise TranslateError(f"unsupported field attribute {a!r}")
    return f"{lead}{mod}{t} {name}{suffix}{sem};"


def check_loop_names(lines):
    """A function may not declare the same loop variable twice. HLSL 2021 (dxc -HV 2021)
    scopes it to the loop, but Slang applies the older rule that it belongs to the enclosing
    block, so a reused name is an error there (the A5 spike, docs/architecture/A5-SPIKE.md)."""
    names = re.findall(r"\bfor\s*\(\s*var\s+(\w+)", "\n".join(split_comment(l)[0] for l in lines))
    dup = sorted({n for n in names if names.count(n) > 1})
    if dup:
        raise TranslateError(f"loop variable declared twice in one function (Slang rejects it): {dup}")


def translate_item(kind, lines, binds, raster=False):
    if kind == "fn":
        check_loop_names(lines)
    out, ptrs, attrs = [], [], ""
    for line in lines:
        code, comment = split_comment(line)
        s = code.strip()
        if not s:
            out.append(line.rstrip())
            continue
        if kind == "struct":
            if s.startswith("struct"):
                struct_name = re.match(r"\s*struct\s+(\w+)", code).group(1)
                code = code.replace("{", "{")
            elif s == "}":
                code = code.replace("}", "};")
            else:
                if "@" in code:
                    code = struct_field(code, struct_name)
                else:
                    def field(m):
                        t, suffix = htype(m.group(2))
                        return f"{t} {m.group(1)}{suffix};"
                    code = re.sub(r"(\w+)\s*:\s*(" + TYPE_RE + r")\s*,", field, code)
        elif kind == "const":
            m = re.fullmatch(r"(\s*)const\s+(\w+)\s*:\s*(\w+)\s*=\s*(.*);\s*", code)
            if not m:
                raise TranslateError(f"unsupported const {s!r}")
            code = f"{m.group(1)}static const {htype(m.group(3))[0]} {m.group(2)} = {literals(m.group(4))};"
        elif kind == "binding" and raster:
            code = raster_binding(code, s, binds)
        elif kind == "binding":
            m = re.fullmatch(r"\s*@group\(0\)\s*@binding\((\d+)\)\s*var<([\w, ]+)>\s*(\w+)\s*:\s*(" + TYPE_RE + r")\s*;\s*", code)
            if not m or int(m.group(1)) != len(binds):
                raise TranslateError(f"bindings must be group 0 and numbered in order: {s!r}")
            space = [x.strip() for x in m.group(2).split(",")]
            if space == ["uniform"] and len(binds) == 0:
                code = f"ConstantBuffer<{m.group(4)}> {m.group(3)} : register(b0);"
                binds.append("Uniform")
            elif space[0] == "storage" and len(binds) > 0:
                el = re.fullmatch(r"array<\s*(\w+|atomic<\s*u32\s*>)\s*>", m.group(4))
                if not el:
                    raise TranslateError(f"storage bindings must be runtime arrays: {s!r}")
                # Every storage buffer is a UAV, read-only ones included, so the host keeps
                # one resource state for all of them and orders passes with UAV barriers.
                code = f"RWStructuredBuffer<{htype(el.group(1))[0]}> {m.group(3)} : register(u{m.group(1)});"
                mode = space[1] if len(space) > 1 else "read"   # WGSL storage defaults to read
                if mode not in ("read", "read_write"):
                    raise TranslateError(f"unsupported storage access {mode!r}: {s!r}")
                binds.append("StorageRead" if mode == "read" else "StorageReadWrite")
            else:
                raise TranslateError(f"binding 0 must be the uniform, the rest storage: {s!r}")
        elif kind == "fn":
            if s.startswith("@"):
                attrs += s + " "
                continue
            if s.startswith("fn "):
                head, rest, ptrs = signature(code, attrs.strip())
                code = head + (" " + statement(rest, ptrs).strip() if rest.strip() else "")
            else:
                code = statement(code, ptrs)
        out.append((code.rstrip() + (" " + comment if comment else "")).rstrip() if code.strip() else comment.rstrip())
    return out


def check_identifiers(text):
    code = "\n".join(split_comment(l)[0] for l in text.split("\n"))
    code = re.sub(r"\bvar<[^>]*>", "var", code)   # address spaces are not identifiers
    bad =sorted(set(re.findall(r"\b\w+\b", code)) & RESERVED)
    if bad:
        raise TranslateError(f"WGSL identifiers that are HLSL keywords: {bad}")


def translate(common, passes, layout=LAYOUT, ns="gpu_passes", header=HEADER):
    """Returns {file name: content}."""
    sections = re.split(r"^//@pass (\w+)[^\S\n]*\n", passes, flags=re.M)
    if sections[0].strip():
        raise TranslateError("code before the first //@pass marker")
    digest = hashlib.sha256((common + passes).encode()).hexdigest()
    files, manifest = {}, []
    for name, body in zip(sections[1::2], sections[2::2]):
        src = common + "\n" + body
        check_identifiers(src)
        groups = {"struct": [], "const": [], "binding": [], "fn": []}
        for kind, lines in items(src):
            groups[kind].append((kind, lines))
        binds, out = [], []
        for kind in ("struct", "const", "binding", "fn"):   # HLSL needs declaration before use
            for k, lines in groups[kind]:
                out += translate_item(k, lines, binds)
        text = "\n".join(out)
        text = re.sub(r"\n{3,}", "\n\n", text).strip("\n") + "\n"
        files[f"{name}.hlsl"] = header + f"// WGSL sha256 {digest}\n// Pass: {name}\n\n" + text
        manifest.append((name, binds))
    hpp = [HEADER.rstrip("\n"), f"// WGSL sha256 {digest}", "#pragma once",
           "// Binding i of each pass is WGSL @group(0) @binding(i), with the access its",
           "// declaration states. The D3D12 backend binds the uniform as a root CBV (b0) and",
           "// every storage buffer as a root UAV (u<i>), read-only ones included.",
           '#include "raw/rhi/rhi.hpp"',
           f"namespace raw::{ns} {{",
           "struct PassLayout { const char* name; int bindCount; rhi::Binding binds[8]; };",
           "inline constexpr PassLayout kPasses[] = {"]
    for name, binds in manifest:
        if len(binds) > 8:
            raise TranslateError(f"pass {name} has more than 8 bindings")
        hpp.append(f"    {{\"{name}\", {len(binds)}, {{{', '.join('rhi::Binding::' + b for b in binds)}}}}},")
    hpp += ["};", "}", ""]
    files[layout] = "\n".join(hpp)
    return files


RASTER = "raster.wgsl"
RASTER_LAYOUT = "raster_layout.hpp"
RASTER_HEADER = ("// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/raster.wgsl."
                 " Do not edit.\n")


def translate_raster(text):
    """Each "//@raster <name>" section of raster.wgsl, alone, as one HLSL file with the
    entry points vs and fs, and every section's binding layout in raster_layout.hpp."""
    sections = re.split(r"^//@raster (\w+)[^\S\n]*\n", text, flags=re.M)
    digest = hashlib.sha256(text.encode()).hexdigest()
    files, manifest = {}, []
    for name, body in zip(sections[1::2], sections[2::2]):
        check_identifiers(body)
        groups = {"struct": [], "const": [], "binding": [], "fn": []}
        for kind, lines in items(body):
            groups[kind].append((kind, lines))
        if [n for _, ls in groups["fn"] for n in re.findall(r"^\s*fn\s+(\w+)", "\n".join(ls), flags=re.M)][-2:] != ["vs", "fs"]:
            raise TranslateError(f"raster pass {name} must end with the entry points vs then fs")
        binds, out = [], []
        for kind in ("struct", "const", "binding", "fn"):
            for k, lines in groups[kind]:
                out += translate_item(k, lines, binds, raster=True)
        text_out = re.sub(r"\n{3,}", "\n\n", "\n".join(out)).strip("\n") + "\n"
        files[f"{name}.hlsl"] = RASTER_HEADER + f"// WGSL sha256 {digest}\n// Raster pass: {name} (entry points vs, fs)\n\n" + text_out
        manifest.append((name, binds))
    hpp = [RASTER_HEADER.rstrip("\n"), f"// WGSL sha256 {digest}", "#pragma once",
           "// Binding i of each raster pass is WGSL @group(0) @binding(i). The D3D12 backend",
           "// binds the uniform as a root CBV (b0), each texture as an SRV table (t<k>) and",
           "// each sampler as a sampler table (s<k>), k counting that kind in order.",
           '#include "raw/rhi/rhi.hpp"',
           "namespace raw::raster_passes {",
           "struct RasterLayout { const char* name; int bindCount; rhi::RasterBinding binds[8]; };",
           "inline constexpr RasterLayout kRasters[] = {"]
    for name, binds in manifest:
        hpp.append(f"    {{\"{name}\", {len(binds)}, {{{', '.join('rhi::RasterBinding::' + b for b in binds)}}}}},")
    hpp += ["};", "}", ""]
    files[RASTER_LAYOUT] = "\n".join(hpp)
    return files


THREADS = "threads.wgsl"
THREADS_LAYOUT = "threads_layout.hpp"
THREADS_HEADER = ("// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/threads.wgsl."
                  " Do not edit.\n")


PBR = "pbr.wgsl"
CUBE = "cube.wgsl"          # a shared fragment of pure functions, in front of pbr.wgsl and light.wgsl
LIGHT = "light.wgsl"
LIGHT_LAYOUT = "light_layout.hpp"
LIGHT_HEADER = ("// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/cube.wgsl and light.wgsl."
                " Do not edit.\n")
POST = "post.wgsl"
POST_LAYOUT = "post_layout.hpp"
POST_HEADER = ("// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/post.wgsl."
               " Do not edit.\n")
SHADOW = "shadow.wgsl"
SHADOW_LAYOUT = "shadow_layout.hpp"
SHADOW_HEADER = ("// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/shadow.wgsl."
                 " Do not edit.\n")
SWR = "swr.wgsl"            # the software rasterizer (RT stage R1): its own shared code, no prelude
SWR_LAYOUT = "swr_layout.hpp"
SWR_HEADER = ("// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/swr.wgsl."
              " Do not edit.\n")
RT = "rt.wgsl"              # the ray-tracing passes (RT stage R2): its own shared code, no prelude
RT_LAYOUT = "rt_layout.hpp"
RT_HEADER = ("// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/rt.wgsl."
             " Do not edit.\n")
PBR_LAYOUT = "pbr_layout.hpp"
PBR_HEADER = ("// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/pbr.wgsl."
              " Do not edit.\n")


def translate_all(read):
    """Every generated file: the renderer's passes, then the Threads module, whose
    shared code is everything in threads.wgsl before its first pass marker."""
    files = translate(read(GPU / "common.wgsl"), read(GPU / "passes.wgsl"))
    text = read(GPU / THREADS)
    i = text.find("//@pass ")
    files.update(translate(text[:i], text[i:], THREADS_LAYOUT, "threads_passes", THREADS_HEADER))
    cube = read(GPU / CUBE)
    for name, layout, ns, header in ((PBR, PBR_LAYOUT, "pbr_passes", PBR_HEADER), (LIGHT, LIGHT_LAYOUT, "light_passes", LIGHT_HEADER)):
        text = read(GPU / name)
        i = text.find("//@pass ")
        files.update(translate(cube + "\n" + text[:i], text[i:], layout, ns, header))
    text = read(GPU / SHADOW)
    i = text.find("//@pass ")
    files.update(translate(text[:i], text[i:], SHADOW_LAYOUT, "shadow_passes", SHADOW_HEADER))
    text = read(GPU / POST)
    i = text.find("//@pass ")
    files.update(translate(text[:i], text[i:], POST_LAYOUT, "post_passes", POST_HEADER))
    text = read(GPU / SWR)
    i = text.find("//@pass ")
    files.update(translate(text[:i], text[i:], SWR_LAYOUT, "swr_passes", SWR_HEADER))
    text = read(GPU / RT)
    i = text.find("//@pass ")
    files.update(translate(text[:i], text[i:], RT_LAYOUT, "rt_passes", RT_HEADER))
    files.update(translate_raster(read(GPU / RASTER)))
    return files


def selftest():
    """The translator must refuse what it cannot translate faithfully."""
    head = "struct Params {\n    w: u32,\n}\n"
    bind = "@group(0) @binding(0) var<uniform> P: Params;\n"
    body = "@compute @workgroup_size(8, 8)\nfn main(@builtin(global_invocation_id) gid: vec3u) {\n    %s\n}\n"
    refused = {"untyped let": "//@pass t\n" + bind + body % "let x = 1.0;",
               "untyped var": "//@pass t\n" + bind + body % "var y = 0u;",
               "HLSL keyword": "//@pass t\n" + bind + body % "let sample: f32 = 1.0;",
               "binding out of order": "//@pass t\n" + bind.replace("binding(0)", "binding(1)") + body % "return;"}
    for what, src in refused.items():
        try:
            translate(head, src)
        except TranslateError:
            continue
        print(f"selftest: accepted {what}", file=sys.stderr)
        return 1
    out = translate(head, "//@pass t\n" + bind + body % "let v: vec3f = vec3f(select(0.0, 1.0, P.w > 0u));")["t.hlsl"]
    want = "const float3 v = ((float3)(((P.w > 0u) ? (1.0f) : (0.0f))));"
    if want not in out:
        print("selftest: splat and select translated wrong:\n" + out, file=sys.stderr)
        return 1
    store = "@group(0) @binding(1) var<storage, read_write> acc: array<atomic<u32>>;\n"
    out = translate(head, "//@pass t\n" + bind + store + body % "atomicAdd(&acc[P.w], u32(mix(0.0, fract(2.5), 0.5)));")["t.hlsl"]
    if "InterlockedAdd(acc[P.w], uint(lerp(0.0f, frac(2.5f), 0.5f)));" not in out or "RWStructuredBuffer<uint> acc" not in out:
        print("selftest: atomics, mix or fract translated wrong:\n" + out, file=sys.stderr)
        return 1
    out = translate(head, "//@pass t\n" + bind + body % "let v: vec2f = vec2f(2.0 * select(1.0, 2.0, P.w >= 2u), 3.0);")["t.hlsl"]
    if "float2(2.0f * ((P.w >= 2u) ? (2.0f) : (1.0f)), 3.0f)" not in out:
        print("selftest: a comparison inside a constructor hid its comma:\n" + out, file=sys.stderr)
        return 1
    for what, stmt in {"pack4x8unorm": "let v: u32 = pack4x8unorm(vec4f(1.0));",
                       "atomicAdd as a value": "let v: u32 = atomicAdd(&acc[0u], 1u);",
                       "round (WGSL rounds half to even)": "let v: f32 = round(0.5);"}.items():
        try:
            translate(head, "//@pass t\n" + bind + store + body % stmt)
        except TranslateError:
            continue
        print(f"selftest: accepted {what}", file=sys.stderr)
        return 1
    rhead = "//@raster r\n@group(0) @binding(0) var t: texture_2d<f32>;\n@group(0) @binding(1) var s: sampler;\n"
    vs = "@vertex\nfn vs(@builtin(vertex_index) i: u32) -> @builtin(position) vec4f {\n    return vec4f(0.0);\n}\n"
    fs = "@fragment\nfn fs(@builtin(position) q: vec4f) -> @location(0) vec4f {\n    return textureSampleLevel(t, s, q.xy, 0.0);\n}\n"
    out = translate_raster(rhead + vs + fs)["r.hlsl"]
    for want in ("Texture2D<float4> t : register(t0);", "SamplerState s : register(s0);",
                 "float4 vs(uint i : SV_VertexID) : SV_Position {", "float4 fs(float4 q : SV_Position) : SV_Target0 {",
                 "return t.SampleLevel(s, q.xy, 0.0f);"):
        if want not in out:
            print(f"selftest: raster translation lacks {want!r}:\n" + out, file=sys.stderr)
            return 1
    for what, src in {"fragment returning a builtin": rhead + vs + fs.replace("@location(0) vec4f", "@builtin(position) vec4f"),
                      "writable storage in a raster pass": rhead.replace("var t: texture_2d<f32>", "var<storage, read_write> t: array<f32>") + vs + fs,
                      "textureSample with derivatives": rhead + vs + fs.replace("textureSampleLevel(t, s, q.xy, 0.0)", "textureSample(t, s, q.xy)"),
                      "entry points in the wrong order": rhead + fs + vs}.items():
        try:
            translate_raster(src)
        except TranslateError:
            continue
        print(f"selftest: accepted {what}", file=sys.stderr)
        return 1
    loops = "@compute @workgroup_size(8, 8)\nfn main(@builtin(global_invocation_id) gid: vec3u) {\n    for (var k: u32 = 0u; k < 3u; k++) {\n    }\n    for (var k: u32 = 0u; k < 3u; k++) {\n    }\n}\n"
    try:
        translate(head, "//@pass t\n" + bind + loops)
        print("selftest: accepted a loop variable declared twice in one function", file=sys.stderr)
        return 1
    except TranslateError:
        pass
    # RHI version 3: vertex pulling, a vertex-output struct, flat interpolants, and several
    # fragment targets in a struct named *Targets.
    v3 = ("//@raster g\n@group(0) @binding(0) var<storage, read> pos: array<f32>;\n"
          "struct VsOut {\n    @builtin(position) clip: vec4f,\n    @location(0) n: vec3f,\n    @location(1) @interpolate(flat) id: u32,\n}\n"
          "struct GTargets {\n    @location(0) a: vec4f,\n    @location(1) b: vec4f,\n}\n"
          "@vertex\nfn vs(@builtin(vertex_index) i: u32) -> VsOut {\n    var o: VsOut;\n    o.clip = vec4f(pos[i], 0.0, 0.0, 1.0);\n    return o;\n}\n"
          "@fragment\nfn fs(v: VsOut) -> GTargets {\n    var t: GTargets;\n    t.a = v.clip;\n    return t;\n}\n")
    out = translate_raster(v3)["g.hlsl"]
    for want in ("RWStructuredBuffer<float> pos : register(u0);", "float4 clip : SV_Position;", "float3 n : TEXCOORD0;",
                 "nointerpolation uint id : TEXCOORD1;", "float4 b : SV_Target1;", "VsOut o = (VsOut)0;", "GTargets fs(VsOut v) {"):
        if want not in out:
            print(f"selftest: RHI v3 raster translation lacks {want!r}:\n" + out, file=sys.stderr)
            return 1
    print("wgsl_to_hlsl: selftest passed")
    return 0


def main(argv):
    if "--selftest" in argv:
        return selftest()
    check = "--check" in argv
    read = lambda p: p.read_text(encoding="utf-8").replace("\r\n", "\n")
    try:
        files = translate_all(read)
    except TranslateError as e:
        print(f"wgsl_to_hlsl: {e}", file=sys.stderr)
        return 2
    stale = []
    for name, text in files.items():
        path = (GPU if name.endswith(".hpp") else OUT) / name
        old = read(path) if path.exists() else None
        if old != text:
            stale.append(name)
            if not check:
                OUT.mkdir(parents=True, exist_ok=True)
                path.write_bytes(text.encode("utf-8"))
    extra = sorted(p.name for p in OUT.glob("*") if p.name not in files or p.name == LAYOUT) if OUT.exists() else []
    if check:
        if stale or extra:
            print("wgsl_to_hlsl: generated HLSL is out of date with the WGSL: "
                  + ", ".join(stale + [f"{e} (not generated)" for e in extra])
                  + "\nrun: python scripts/wgsl_to_hlsl.py", file=sys.stderr)
            return 1
        print(f"wgsl_to_hlsl: {len(files)} generated files match the WGSL")
        return 0
    print(f"wgsl_to_hlsl: wrote {len(stale)} of {len(files)} files" + (f"; unexpected files: {extra}" if extra else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
