// Source frames for the lab 2 parity pages, sheets and gallery. All are generated by our own code
// (author, 2026-10-10: "No test models, only full owned assets").
//   labSource("street" | "day" | "edges" | "box" | "game", w, h, t)
// street/day: the raymarched street (scene-linear, with albedo, irradiance, normals and camera).
// edges: hard-edged scene-linear plate (bars, a disc, small dots) for edge-sensitive passes.
// box: a black field with a white box in the upper middle, as R'G'B' signal (for the CRT sag).
// game: fixtures/game.mjs, R'G'B' signal.
import { streetScene } from "../fixtures/street.mjs";
import { gameFrame } from "../fixtures/game.mjs";

export function edgesPlate(w, h) {
  const d = new Float32Array(w * h * 4);
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
    const u = x / w, v = y / h; let c = [0.05, 0.05, 0.06];
    if (v < 0.4) c = Math.floor(u * 8) % 2 ? [1.2, 1.1, 0.9] : [0.12, 0.1, 0.09];
    if (Math.hypot(u - 0.3, (v - 0.7) * h / w) < 0.12) c = [1.5, 0.6, 0.3];
    if (u > 0.55 && v > 0.55 && (x % 9) < 2 && (y % 9) < 2) c = [1.5, 1.5, 1.4];
    d.set([...c, 1], (y * w + x) * 4);
  }
  return { width: w, height: h, data: d };
}
export function boxSignal(w, h) {
  const d = new Float32Array(w * h * 4);
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) { const on = x > w * 0.3 && x < w * 0.7 && y > h * 0.2 && y < h * 0.4; d.set(on ? [1, 1, 1, 1] : [0, 0, 0, 1], (y * w + x) * 4); }
  return { width: w, height: h, data: d };
}
// The street as R'G'B' signal: the same soft shoulder as the display encode, then sRGB.
export function toSignal(f, gain = 2.4) {
  const d = new Float32Array(f.data.length);
  const enc = (v) => { const l = Math.min(1, 1 - Math.exp(-Math.max(0, v) * gain)); return l <= 0.0031308 ? l * 12.92 : 1.055 * Math.pow(l, 1 / 2.4) - 0.055; };
  for (let i = 0; i < d.length; i++) d[i] = (i & 3) === 3 ? 1 : enc(f.data[i]);
  return { width: f.width, height: f.height, data: d };
}
const cache = new Map();
export function labSource(name, w, h, t = 0) {
  const key = `${name}/${w}/${h}/${t}`;
  if (cache.has(key)) return cache.get(key);
  let f;
  if (name === "street") f = streetScene(w, h, t);
  else if (name === "day") f = streetScene(w, h, t, { daylight: true });
  else if (name === "edges") f = edgesPlate(w, h);
  else if (name === "box") f = boxSignal(w, h);
  else if (name === "game") f = gameFrame(w, h, t);
  else if (name === "street-signal") f = toSignal(streetScene(w, h, t));
  else throw new Error("unknown source " + name);
  cache.set(key, f);
  return f;
}
// Display-linear frames (0..1) for passes that model the display itself (CRT purity):
// "street" through the soft shoulder, or flat "white" and "red" plates.
export function displayLinear(name, w, h) {
  if (name === "white" || name === "red") { const c = name === "white" ? [1, 1, 1] : [1, 0, 0], d = new Float32Array(w * h * 4); for (let i = 0; i < w * h; i++) d.set([...c, 1], i * 4); return { width: w, height: h, data: d }; }
  const f = labSource(name, w, h), d = new Float32Array(f.data.length);
  for (let i = 0; i < d.length; i++) d[i] = (i & 3) === 3 ? 1 : Math.min(1, 1 - Math.exp(-Math.max(0, f.data[i]) * 2.4));
  return { width: w, height: h, data: d };
}
