# The RHI backends. A build links one, with the shader library in the format
# that backend takes. The default build links the null backend
# (src/rhi/null/), which answers --gpu with exit code 4 and an unverifiable
# certificate, and the library stays dependency-free.
#
#   RAW_NATIVE_GPU=ON        (Emscripten only) a second WebAssembly CLI,
#                            raw-native-gpu.mjs, built with Emscripten's WebGPU
#                            port and JSPI: src/rhi/webgpu/ and the WGSL passes.
#   RAW_NATIVE_GPU_D3D12=ON  (Windows only) raw_native_cli renders --gpu on
#                            D3D12: src/rhi/d3d12/. The passes are
#                            src/renderer/gpu/shaders/hlsl/*.hlsl, generated from
#                            the WGSL by scripts/wgsl_to_hlsl.py, compiled to DXIL
#                            by the Windows SDK's dxc.exe at build time. Links
#                            d3d12.lib and dxgi.lib from the Windows SDK; nothing else.
option(RAW_NATIVE_GPU "Build the WebGPU CLI (Emscripten only)" OFF)
option(RAW_NATIVE_GPU_D3D12 "Build the D3D12 backend into raw_native_cli (Windows only)" OFF)

set(RAW_NATIVE_SHADERS "${CMAKE_CURRENT_SOURCE_DIR}/src/renderer/gpu/shaders")
# Embed the WGSL sources as C++ raw strings.
function(raw_native_embed_wgsl out)
    file(READ "${RAW_NATIVE_SHADERS}/common.wgsl" common)
    file(READ "${RAW_NATIVE_SHADERS}/passes.wgsl" passes)
    file(READ "${RAW_NATIVE_SHADERS}/threads.wgsl" threads)
    file(READ "${RAW_NATIVE_SHADERS}/raster.wgsl" raster)
    file(READ "${RAW_NATIVE_SHADERS}/pbr.wgsl" pbr)
    file(READ "${RAW_NATIVE_SHADERS}/cube.wgsl" cube)
    file(READ "${RAW_NATIVE_SHADERS}/light.wgsl" light)
    file(READ "${RAW_NATIVE_SHADERS}/shadow.wgsl" shadow)
    file(READ "${RAW_NATIVE_SHADERS}/post.wgsl" post)
    file(WRITE "${out}.tmp"
        "#pragma once\n// Generated by cmake/gpu.cmake from src/renderer/gpu/shaders/*.wgsl. Do not edit.\n"
        "inline constexpr const char* kCommonWgsl = R\"WGSL(${common})WGSL\";\n"
        "inline constexpr const char* kPassesWgsl = R\"WGSL(${passes})WGSL\";\n"
        "inline constexpr const char* kThreadsWgsl = R\"WGSL(${threads})WGSL\";\n"
        "inline constexpr const char* kRasterWgsl = R\"WGSL(${raster})WGSL\";\n"
        "inline constexpr const char* kPbrWgsl = R\"WGSL(${pbr})WGSL\";\n"
        "inline constexpr const char* kCubeWgsl = R\"WGSL(${cube})WGSL\";\n"
        "inline constexpr const char* kLightWgsl = R\"WGSL(${light})WGSL\";\n"
        "inline constexpr const char* kShadowWgsl = R\"WGSL(${shadow})WGSL\";\n"
        "inline constexpr const char* kPostWgsl = R\"WGSL(${post})WGSL\";\n")
    configure_file("${out}.tmp" "${out}" COPYONLY)
endfunction()

if(EMSCRIPTEN AND RAW_NATIVE_GPU)
    set(gen "${CMAKE_CURRENT_BINARY_DIR}/gen")
    raw_native_embed_wgsl("${gen}/raw_gpu_shaders.hpp")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
        "${RAW_NATIVE_SHADERS}/common.wgsl" "${RAW_NATIVE_SHADERS}/passes.wgsl"
        "${RAW_NATIVE_SHADERS}/threads.wgsl" "${RAW_NATIVE_SHADERS}/raster.wgsl" "${RAW_NATIVE_SHADERS}/pbr.wgsl"
        "${RAW_NATIVE_SHADERS}/cube.wgsl" "${RAW_NATIVE_SHADERS}/light.wgsl" "${RAW_NATIVE_SHADERS}/shadow.wgsl" "${RAW_NATIVE_SHADERS}/post.wgsl")
    add_executable(raw_native_gpu_cli app/main.cpp src/rhi/webgpu/webgpu_device.cpp src/rhi/webgpu/webgpu_raster.cpp
        src/renderer/gpu/shaders_wgsl.cpp
        src/rhi/null/hw_null.cpp)
    target_include_directories(raw_native_gpu_cli PRIVATE "${gen}")
    target_compile_definitions(raw_native_gpu_cli PRIVATE RAW_NATIVE_GPU=1)
    target_compile_options(raw_native_gpu_cli PRIVATE --use-port=emdawnwebgpu)
    target_link_libraries(raw_native_gpu_cli PRIVATE raw_native)
    raw_native_wasm_target(raw_native_gpu_cli)
    set_target_properties(raw_native_gpu_cli PROPERTIES OUTPUT_NAME "raw-native-gpu")
    target_link_options(raw_native_gpu_cli PRIVATE --use-port=emdawnwebgpu -sJSPI=1)
endif()

# Find dxc.exe in the Windows SDK: the SDK the build targets first, then the
# newest installed one.
function(raw_native_find_dxc)
    set(hints "")
    if(DEFINED ENV{WindowsSdkVerBinPath})
        list(APPEND hints "$ENV{WindowsSdkVerBinPath}/x64")
    endif()
    set(pf86 "ProgramFiles(x86)")
    set(kits "$ENV{${pf86}}/Windows Kits/10/bin")
    if(CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION)
        list(APPEND hints "${kits}/${CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION}/x64")
    endif()
    file(GLOB sdks LIST_DIRECTORIES true "${kits}/10.*")
    list(SORT sdks COMPARE NATURAL ORDER DESCENDING)
    foreach(s ${sdks})
        list(APPEND hints "${s}/x64")
    endforeach()
    find_program(RAW_NATIVE_DXC dxc HINTS ${hints} NO_DEFAULT_PATH)
    if(NOT RAW_NATIVE_DXC)
        message(FATAL_ERROR "RAW_NATIVE_GPU_D3D12 needs dxc.exe from the Windows SDK (10.0.18362 or newer); set RAW_NATIVE_DXC")
    endif()
endfunction()

# Compile each generated HLSL pass to DXIL and embed the bytes in a header.
# -HV 2021: short-circuit && and ||, as in WGSL. -Gis: strict IEEE float, no
# fast-math rewrites, to stay as close to the CPU reference as the driver allows.
function(raw_native_d3d12_shaders gen out_header)
    set(passes setup raster motion ssao rtao shade
        threads_init threads_rd_seed threads_rd threads_decay threads_advance threads_pyr_first threads_pyr_next threads_finish
        pbr_eval pbr_shade light_cluster light_prefilter shadow_lookup shadow_contact post_gtao post_ssr post_taa)
    set(headers "")
    set(includes "")
    set(table "")
    foreach(p ${passes})
        set(src "${RAW_NATIVE_SHADERS}/hlsl/${p}.hlsl")
        set(h "${gen}/dxil_${p}.h")
        add_custom_command(OUTPUT "${h}"
            COMMAND "${RAW_NATIVE_DXC}" -T cs_6_0 -E main -HV 2021 -Gis -O3 -Qstrip_debug -Qstrip_reflect
                    -Fh "${h}" -Vn "kDxil_${p}" "${src}"
            DEPENDS "${src}" VERBATIM
            COMMENT "dxc ${p}.hlsl")
        list(APPEND headers "${h}")
        string(APPEND includes "#include \"dxil_${p}.h\"\n")
        string(APPEND table "    {\"${p}\", kDxil_${p}, sizeof kDxil_${p}},\n")
    endforeach()
    # Raster passes: one HLSL file, compiled twice, as "<name>.vs" and "<name>.fs".
    set(rasters texture_identity fmt_pattern depth_tris gbuffer shadow_depth)
    foreach(p ${rasters})
        set(src "${RAW_NATIVE_SHADERS}/hlsl/${p}.hlsl")
        foreach(stage vs fs)
            if(stage STREQUAL "vs")
                set(profile vs_6_0)
            else()
                set(profile ps_6_0)
            endif()
            set(h "${gen}/dxil_${p}_${stage}.h")
            add_custom_command(OUTPUT "${h}"
                COMMAND "${RAW_NATIVE_DXC}" -T ${profile} -E ${stage} -HV 2021 -Gis -O3 -Qstrip_debug -Qstrip_reflect
                        -Fh "${h}" -Vn "kDxil_${p}_${stage}" "${src}"
                DEPENDS "${src}" VERBATIM
                COMMENT "dxc ${p}.hlsl (${stage})")
            list(APPEND headers "${h}")
            string(APPEND includes "#include \"dxil_${p}_${stage}.h\"\n")
            string(APPEND table "    {\"${p}.${stage}\", kDxil_${p}_${stage}, sizeof kDxil_${p}_${stage}},\n")
        endforeach()
    endforeach()
    file(WRITE "${out_header}.tmp"
        "#pragma once\n// Generated by cmake/gpu.cmake. Do not edit.\n#include <cstddef>\n${includes}"
        "struct DxilBlob { const char* name; const void* bytes; std::size_t size; };\n"
        "inline constexpr DxilBlob kDxil[] = {\n${table}};\n")
    configure_file("${out_header}.tmp" "${out_header}" COPYONLY)
    set(RAW_NATIVE_DXIL_HEADERS ${headers} PARENT_SCOPE)
endfunction()

# HW workstream (evidence/hw-*-bounds.json): hand-written HLSL in src/rhi/d3d12/hw_shaders/,
# each with its own profile and flags, embedded in raw_hw_dxil.hpp for src/rhi/d3d12/hw_*.cpp.
function(raw_native_hw_shaders gen out_header)
    set(dir "${CMAKE_CURRENT_SOURCE_DIR}/src/rhi/d3d12/hw_shaders")
    # name|source|profile|extra flags (semicolons in flags are spaces here)
    set(entries
        "hw_scan_wave|hw_scan_wave|cs_6_0|"
        "hw_scan_shared|hw_scan_shared|cs_6_0|"
        "hw_half|hw_half|cs_6_2|-enable-16bit-types"
        "hw_half_fallback|hw_half_fallback|cs_6_0|"
        "hw_rayquery_probe|hw_rayquery_probe|cs_6_5|"
        "hw_rayquery|hw_rayquery|cs_6_5|"
        "hw_busy|hw_busy|cs_6_0|-DFLAT=0"
        "hw_busy_flat|hw_busy|cs_6_0|-DFLAT=1")
    set(headers "")
    set(includes "")
    set(table "")
    foreach(e ${entries})
        string(REPLACE "|" ";" f "${e}")
        list(GET f 0 name)
        list(GET f 1 src)
        list(GET f 2 profile)
        list(LENGTH f nf)
        set(extra "")
        if(nf GREATER 3)
            list(GET f 3 extra)
            separate_arguments(extra)
        endif()
        set(h "${gen}/hwdxil_${name}.h")
        add_custom_command(OUTPUT "${h}"
            COMMAND "${RAW_NATIVE_DXC}" -T ${profile} -E main -HV 2021 -Gis -O3 -Qstrip_debug -Qstrip_reflect ${extra}
                    -Fh "${h}" -Vn "kHwDxil_${name}" "${dir}/${src}.hlsl"
            DEPENDS "${dir}/${src}.hlsl" VERBATIM
            COMMENT "dxc ${src}.hlsl (${name})")
        list(APPEND headers "${h}")
        string(APPEND includes "#include \"hwdxil_${name}.h\"
")
        string(APPEND table "    {\"${name}\", kHwDxil_${name}, sizeof kHwDxil_${name}},
")
    endforeach()
    file(WRITE "${out_header}.tmp"
        "#pragma once
// Generated by cmake/gpu.cmake. Do not edit.
#include <cstddef>
${includes}"
        "struct HwDxilBlob { const char* name; const void* bytes; std::size_t size; };
"
        "inline constexpr HwDxilBlob kHwDxil[] = {
${table}};
")
    configure_file("${out_header}.tmp" "${out_header}" COPYONLY)
    set(RAW_NATIVE_HW_DXIL_HEADERS ${headers} PARENT_SCOPE)
endfunction()

if(RAW_NATIVE_GPU_D3D12)
    if(NOT WIN32 OR EMSCRIPTEN)
        message(FATAL_ERROR "RAW_NATIVE_GPU_D3D12 is a Windows-only option")
    endif()
    raw_native_find_dxc()
    set(gen "${CMAKE_CURRENT_BINARY_DIR}/gen")
    raw_native_d3d12_shaders("${gen}" "${gen}/raw_d3d12_dxil.hpp")
    raw_native_hw_shaders("${gen}" "${gen}/raw_hw_dxil.hpp")
    add_library(raw_native_d3d12 STATIC src/rhi/d3d12/d3d12_device.cpp src/rhi/d3d12/d3d12_commands.cpp
        src/rhi/d3d12/d3d12_raster.cpp src/rhi/d3d12/d3d12_texture.cpp
        src/renderer/gpu/shaders_dxil.cpp
        src/rhi/d3d12/hw_queue.cpp src/rhi/d3d12/hw_probe.cpp src/rhi/d3d12/hw_checks.cpp src/rhi/d3d12/hw_rayquery.cpp
        ${RAW_NATIVE_DXIL_HEADERS} ${RAW_NATIVE_HW_DXIL_HEADERS})
    target_include_directories(raw_native_d3d12 PRIVATE "${gen}")
    target_link_libraries(raw_native_d3d12 PUBLIC raw_native d3d12 dxgi)
    target_link_libraries(raw_native_cli PRIVATE raw_native_d3d12)
    if(RAW_NATIVE_BUILD_TESTS)
        # Renders on the D3D12 adapter and checks the GPU certificate. Without a
        # hardware adapter (CI runners have none) it exits 77, which CTest reports
        # as skipped with the reason in the output, never as passed.
        add_executable(gpu_d3d12_runtime tests/gpu/d3d12_runtime.cpp)
        target_link_libraries(gpu_d3d12_runtime PRIVATE raw_native_d3d12)
        target_include_directories(gpu_d3d12_runtime PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/tests")
        add_test(NAME gpu_d3d12_runtime COMMAND gpu_d3d12_runtime)
        set_tests_properties(gpu_d3d12_runtime PROPERTIES SKIP_RETURN_CODE 77)
        # The sampled-texture identity check (ROADMAP M2 criterion 3), skipped the same way.
        add_executable(gpu_texture_identity tests/gpu/texture_identity.cpp)
        target_link_libraries(gpu_texture_identity PRIVATE raw_native_d3d12)
        add_test(NAME gpu_texture_identity COMMAND gpu_texture_identity)
        set_tests_properties(gpu_texture_identity PROPERTIES SKIP_RETURN_CODE 77)
        # The material model's GPU parity (M3, evidence/m3-materials-bounds.json), skipped the same way.
        add_executable(gpu_pbr_parity tests/gpu/pbr_parity.cpp)
        target_link_libraries(gpu_pbr_parity PRIVATE raw_native_d3d12)
        add_test(NAME gpu_pbr_parity COMMAND gpu_pbr_parity)
        set_tests_properties(gpu_pbr_parity PROPERTIES SKIP_RETURN_CODE 77)
        # RHI version 3: formats, depth and the hardware G-buffer (M3, evidence/m3-rhi3-bounds.json).
        add_executable(gpu_raster_identity tests/gpu/raster_identity.cpp)
        target_link_libraries(gpu_raster_identity PRIVATE raw_native_d3d12)
        add_test(NAME gpu_raster_identity COMMAND gpu_raster_identity)
        set_tests_properties(gpu_raster_identity PROPERTIES SKIP_RETURN_CODE 77)
        # The shadow maps' GPU parity (M3, evidence/m3-shadows-bounds.json), skipped the same way.
        add_executable(gpu_shadow_parity tests/gpu/shadow_parity.cpp)
        target_link_libraries(gpu_shadow_parity PRIVATE raw_native_d3d12)
        add_test(NAME gpu_shadow_parity COMMAND gpu_shadow_parity)
        set_tests_properties(gpu_shadow_parity PROPERTIES SKIP_RETURN_CODE 77)
        # GTAO, SSR and TAA GPU parity (M3, evidence/m3-post-bounds.json), skipped the same way.
        add_executable(gpu_post_parity tests/gpu/post_parity.cpp)
        target_link_libraries(gpu_post_parity PRIVATE raw_native_d3d12)
        add_test(NAME gpu_post_parity COMMAND gpu_post_parity)
        set_tests_properties(gpu_post_parity PROPERTIES SKIP_RETURN_CODE 77)
        # The lighting's GPU parity (M3, evidence/m3-lighting-bounds.json), skipped the same way.
        add_executable(gpu_lighting_parity tests/gpu/lighting_parity.cpp)
        target_link_libraries(gpu_lighting_parity PRIVATE raw_native_d3d12)
        add_test(NAME gpu_lighting_parity COMMAND gpu_lighting_parity)
        set_tests_properties(gpu_lighting_parity PROPERTIES SKIP_RETURN_CODE 77)
        # HW H1.0: the hardware probe, its functional checks and timestamps (evidence/hw-h1-0-bounds.json).
        add_executable(gpu_hw_probe tests/gpu/hw_probe.cpp)
        target_link_libraries(gpu_hw_probe PRIVATE raw_native_d3d12)
        add_test(NAME gpu_hw_probe COMMAND gpu_hw_probe)
        set_tests_properties(gpu_hw_probe PROPERTIES SKIP_RETURN_CODE 77)
        # HW H1.1: inline ray query against the CPU BVH (evidence/hw-h1-1-bounds.json).
        add_executable(gpu_hw_rayquery tests/gpu/hw_rayquery.cpp)
        target_link_libraries(gpu_hw_rayquery PRIVATE raw_native_d3d12)
        add_test(NAME gpu_hw_rayquery COMMAND gpu_hw_rayquery)
        set_tests_properties(gpu_hw_rayquery PROPERTIES SKIP_RETURN_CODE 77)
    endif()
    message(STATUS "raw-native: D3D12 backend on, shaders compiled by ${RAW_NATIVE_DXC}")
else()
    target_sources(raw_native_cli PRIVATE ${RAW_NATIVE_NULL_BACKEND})
endif()

# HW workstream, Vulkan half (evidence/hw-h1-0-vk-bounds.json). Optional and off by default:
# RAW_NATIVE_VULKAN=ON builds raw_native_vk_probe against the Vulkan SDK's loader and headers,
# with the GLSL kernels in src/rhi/vulkan/shaders/ compiled to SPIR-V by its glslangValidator.
option(RAW_NATIVE_VULKAN "Build the Vulkan hardware probe tool (needs the Vulkan SDK)" OFF)
if(RAW_NATIVE_VULKAN AND NOT EMSCRIPTEN)
    find_package(Vulkan REQUIRED COMPONENTS glslangValidator)
    set(vkgen "${CMAKE_CURRENT_BINARY_DIR}/gen-vk")
    set(vkdir "${CMAKE_CURRENT_SOURCE_DIR}/src/rhi/vulkan/shaders")
    # name|source|defines
    set(vk_entries "vk_scan_subgroup|vk_scan_subgroup|" "vk_scan_shared|vk_scan_shared|" "vk_half|vk_half|"
        "vk_half_fallback|vk_half_fallback|" "vk_busy|vk_busy|-DFLAT=0" "vk_busy_flat|vk_busy|-DFLAT=1"
        "vk_rayquery_probe|vk_rayquery_probe|" "vk_coopmat_probe|vk_coopmat_probe|"
        "vk_gemm_coop|vk_gemm_coop|" "vk_gemm_coop_skipk|vk_gemm_coop|-DSKIP_K=1" "vk_gemm_coop_bcol|vk_gemm_coop|-DB_COLMAJOR=1"
        "vk_gemm_tiled|vk_gemm_tiled|" "vk_gemm_tiled_skipk|vk_gemm_tiled|-DSKIP_K=1")
    set(vk_headers "")
    set(vk_includes "")
    set(vk_table "")
    foreach(e ${vk_entries})
        string(REPLACE "|" ";" f "${e}")
        list(GET f 0 name)
        list(GET f 1 src)
        list(LENGTH f nf)
        set(defs "")
        if(nf GREATER 2)
            list(GET f 2 defs)
        endif()
        set(h "${vkgen}/spv_${name}.h")
        add_custom_command(OUTPUT "${h}"
            COMMAND Vulkan::glslangValidator -V --target-env vulkan1.3 ${defs} --vn "kSpv_${name}" -o "${h}" "${vkdir}/${src}.comp"
            DEPENDS "${vkdir}/${src}.comp" VERBATIM
            COMMENT "glslang ${src}.comp (${name})")
        list(APPEND vk_headers "${h}")
        string(APPEND vk_includes "#include \"spv_${name}.h\"\n")
        string(APPEND vk_table "    {\"${name}\", kSpv_${name}, sizeof kSpv_${name}},\n")
    endforeach()
    file(WRITE "${vkgen}/raw_vk_spirv.hpp.tmp"
        "#pragma once\n// Generated by cmake/gpu.cmake. Do not edit.\n#include <cstddef>\n#include <cstdint>\n${vk_includes}"
        "struct VkSpirvBlob { const char* name; const uint32_t* words; std::size_t bytes; };\n"
        "inline constexpr VkSpirvBlob kVkSpirv[] = {\n${vk_table}};\n")
    configure_file("${vkgen}/raw_vk_spirv.hpp.tmp" "${vkgen}/raw_vk_spirv.hpp" COPYONLY)
    add_executable(raw_native_vk_probe app/vk_probe.cpp src/rhi/vulkan/vk_context.cpp src/rhi/vulkan/vk_probe.cpp
        src/rhi/vulkan/vk_compute.cpp src/rhi/vulkan/vk_checks.cpp src/rhi/vulkan/vk_gemm.cpp ${vk_headers})
    target_include_directories(raw_native_vk_probe PRIVATE "${vkgen}" "${CMAKE_CURRENT_SOURCE_DIR}")
    target_compile_features(raw_native_vk_probe PRIVATE cxx_std_23)
    target_link_libraries(raw_native_vk_probe PRIVATE Vulkan::Vulkan)
    message(STATUS "raw-native: Vulkan probe tool on (${Vulkan_LIBRARY})")
endif()
