# The WebGPU backend (phase 1): a second WebAssembly CLI, raw-native-gpu.mjs,
# built with Emscripten's WebGPU port and JSPI. Only the Emscripten build with
# RAW_NATIVE_GPU=ON compiles any GPU code; the native build and the CPU wasm
# build link src/gpu/gpu_none.cpp and stay dependency-free.
option(RAW_NATIVE_GPU "Build the WebGPU CLI (Emscripten only)" OFF)

# Embed the WGSL sources as C++ raw strings.
function(raw_native_embed_wgsl out)
    file(READ "${CMAKE_CURRENT_SOURCE_DIR}/src/gpu/common.wgsl" common)
    file(READ "${CMAKE_CURRENT_SOURCE_DIR}/src/gpu/passes.wgsl" passes)
    file(WRITE "${out}.tmp"
        "#pragma once\n// Generated by cmake/gpu.cmake from src/gpu/*.wgsl. Do not edit.\n"
        "inline constexpr const char* kCommonWgsl = R\"WGSL(${common})WGSL\";\n"
        "inline constexpr const char* kPassesWgsl = R\"WGSL(${passes})WGSL\";\n")
    configure_file("${out}.tmp" "${out}" COPYONLY)
endfunction()

if(EMSCRIPTEN AND RAW_NATIVE_GPU)
    set(gen "${CMAKE_CURRENT_BINARY_DIR}/gen")
    raw_native_embed_wgsl("${gen}/raw_gpu_shaders.hpp")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
        "${CMAKE_CURRENT_SOURCE_DIR}/src/gpu/common.wgsl" "${CMAKE_CURRENT_SOURCE_DIR}/src/gpu/passes.wgsl")
    add_executable(raw_native_gpu_cli app/main.cpp src/gpu/webgpu.cpp)
    target_include_directories(raw_native_gpu_cli PRIVATE "${gen}")
    target_compile_definitions(raw_native_gpu_cli PRIVATE RAW_NATIVE_GPU=1)
    target_compile_options(raw_native_gpu_cli PRIVATE --use-port=emdawnwebgpu)
    target_link_libraries(raw_native_gpu_cli PRIVATE raw_native)
    raw_native_wasm_target(raw_native_gpu_cli)
    set_target_properties(raw_native_gpu_cli PROPERTIES OUTPUT_NAME "raw-native-gpu")
    target_link_options(raw_native_gpu_cli PRIVATE --use-port=emdawnwebgpu -sJSPI=1)
endif()
