# The RHI backends. A build links one, with the shader library in the format
# that backend takes. The default build links the null backend
# (src/rhi/null/), which answers --gpu with exit code 4 and an unverifiable
# certificate, and the library stays dependency-free.
#
#   RAW_NATIVE_GPU=ON        (Emscripten only) a second WebAssembly CLI,
#                            raw-native-gpu.mjs, built with Emscripten's WebGPU
#                            port and JSPI: src/rhi/webgpu/ and the WGSL passes.
#   RAW_NATIVE_GPU_D3D12=ON  (Windows only) raw_native_cli renders --gpu on
#                            D3D12: src/rhi/d3d12/. The passes are
#                            src/renderer/gpu/shaders/hlsl/*.hlsl, generated from
#                            the WGSL by scripts/wgsl_to_hlsl.py, compiled to DXIL
#                            by the Windows SDK's dxc.exe at build time. Links
#                            d3d12.lib and dxgi.lib from the Windows SDK; nothing else.
option(RAW_NATIVE_GPU "Build the WebGPU CLI (Emscripten only)" OFF)
option(RAW_NATIVE_GPU_D3D12 "Build the D3D12 backend into raw_native_cli (Windows only)" OFF)

set(RAW_NATIVE_SHADERS "${CMAKE_CURRENT_SOURCE_DIR}/src/renderer/gpu/shaders")
# Embed the WGSL sources as C++ raw strings.
function(raw_native_embed_wgsl out)
    file(READ "${RAW_NATIVE_SHADERS}/common.wgsl" common)
    file(READ "${RAW_NATIVE_SHADERS}/passes.wgsl" passes)
    file(READ "${RAW_NATIVE_SHADERS}/threads.wgsl" threads)
    file(READ "${RAW_NATIVE_SHADERS}/raster.wgsl" raster)
    file(READ "${RAW_NATIVE_SHADERS}/pbr.wgsl" pbr)
    file(READ "${RAW_NATIVE_SHADERS}/cube.wgsl" cube)
    file(READ "${RAW_NATIVE_SHADERS}/light.wgsl" light)
    file(WRITE "${out}.tmp"
        "#pragma once\n// Generated by cmake/gpu.cmake from src/renderer/gpu/shaders/*.wgsl. Do not edit.\n"
        "inline constexpr const char* kCommonWgsl = R\"WGSL(${common})WGSL\";\n"
        "inline constexpr const char* kPassesWgsl = R\"WGSL(${passes})WGSL\";\n"
        "inline constexpr const char* kThreadsWgsl = R\"WGSL(${threads})WGSL\";\n"
        "inline constexpr const char* kRasterWgsl = R\"WGSL(${raster})WGSL\";\n"
        "inline constexpr const char* kPbrWgsl = R\"WGSL(${pbr})WGSL\";\n"
        "inline constexpr const char* kCubeWgsl = R\"WGSL(${cube})WGSL\";\n"
        "inline constexpr const char* kLightWgsl = R\"WGSL(${light})WGSL\";\n")
    configure_file("${out}.tmp" "${out}" COPYONLY)
endfunction()

if(EMSCRIPTEN AND RAW_NATIVE_GPU)
    set(gen "${CMAKE_CURRENT_BINARY_DIR}/gen")
    raw_native_embed_wgsl("${gen}/raw_gpu_shaders.hpp")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
        "${RAW_NATIVE_SHADERS}/common.wgsl" "${RAW_NATIVE_SHADERS}/passes.wgsl"
        "${RAW_NATIVE_SHADERS}/threads.wgsl" "${RAW_NATIVE_SHADERS}/raster.wgsl" "${RAW_NATIVE_SHADERS}/pbr.wgsl"
        "${RAW_NATIVE_SHADERS}/cube.wgsl" "${RAW_NATIVE_SHADERS}/light.wgsl")
    add_executable(raw_native_gpu_cli app/main.cpp src/rhi/webgpu/webgpu_device.cpp src/rhi/webgpu/webgpu_raster.cpp
        src/renderer/gpu/shaders_wgsl.cpp)
    target_include_directories(raw_native_gpu_cli PRIVATE "${gen}")
    target_compile_definitions(raw_native_gpu_cli PRIVATE RAW_NATIVE_GPU=1)
    target_compile_options(raw_native_gpu_cli PRIVATE --use-port=emdawnwebgpu)
    target_link_libraries(raw_native_gpu_cli PRIVATE raw_native)
    raw_native_wasm_target(raw_native_gpu_cli)
    set_target_properties(raw_native_gpu_cli PROPERTIES OUTPUT_NAME "raw-native-gpu")
    target_link_options(raw_native_gpu_cli PRIVATE --use-port=emdawnwebgpu -sJSPI=1)
endif()

# Find dxc.exe in the Windows SDK: the SDK the build targets first, then the
# newest installed one.
function(raw_native_find_dxc)
    set(hints "")
    if(DEFINED ENV{WindowsSdkVerBinPath})
        list(APPEND hints "$ENV{WindowsSdkVerBinPath}/x64")
    endif()
    set(pf86 "ProgramFiles(x86)")
    set(kits "$ENV{${pf86}}/Windows Kits/10/bin")
    if(CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION)
        list(APPEND hints "${kits}/${CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION}/x64")
    endif()
    file(GLOB sdks LIST_DIRECTORIES true "${kits}/10.*")
    list(SORT sdks COMPARE NATURAL ORDER DESCENDING)
    foreach(s ${sdks})
        list(APPEND hints "${s}/x64")
    endforeach()
    find_program(RAW_NATIVE_DXC dxc HINTS ${hints} NO_DEFAULT_PATH)
    if(NOT RAW_NATIVE_DXC)
        message(FATAL_ERROR "RAW_NATIVE_GPU_D3D12 needs dxc.exe from the Windows SDK (10.0.18362 or newer); set RAW_NATIVE_DXC")
    endif()
endfunction()

# Compile each generated HLSL pass to DXIL and embed the bytes in a header.
# -HV 2021: short-circuit && and ||, as in WGSL. -Gis: strict IEEE float, no
# fast-math rewrites, to stay as close to the CPU reference as the driver allows.
function(raw_native_d3d12_shaders gen out_header)
    set(passes setup raster motion ssao rtao shade
        threads_init threads_rd_seed threads_rd threads_decay threads_advance threads_pyr_first threads_pyr_next threads_finish
        pbr_eval pbr_shade light_cluster light_prefilter)
    set(headers "")
    set(includes "")
    set(table "")
    foreach(p ${passes})
        set(src "${RAW_NATIVE_SHADERS}/hlsl/${p}.hlsl")
        set(h "${gen}/dxil_${p}.h")
        add_custom_command(OUTPUT "${h}"
            COMMAND "${RAW_NATIVE_DXC}" -T cs_6_0 -E main -HV 2021 -Gis -O3 -Qstrip_debug -Qstrip_reflect
                    -Fh "${h}" -Vn "kDxil_${p}" "${src}"
            DEPENDS "${src}" VERBATIM
            COMMENT "dxc ${p}.hlsl")
        list(APPEND headers "${h}")
        string(APPEND includes "#include \"dxil_${p}.h\"\n")
        string(APPEND table "    {\"${p}\", kDxil_${p}, sizeof kDxil_${p}},\n")
    endforeach()
    # Raster passes: one HLSL file, compiled twice, as "<name>.vs" and "<name>.fs".
    set(rasters texture_identity)
    foreach(p ${rasters})
        set(src "${RAW_NATIVE_SHADERS}/hlsl/${p}.hlsl")
        foreach(stage vs fs)
            if(stage STREQUAL "vs")
                set(profile vs_6_0)
            else()
                set(profile ps_6_0)
            endif()
            set(h "${gen}/dxil_${p}_${stage}.h")
            add_custom_command(OUTPUT "${h}"
                COMMAND "${RAW_NATIVE_DXC}" -T ${profile} -E ${stage} -HV 2021 -Gis -O3 -Qstrip_debug -Qstrip_reflect
                        -Fh "${h}" -Vn "kDxil_${p}_${stage}" "${src}"
                DEPENDS "${src}" VERBATIM
                COMMENT "dxc ${p}.hlsl (${stage})")
            list(APPEND headers "${h}")
            string(APPEND includes "#include \"dxil_${p}_${stage}.h\"\n")
            string(APPEND table "    {\"${p}.${stage}\", kDxil_${p}_${stage}, sizeof kDxil_${p}_${stage}},\n")
        endforeach()
    endforeach()
    file(WRITE "${out_header}.tmp"
        "#pragma once\n// Generated by cmake/gpu.cmake. Do not edit.\n#include <cstddef>\n${includes}"
        "struct DxilBlob { const char* name; const void* bytes; std::size_t size; };\n"
        "inline constexpr DxilBlob kDxil[] = {\n${table}};\n")
    configure_file("${out_header}.tmp" "${out_header}" COPYONLY)
    set(RAW_NATIVE_DXIL_HEADERS ${headers} PARENT_SCOPE)
endfunction()

if(RAW_NATIVE_GPU_D3D12)
    if(NOT WIN32 OR EMSCRIPTEN)
        message(FATAL_ERROR "RAW_NATIVE_GPU_D3D12 is a Windows-only option")
    endif()
    raw_native_find_dxc()
    set(gen "${CMAKE_CURRENT_BINARY_DIR}/gen")
    raw_native_d3d12_shaders("${gen}" "${gen}/raw_d3d12_dxil.hpp")
    add_library(raw_native_d3d12 STATIC src/rhi/d3d12/d3d12_device.cpp src/rhi/d3d12/d3d12_commands.cpp
        src/rhi/d3d12/d3d12_raster.cpp
        src/renderer/gpu/shaders_dxil.cpp
        ${RAW_NATIVE_DXIL_HEADERS})
    target_include_directories(raw_native_d3d12 PRIVATE "${gen}")
    target_link_libraries(raw_native_d3d12 PUBLIC raw_native d3d12 dxgi)
    target_link_libraries(raw_native_cli PRIVATE raw_native_d3d12)
    if(RAW_NATIVE_BUILD_TESTS)
        # Renders on the D3D12 adapter and checks the GPU certificate. Without a
        # hardware adapter (CI runners have none) it exits 77, which CTest reports
        # as skipped with the reason in the output, never as passed.
        add_executable(gpu_d3d12_runtime tests/gpu/d3d12_runtime.cpp)
        target_link_libraries(gpu_d3d12_runtime PRIVATE raw_native_d3d12)
        target_include_directories(gpu_d3d12_runtime PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/tests")
        add_test(NAME gpu_d3d12_runtime COMMAND gpu_d3d12_runtime)
        set_tests_properties(gpu_d3d12_runtime PROPERTIES SKIP_RETURN_CODE 77)
        # The sampled-texture identity check (ROADMAP M2 criterion 3), skipped the same way.
        add_executable(gpu_texture_identity tests/gpu/texture_identity.cpp)
        target_link_libraries(gpu_texture_identity PRIVATE raw_native_d3d12)
        add_test(NAME gpu_texture_identity COMMAND gpu_texture_identity)
        set_tests_properties(gpu_texture_identity PROPERTIES SKIP_RETURN_CODE 77)
        # The material model's GPU parity (M3, evidence/m3-materials-bounds.json), skipped the same way.
        add_executable(gpu_pbr_parity tests/gpu/pbr_parity.cpp)
        target_link_libraries(gpu_pbr_parity PRIVATE raw_native_d3d12)
        add_test(NAME gpu_pbr_parity COMMAND gpu_pbr_parity)
        set_tests_properties(gpu_pbr_parity PROPERTIES SKIP_RETURN_CODE 77)
        # The lighting's GPU parity (M3, evidence/m3-lighting-bounds.json), skipped the same way.
        add_executable(gpu_lighting_parity tests/gpu/lighting_parity.cpp)
        target_link_libraries(gpu_lighting_parity PRIVATE raw_native_d3d12)
        add_test(NAME gpu_lighting_parity COMMAND gpu_lighting_parity)
        set_tests_properties(gpu_lighting_parity PROPERTIES SKIP_RETURN_CODE 77)
    endif()
    message(STATUS "raw-native: D3D12 backend on, shaders compiled by ${RAW_NATIVE_DXC}")
else()
    target_sources(raw_native_cli PRIVATE ${RAW_NATIVE_NULL_BACKEND})
endif()
