// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/raster.wgsl. Do not edit.
// WGSL sha256 fb145cf9e6d3c744aa240359221fcc3c0121b9ff5262c83e13210986bbe4e171
// Raster pass: depth_tris (entry points vs, fs)

struct DtOut {
    float4 clip : SV_Position;
    nointerpolation float3 rgb : TEXCOORD0;
};
// RHI version 3 depth test: triangles pulled from a storage buffer (12 floats each: three
// clip-space xyz corners, then RGB), drawn into one target with a Depth32Float target.
// (No uniform: WebGPU's derived layout drops a binding the shader never reads.)
RWStructuredBuffer<float> T : register(u0);

DtOut vs(uint i : SV_VertexID) {
    const uint b = (i / 3u) * 12u;
    const uint k = i % 3u;
    DtOut o = (DtOut)0;
    o.clip = float4(T[b + 3u * k], T[b + 3u * k + 1u], T[b + 3u * k + 2u], 1.0f);
    o.rgb = float3(T[b + 9u], T[b + 10u], T[b + 11u]);
    return o;
}

float4 fs(DtOut v) : SV_Target0 {
    return float4(v.rgb, 1.0f);
}
