// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/raster.wgsl. Do not edit.
// WGSL sha256 fb145cf9e6d3c744aa240359221fcc3c0121b9ff5262c83e13210986bbe4e171
// Raster pass: fmt_pattern (entry points vs, fs)

// RHI version 3 format round trip (evidence/m3-rhi3-bounds.json): every channel of every
// pixel gets n * scale with n = (7x + 13y + 5c) & 255, values each format holds exactly
// (scale 1/255 for RGBA8Unorm, 1/256 for the float formats).
struct Pat {
    float scale;
    float pad0;
    float pad1;
    float pad2;
};
ConstantBuffer<Pat> U : register(b0);

float4 vs(uint i : SV_VertexID) : SV_Position {
    const float x = float((i << 1u) & 2u);
    const float y = float(i & 2u);
    return float4(x * 2.0f - 1.0f, 1.0f - y * 2.0f, 0.0f, 1.0f);
}

float4 fs(float4 q : SV_Position) : SV_Target0 {
    const uint x = uint(q.x);
    const uint y = uint(q.y);
    const float r = float((7u * x + 13u * y) & 255u);
    const float g = float((7u * x + 13u * y + 5u) & 255u);
    const float b = float((7u * x + 13u * y + 10u) & 255u);
    const float a = float((7u * x + 13u * y + 15u) & 255u);
    return float4(r, g, b, a) * U.scale;
}
