// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/raster.wgsl. Do not edit.
// WGSL sha256 899319093bd45fd62feb145418c5590edf5674c435a67884e0fdd43960ec439b
// Raster pass: gbuffer (entry points vs, fs)

// The hardware G-buffer (ROADMAP M3): triangles pulled from storage in the layout of
// src/renderer/gpu/frame_pack.cpp (24 floats: world positions, normals, albedo), transformed
// by the view-projection rows, depth-tested in hardware. Clip z is moved from [-w, w] (the
// engine's projection) to [0, w] (D3D12 and WebGPU). Targets: world position, normal,
// albedo with coverage, and (triangle index + 1, view distance).
struct Cam {
    float4 vp[4];
};
struct GbOut {
    float4 clip : SV_Position;
    float3 wpos : TEXCOORD0;
    float3 nrm : TEXCOORD1;
    nointerpolation float3 alb : TEXCOORD2;
    nointerpolation uint tri : TEXCOORD3;
    float dist : TEXCOORD4;
};
struct GbTargets {
    float4 pos : SV_Target0;
    float4 nrm : SV_Target1;
    float4 alb : SV_Target2;
    float4 id : SV_Target3;
};
ConstantBuffer<Cam> U : register(b0);
RWStructuredBuffer<float> T : register(u0);
float mrow(float4 r, float4 v) { return r.x * v.x + r.y * v.y + r.z * v.z + r.w * v.w; }

GbOut vs(uint i : SV_VertexID) {
    const uint t = i / 3u;
    const uint k = i % 3u;
    const uint b = t * 24u;
    const float4 wp = float4(T[b + 3u * k], T[b + 3u * k + 1u], T[b + 3u * k + 2u], 1.0f);
    const float4 c = float4(mrow(U.vp[0], wp), mrow(U.vp[1], wp), mrow(U.vp[2], wp), mrow(U.vp[3], wp));
    GbOut o = (GbOut)0;
    o.clip = float4(c.x, c.y, 0.5f * (c.z + c.w), c.w);
    o.wpos = wp.xyz;
    o.nrm = float3(T[b + 9u + 3u * k], T[b + 10u + 3u * k], T[b + 11u + 3u * k]);
    o.alb = float3(T[b + 18u], T[b + 19u], T[b + 20u]);
    o.tri = t + 1u;
    o.dist = c.w;
    return o;
}

GbTargets fs(GbOut v) {
    GbTargets o = (GbTargets)0;
    const float l = sqrt(v.nrm.x * v.nrm.x + v.nrm.y * v.nrm.y + v.nrm.z * v.nrm.z);
    o.pos = float4(v.wpos, 1.0f);
    o.nrm = float4(v.nrm / l, 0.0f);
    o.alb = float4(v.alb, 1.0f);
    o.id = float4(float(v.tri), v.dist, 0.0f, 1.0f);
    return o;
}
