// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/cube.wgsl and light.wgsl. Do not edit.
// WGSL sha256 79182cc9fc4f0de1d951908f66f66344413be0c6a92a6f527495dfeb7d95a038
// Pass: light_prefilter

// raw-native GPU lighting passes: clustered light assignment and the GGX prefilter of an
// environment cube, the float32 forms of src/renderer/lighting_clusters.cpp and
// raw/renderer/lighting_cube.hpp. cube.wgsl sits in front of this module's shared code.

struct LightParams {
    uint nlights; uint nclusters; uint size; uint level;
    uint samples; uint levels; uint pad0; uint pad1;
    float4 grid;
};
// A light: 16 floats. 0 type (0 directional, 1 point, 2 spot), 1..3 position, 4..6 direction,
// 7..9 colour, 10 intensity, 11 range (0: unlimited), 12 spot scale, 13 spot offset.
static const uint LIGHT = 16u;
static const uint MAX_PER_CLUSTER = 256u;

// One invocation per texel of level P.level: the GGX prefilter of
// raw::lighting::cube::prefilterTexel, reading level 0 bilinearly. The half-vector
// samples come from the host (S: cos theta, sin theta cos phi, sin theta sin phi for each
// sample of this level), computed in double: in-shader sin and cos carry about 1e-6 error
// on SwiftShader, and the sun's 1e5 nits turned that into a 1.2e-3 relative error.
ConstantBuffer<LightParams> P : register(b0);
RWStructuredBuffer<float> E : register(u1);
RWStructuredBuffer<float> S : register(u2);
// raw-native GPU shared fragment: cube-map addressing, the orthonormal basis, the
// radical inverse and the cluster index, line for line as raw/renderer/lighting_cube.hpp
// and src/renderer/lighting_clusters.cpp. Pure functions only (no bindings), so every
// module may put it in front of its shared code: pbr.wgsl and light.wgsl do.

// Levels stop at 8 texels a face (raw::lighting::cube::kMinLevelSize).
uint cube_level_size(uint size, uint level) { return max(min(size, 8u), size >> level); }
// Floats before level `level` of a cube stored as RGB texels, faces in order.
uint cube_level_offset(uint size, uint level) {
    uint off = 0u;
    for (uint k = 0u; k < level; k++) {
        const uint n = cube_level_size(size, k);
        off = off + 18u * n * n;
    }
    return off;
}
// Face index in x, and u, v in [0, 1] in y and z (+x -x +y -y +z -z; D3D / OpenGL rules).
float3 cube_face(float3 d) {
    const float ax = abs(d.x);
    const float ay = abs(d.y);
    const float az = abs(d.z);
    float f = 0.0f; float ma = 0.0f; float sc = 0.0f; float tc = 0.0f;
    if (ax >= ay && ax >= az) {
        f = ((d.x >= 0.0f) ? (0.0f) : (1.0f)); ma = ax; sc = ((d.x >= 0.0f) ? (-d.z) : (d.z)); tc = -d.y;
    } else if (ay >= az) {
        f = ((d.y >= 0.0f) ? (2.0f) : (3.0f)); ma = ay; sc = d.x; tc = ((d.y >= 0.0f) ? (d.z) : (-d.z));
    } else {
        f = ((d.z >= 0.0f) ? (4.0f) : (5.0f)); ma = az; sc = ((d.z >= 0.0f) ? (d.x) : (-d.x)); tc = -d.y;
    }
    return float3(f, 0.5f * (sc / ma + 1.0f), 0.5f * (tc / ma + 1.0f));
}
float3 cube_dir(uint f, float u, float v) {
    const float sc = 2.0f * u - 1.0f;
    const float tc = 2.0f * v - 1.0f;
    float3 d = float3(-sc, -tc, -1.0f);
    if (f == 0u) { d = float3(1.0f, -tc, -sc); }
    if (f == 1u) { d = float3(-1.0f, -tc, sc); }
    if (f == 2u) { d = float3(sc, 1.0f, tc); }
    if (f == 3u) { d = float3(sc, -1.0f, -tc); }
    if (f == 4u) { d = float3(sc, -tc, 1.0f); }
    return d / sqrt(d.x * d.x + d.y * d.y + d.z * d.z);
}
// The texel a bilinear tap lands on, seamless across faces (raw::lighting::cube::tap).
// Returns (face, y, x) for a tap at row y, column x of face f, possibly past its edge.
uint3 cube_tap(uint n, uint f, int y, int x) {
    const int ni = int(n);
    if (x >= 0 && x < ni && y >= 0 && y < ni) { return uint3(f, uint(y), uint(x)); }
    const float3 d = cube_dir(f, (float(x) + 0.5f) / float(n), (float(y) + 0.5f) / float(n));
    const float3 fu = cube_face(d);
    const int xx = clamp(int(fu.y * float(n)), 0, ni - 1);
    const int yy = clamp(int(fu.z * float(n)), 0, ni - 1);
    return uint3(uint(fu.x), uint(yy), uint(xx));
}
// Duff et al. 2017.
void onb(float3 n, inout float3 t, inout float3 b) {
    const float s = ((n.z >= 0.0f) ? (1.0f) : (-1.0f));
    const float a = -1.0f / (s + n.z);
    const float c = n.x * n.y * a;
    t = float3(1.0f + s * n.x * n.x * a, s * c, -s * n.x);
    b = float3(c, s + n.y * n.y * a, -n.y);
}
float radical_inverse(uint bits_in) {
    uint b = (bits_in << 16u) | (bits_in >> 16u);
    b = ((b & 0x55555555u) << 1u) | ((b & 0xAAAAAAAAu) >> 1u);
    b = ((b & 0x33333333u) << 2u) | ((b & 0xCCCCCCCCu) >> 2u);
    b = ((b & 0x0F0F0F0Fu) << 4u) | ((b & 0xF0F0F0F0u) >> 4u);
    b = ((b & 0x00FF00FFu) << 8u) | ((b & 0xFF00FF00u) >> 8u);
    return float(b) * 2.3283064365386963e-10f;
}
// The cluster of a view-space point, or -1 outside the frustum. grid: tan(fovy / 2), aspect,
// near, far; 16 x 9 x 24 clusters (raw::lighting::ClusterGrid).
int cluster_of(float3 p, float4 grid) {
    const float d = -p.z;
    if (!(d >= grid.z && d < grid.w)) { return -1; }
    const float nx = p.x / (d * grid.x * grid.y);
    const float ny = p.y / (d * grid.x);
    if (!(abs(nx) <= 1.0f && abs(ny) <= 1.0f)) { return -1; }
    const int ix = min(int((nx + 1.0f) * 0.5f * 16.0f), 15);
    const int iy = min(int((ny + 1.0f) * 0.5f * 9.0f), 8);
    const int iz = min(int(log(d / grid.z) / log(grid.w / grid.z) * 24.0f), 23);
    return (iz * 9 + iy) * 16 + ix;
}

float3 texel0(uint f, int y, int x) {
    const uint3 t = cube_tap(P.size, f, y, x);
    const uint i = ((t.x * P.size + t.y) * P.size + t.z) * 3u;
    return float3(E[i], E[i + 1u], E[i + 2u]);
}
float3 sample0(float3 d) {
    const float3 fu = cube_face(d);
    const uint f = uint(fu.x);
    const float fx = fu.y * float(P.size) - 0.5f;
    const float fy = fu.z * float(P.size) - 0.5f;
    const int x0 = int(floor(fx));
    const int y0 = int(floor(fy));
    const float ax = fx - float(x0);
    const float ay = fy - float(y0);
    const float3 a = texel0(f, y0, x0);
    const float3 b = texel0(f, y0, x0 + 1);
    const float3 c = texel0(f, y0 + 1, x0);
    const float3 e = texel0(f, y0 + 1, x0 + 1);
    return (a * (1.0f - ax) + b * ax) * (1.0f - ay) + (c * (1.0f - ax) + e * ax) * ay;
}

[numthreads(64, 1, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    const uint n = cube_level_size(P.size, P.level);
    if (gid.x >= 6u * n * n) { return; }
    const uint f = gid.x / (n * n);
    const uint y = (gid.x / n) % n;
    const uint x = gid.x % n;
    const float3 nd = cube_dir(f, (float(x) + 0.5f) / float(n), (float(y) + 0.5f) / float(n));
    float3 t = ((float3)(0.0f));
    float3 bb = ((float3)(0.0f));
    onb(nd, t, bb);
    float3 sum = ((float3)(0.0f));
    float w = 0.0f;
    for (uint k = 0u; k < P.samples; k++) {
        const uint s3 = k * 3u;
        const float3 h = t * S[s3 + 1u] + bb * S[s3 + 2u] + nd * S[s3];
        const float nh = dot(nd, h);
        const float3 l = 2.0f * nh * h - nd;
        const float nl = dot(nd, l);
        if (nl <= 0.0f) { continue; }
        sum = sum + sample0(l) * nl;
        w = w + nl;
    }
    const uint o = cube_level_offset(P.size, P.level) + gid.x * 3u;
    const float3 v = sum / w;
    E[o] = v.x; E[o + 1u] = v.y; E[o + 2u] = v.z;
}
