// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/pbr.wgsl. Do not edit.
// WGSL sha256 e516a8e4272606746a99217b408cec9a8f4d5dc17b5a9b57a0ab486ab7a7dcf8
// Pass: pbr_shade

// raw-native GPU material model: the float32 form of raw/renderer/pbr.hpp.
// The same model term for term; the CPU reference is float64, and the parity check
// (raw/renderer/pbr_parity.hpp) compares the two within evidence/m3-materials-bounds.json.
// Shared code sits above the first pass marker; each pass follows it.
// Translator subset (scripts/wgsl_to_hlsl.py): every let and var typed, one statement per
// line, no struct values (materials are read from the case buffer by index).

struct PbrParams {
    uint count; uint flags; uint nlights; uint env_size;
    uint env_levels; uint sh_off; uint pad0; uint pad1;
    float4 grid;
    float4 misc;
};

static const float PI = 3.14159265358979f;
static const float MIN_ROUGH = 0.045f;
static const float MIN_SHEEN = 0.07f;
static const float THETA_PAD = 0.05f;
static const float ROUGH_MAX = 1.05f;
static const uint N_THETA = 128u;
static const uint N_ROUGH = 128u;
static const uint N_SH = 64u;
static const uint AN_MU = 32u;
static const uint AN_PHI = 8u;
static const uint AN_ROUGH = 24u;
static const uint AN_K = 12u;
static const uint HARMONICS = 8u;
// Offsets of each table in the one table buffer (floats); raw/renderer/pbr_parity.hpp packs them.
static const uint OFF_A = 0u;
static const uint OFF_B = 16384u;
static const uint OFF_AAVG = 32768u;
static const uint OFF_BAVG = 32896u;
static const uint OFF_SH = 33024u;
static const uint OFF_A4 = 37120u;
static const uint OFF_B4 = 110848u;
static const uint OFF_AAVG2 = 184576u;
static const uint OFF_BAVG2 = 184864u;
static const uint OFF_DOM = 185152u;
static const uint N_DOM = 64u;
// A case: 44 floats. Material fields in pbr.hpp order, then wo and wi; the anisotropy
// rotation arrives as its cosine (27) and sine (35), computed on the host.
static const uint CASE = 44u;
static const uint FLAG_NO_MS = 1u;

// A sample: the 36 material floats, then position, normal, tangent and the unit view vector.
static const uint SAMPLE = 48u;
static const uint NCLUSTERS = 3456u;
static const uint MAX_PER_CLUSTER = 256u;

// Shades surface samples (raw::lighting::shadePunctual over the sample's cluster list, plus
// raw::lighting::shadeIbl), multiplied by the exposure. One invocation per sample.
ConstantBuffer<PbrParams> P : register(b0);
RWStructuredBuffer<float> C : register(u1);
RWStructuredBuffer<float> T : register(u2);
RWStructuredBuffer<float> L : register(u3);
RWStructuredBuffer<uint> K : register(u4);
RWStructuredBuffer<float> E : register(u5);
RWStructuredBuffer<float> R : register(u6);
// raw-native GPU shared fragment: cube-map addressing, the orthonormal basis, the
// radical inverse and the cluster index, line for line as raw/renderer/lighting_cube.hpp
// and src/renderer/lighting_clusters.cpp. Pure functions only (no bindings), so every
// module may put it in front of its shared code: pbr.wgsl and light.wgsl do.

// Levels stop at 8 texels a face (raw::lighting::cube::kMinLevelSize).
uint cube_level_size(uint size, uint level) { return max(min(size, 8u), size >> level); }
// Floats before level `level` of a cube stored as RGB texels, faces in order.
uint cube_level_offset(uint size, uint level) {
    uint off = 0u;
    for (uint k = 0u; k < level; k++) {
        const uint n = cube_level_size(size, k);
        off = off + 18u * n * n;
    }
    return off;
}
// Face index in x, and u, v in [0, 1] in y and z (+x -x +y -y +z -z; D3D / OpenGL rules).
float3 cube_face(float3 d) {
    const float ax = abs(d.x);
    const float ay = abs(d.y);
    const float az = abs(d.z);
    float f = 0.0f; float ma = 0.0f; float sc = 0.0f; float tc = 0.0f;
    if (ax >= ay && ax >= az) {
        f = ((d.x >= 0.0f) ? (0.0f) : (1.0f)); ma = ax; sc = ((d.x >= 0.0f) ? (-d.z) : (d.z)); tc = -d.y;
    } else if (ay >= az) {
        f = ((d.y >= 0.0f) ? (2.0f) : (3.0f)); ma = ay; sc = d.x; tc = ((d.y >= 0.0f) ? (d.z) : (-d.z));
    } else {
        f = ((d.z >= 0.0f) ? (4.0f) : (5.0f)); ma = az; sc = ((d.z >= 0.0f) ? (d.x) : (-d.x)); tc = -d.y;
    }
    return float3(f, 0.5f * (sc / ma + 1.0f), 0.5f * (tc / ma + 1.0f));
}
float3 cube_dir(uint f, float u, float v) {
    const float sc = 2.0f * u - 1.0f;
    const float tc = 2.0f * v - 1.0f;
    float3 d = float3(-sc, -tc, -1.0f);
    if (f == 0u) { d = float3(1.0f, -tc, -sc); }
    if (f == 1u) { d = float3(-1.0f, -tc, sc); }
    if (f == 2u) { d = float3(sc, 1.0f, tc); }
    if (f == 3u) { d = float3(sc, -1.0f, -tc); }
    if (f == 4u) { d = float3(sc, -tc, 1.0f); }
    return d / sqrt(d.x * d.x + d.y * d.y + d.z * d.z);
}
// The texel a bilinear tap lands on, seamless across faces (raw::lighting::cube::tap).
// Returns (face, y, x) for a tap at row y, column x of face f, possibly past its edge.
uint3 cube_tap(uint n, uint f, int y, int x) {
    const int ni = int(n);
    if (x >= 0 && x < ni && y >= 0 && y < ni) { return uint3(f, uint(y), uint(x)); }
    const float3 d = cube_dir(f, (float(x) + 0.5f) / float(n), (float(y) + 0.5f) / float(n));
    const float3 fu = cube_face(d);
    const int xx = clamp(int(fu.y * float(n)), 0, ni - 1);
    const int yy = clamp(int(fu.z * float(n)), 0, ni - 1);
    return uint3(uint(fu.x), uint(yy), uint(xx));
}
// Duff et al. 2017.
void onb(float3 n, inout float3 t, inout float3 b) {
    const float s = ((n.z >= 0.0f) ? (1.0f) : (-1.0f));
    const float a = -1.0f / (s + n.z);
    const float c = n.x * n.y * a;
    t = float3(1.0f + s * n.x * n.x * a, s * c, -s * n.x);
    b = float3(c, s + n.y * n.y * a, -n.y);
}
float radical_inverse(uint bits_in) {
    uint b = (bits_in << 16u) | (bits_in >> 16u);
    b = ((b & 0x55555555u) << 1u) | ((b & 0xAAAAAAAAu) >> 1u);
    b = ((b & 0x33333333u) << 2u) | ((b & 0xCCCCCCCCu) >> 2u);
    b = ((b & 0x0F0F0F0Fu) << 4u) | ((b & 0xF0F0F0F0u) >> 4u);
    b = ((b & 0x00FF00FFu) << 8u) | ((b & 0xFF00FF00u) >> 8u);
    return float(b) * 2.3283064365386963e-10f;
}
// The cluster of a view-space point, or -1 outside the frustum. grid: tan(fovy / 2), aspect,
// near, far; 16 x 9 x 24 clusters (raw::lighting::ClusterGrid).
int cluster_of(float3 p, float4 grid) {
    const float d = -p.z;
    if (!(d >= grid.z && d < grid.w)) { return -1; }
    const float nx = p.x / (d * grid.x * grid.y);
    const float ny = p.y / (d * grid.x);
    if (!(abs(nx) <= 1.0f && abs(ny) <= 1.0f)) { return -1; }
    const int ix = min(int((nx + 1.0f) * 0.5f * 16.0f), 15);
    const int iy = min(int((ny + 1.0f) * 0.5f * 9.0f), 8);
    const int iz = min(int(log(d / grid.z) / log(grid.w / grid.z) * 24.0f), 23);
    return (iz * 9 + iy) * 16 + ix;
}

float pdot(float3 a, float3 b) { return a.x * b.x + a.y * b.y + a.z * b.z; }
float3 pnorm(float3 a) { const float l = sqrt(pdot(a, a)); return a / l; }
float pmax3(float3 c) { return max(c.x, max(c.y, c.z)); }

float alpha_of(float r) { const float c = clamp(r, MIN_ROUGH, 1.0f); return c * c; }
float ggx_d(float3 h, float ax, float ay) {
    if (h.z <= 0.0f) { return 0.0f; }
    const float u = h.x / ax;
    const float v = h.y / ay;
    const float s = u * u + v * v + h.z * h.z;
    return 1.0f / (PI * ax * ay * s * s);
}
float smith_v(float3 o, float3 i, float ax, float ay) {
    const float qo = sqrt(ax * ax * o.x * o.x + ay * ay * o.y * o.y + o.z * o.z);
    const float qi = sqrt(ax * ax * i.x * i.x + ay * ay * i.y * i.y + i.z * i.z);
    return 0.5f / (abs(i.z) * qo + abs(o.z) * qi);
}
float schlick(float f0, float f90, float c) {
    const float m = 1.0f - clamp(c, 0.0f, 1.0f);
    const float m5 = m * m * m * m * m;
    return f0 + (f90 - f0) * m5;
}
float charlie_d(float3 h, float rs) {
    const float r = clamp(rs, MIN_SHEEN, 1.0f);
    const float inv = 1.0f / (r * r);
    const float s2 = h.x * h.x + h.y * h.y;
    return (2.0f + inv) * pow(s2, 0.5f * inv) / (2.0f * PI);
}
float sheen_l(float x, float a) {
    const float t = (1.0f - a) * (1.0f - a);
    const float ca = 21.5473f + (25.3245f - 21.5473f) * t;
    const float cb = 3.82987f + (3.32435f - 3.82987f) * t;
    const float cc = 0.19823f + (0.16801f - 0.19823f) * t;
    const float cd = -1.97760f + (-1.27393f + 1.97760f) * t;
    const float ce = -4.32054f + (-4.85967f + 4.32054f) * t;
    return ca / (1.0f + cb * pow(x, cc)) + cd * x + ce;
}
float sheen_lambda(float c, float a) {
    if (abs(c) < 0.5f) { return exp(sheen_l(c, a)); }
    return exp(2.0f * sheen_l(0.5f, a) - sheen_l(1.0f - c, a));
}
float charlie_v(float mo, float mi, float rs) {
    const float r = clamp(rs, MIN_SHEEN, 1.0f);
    const float a = r * r;
    return 1.0f / ((1.0f + sheen_lambda(mo, a) + sheen_lambda(mi, a)) * (4.0f * mo * mi));
}
float walter(float3 win, float eta_in, float3 wout, float eta_out, float ax, float ay, float f0) {
    if (win.z * wout.z >= 0.0f) { return 0.0f; }
    float3 h = -(eta_in * win + eta_out * wout);
    const float l = sqrt(pdot(h, h));
    if (l <= 0.0f) { return 0.0f; }
    h = h / l;
    if (h.z < 0.0f) { h = -h; }
    const float ih = pdot(win, h);
    const float oh = pdot(wout, h);
    if (ih * win.z <= 0.0f || oh * wout.z <= 0.0f) { return 0.0f; }
    const float clow = ((eta_in <= eta_out) ? (abs(ih)) : (abs(oh)));
    const float fr = schlick(f0, 1.0f, clow);
    const float den = eta_in * ih + eta_out * oh;
    const float g2 = 4.0f * abs(win.z) * abs(wout.z) * smith_v(win, wout, ax, ay);
    return abs(ih) * abs(oh) / (abs(win.z) * abs(wout.z)) * eta_out * eta_out * (1.0f - fr) * g2 * ggx_d(h, ax, ay) / (den * den);
}

// Tables: bilinear on (theta, roughness) rows, as raw::pbr::Tables reads them.
void locate(float x, uint n, inout uint i0, inout float f) {
    const float c = clamp(x, 0.0f, float(n) - 1.0f);
    i0 = min(uint(c), n - 2u);
    f = c - float(i0);
}
float theta_x(float mu, uint n) {
    const float th = acos(clamp(mu, 0.0f, 1.0f));
    return (th + THETA_PAD) / (PI / 2.0f + THETA_PAD) * float(n - 1u);
}
float read2(uint off, uint nt, uint nr, float mu, float r) {
    uint x0 = 0u; float fx = 0.0f; uint y0 = 0u; float fy = 0.0f;
    locate(theta_x(mu, nt), nt, x0, fx);
    locate(r / ROUGH_MAX * float(nr - 1u), nr, y0, fy);
    const uint a = off + y0 * nt + x0;
    return (T[a] * (1.0f - fx) + T[a + 1u] * fx) * (1.0f - fy) + (T[a + nt] * (1.0f - fx) + T[a + nt + 1u] * fx) * fy;
}
float read1(uint off, uint n, float r) {
    uint y0 = 0u; float f = 0.0f;
    locate(r / ROUGH_MAX * float(n - 1u), n, y0, f);
    return T[off + y0] * (1.0f - f) + T[off + y0 + 1u] * f;
}
float read4(uint off, float mu, float phi_in, float r, float k) {
    float ph = abs(phi_in);
    ph = ph - floor(ph / PI) * PI;
    if (ph > 0.5f * PI) { ph = PI - ph; }
    uint i0 = 0u; float f0 = 0.0f; uint i1 = 0u; float f1 = 0.0f;
    uint i2 = 0u; float f2 = 0.0f; uint i3 = 0u; float f3 = 0.0f;
    locate(theta_x(mu, AN_MU), AN_MU, i0, f0);
    locate(ph / (0.5f * PI) * float(AN_PHI - 1u), AN_PHI, i1, f1);
    locate(r / ROUGH_MAX * float(AN_ROUGH - 1u), AN_ROUGH, i2, f2);
    locate(k * float(AN_K - 1u), AN_K, i3, f3);
    float s = 0.0f;
    for (uint c = 0u; c < 16u; c++) {
        const uint b0 = c & 1u; const uint b1 = (c >> 1u) & 1u; const uint b2 = (c >> 2u) & 1u; const uint b3 = (c >> 3u) & 1u;
        const float w = ((b0 == 1u) ? (f0) : (1.0f - f0)) * ((b1 == 1u) ? (f1) : (1.0f - f1)) * ((b2 == 1u) ? (f2) : (1.0f - f2)) * ((b3 == 1u) ? (f3) : (1.0f - f3));
        s = s + w * T[off + (((i3 + b3) * AN_ROUGH + i2 + b2) * AN_PHI + i1 + b1) * AN_MU + i0 + b0];
    }
    return s;
}
float read2rk(uint off, float r, float k) {
    uint ir = 0u; float fr = 0.0f; uint ik = 0u; float fk = 0.0f;
    locate(r / ROUGH_MAX * float(AN_ROUGH - 1u), AN_ROUGH, ir, fr);
    locate(k * float(AN_K - 1u), AN_K, ik, fk);
    const uint a = off + ik * AN_ROUGH + ir;
    return (T[a] * (1.0f - fr) + T[a + 1u] * fr) * (1.0f - fk) + (T[a + AN_ROUGH] * (1.0f - fr) + T[a + AN_ROUGH + 1u] * fr) * fk;
}
// The sheen table's view axis is sqrt(mu) (raw::pbr::Tables::Sh).
float read_sh(float mu, float r) {
    uint x0 = 0u; float fx = 0.0f; uint y0 = 0u; float fy = 0.0f;
    locate(sqrt(clamp(mu, 0.0f, 1.0f)) * float(N_SH - 1u), N_SH, x0, fx);
    locate(r / ROUGH_MAX * float(N_SH - 1u), N_SH, y0, fy);
    const uint a = OFF_SH + y0 * N_SH + x0;
    return (T[a] * (1.0f - fx) + T[a + 1u] * fx) * (1.0f - fy) + (T[a + N_SH] * (1.0f - fx) + T[a + N_SH + 1u] * fx) * fy;
}
float tab_e(float mu, float r) { return read2(OFF_A, N_THETA, N_ROUGH, mu, r) + read2(OFF_B, N_THETA, N_ROUGH, mu, r); }
float tab_eavg(float r) { return read1(OFF_AAVG, N_ROUGH, r) + read1(OFF_BAVG, N_ROUGH, r); }

// Iridescence (Belcour and Barla 2017), eight harmonics as raw::pbr::iridescentFresnel.
float3 xyz_to_709(float x, float y, float z) {
    return float3(3.2404542f * x - 1.5371385f * y - 0.4985314f * z, -0.9692660f * x + 1.8760108f * y + 0.0415560f * z, 0.0556434f * x - 0.2040259f * y + 1.0572252f * z);
}
float3 sensitivity(float opd, float3 shift) {
    const float ph = 2.0f * PI * opd * 1.0e-9f;
    const float3 val = float3(5.4856e-13f, 4.4201e-13f, 5.2481e-13f);
    const float3 pos = float3(1.6810e+06f, 1.7953e+06f, 2.2084e+06f);
    const float3 vr = float3(4.3278e+09f, 9.3046e+09f, 6.6121e+09f);
    float3 xyz = val * sqrt(2.0f * PI * vr) * cos(pos * ph + shift) * exp(-ph * ph * vr);
    xyz.x = xyz.x + 9.7470e-14f * sqrt(2.0f * PI * 4.5282e+09f) * cos(2.2399e+06f * ph + shift.x) * exp(-4.5282e+09f * ph * ph);
    xyz = xyz / 1.0685e-7f;
    return xyz_to_709(xyz.x, xyz.y, xyz.z);
}
float ior_to_f0(float t, float i) { const float q = (t - i) / (t + i); return q * q; }
float3 irid_f(float film, float d, float3 f0, float cos1) {
    const float s2 = (1.0f / film) * (1.0f / film) * (1.0f - cos1 * cos1);
    const float c2sq = 1.0f - s2;
    if (c2sq < 0.0f) { return ((float3)(1.0f)); }
    const float cos2 = sqrt(c2sq);
    const float r12 = schlick(ior_to_f0(film, 1.0f), 1.0f, cos1);
    const float t121 = 1.0f - r12;
    const float phi21 = PI - ((film < 1.0f) ? (PI) : (0.0f));
    const float3 sf = sqrt(f0 + ((float3)(0.0001f)));
    const float3 base = (((float3)(1.0f)) + sf) / (((float3)(1.0f)) - sf);
    const float3 r23 = float3(schlick(ior_to_f0(base.x, film), 1.0f, cos2), schlick(ior_to_f0(base.y, film), 1.0f, cos2), schlick(ior_to_f0(base.z, film), 1.0f, cos2));
    const float3 phi = ((float3)(phi21)) + float3(((base.x < film) ? (PI) : (0.0f)), ((base.y < film) ? (PI) : (0.0f)), ((base.z < film) ? (PI) : (0.0f)));
    const float opd = 2.0f * film * d * cos2;
    const float3 r123sq = clamp(r12 * r23, ((float3)(1e-5f)), ((float3)(0.9999f)));
    const float3 r123 = sqrt(r123sq);
    const float3 rs = t121 * t121 * r23 / (((float3)(1.0f)) - r123sq);
    float3 acc = ((float3)(r12)) + rs;
    float3 cm = rs - ((float3)(t121));
    for (uint m = 1u; m <= HARMONICS; m++) {
        cm = cm * r123;
        acc = acc + cm * 2.0f * sensitivity(float(m) * opd, float(m) * phi);
    }
    return max(acc, ((float3)(0.0f)));
}
// Material evaluation from a case or sample buffer C (every pass of this module binds the
// uniform P as 0, the material buffer C as 1 and the tables T as 2).
float3 cv3(uint b, uint k) { return float3(C[b + k], C[b + k + 1u], C[b + k + 2u]); }
float kms(float favg, float ebar) { return favg * favg * ebar / (1.0f - favg * (1.0f - ebar)); }
float3 kms3(float3 f0, float f90, float ebar) {
    const float3 fa = f0 + (((float3)(f90)) - f0) / 21.0f;
    return float3(kms(fa.x, ebar), kms(fa.y, ebar), kms(fa.z, ebar));
}
// Split albedo (A, B) for a direction in the anisotropy frame.
float2 split_ab(float3 w, float r, float k) {
    const float mu = abs(w.z);
    if (k > 0.0f) {
        const float ph = atan2(abs(w.y), abs(w.x));
        return float2(read4(OFF_A4, mu, ph, r, k), read4(OFF_B4, mu, ph, r, k));
    }
    return float2(read2(OFF_A, N_THETA, N_ROUGH, mu, r), read2(OFF_B, N_THETA, N_ROUGH, mu, r));
}
float3 es_at(float2 ab, float3 f0d, float f90, float3 kd) {
    return f0d * ab.x + ((float3)(f90 * ab.y)) + (1.0f - ab.x - ab.y) * kd;
}
float3 fresnel3(float3 f0, float f90, float voh, uint b) {
    const float3 f = float3(schlick(f0.x, f90, voh), schlick(f0.y, f90, voh), schlick(f0.z, f90, voh));
    const float iri = C[b + 28u];
    if (iri <= 0.0f) { return f; }
    return f * (1.0f - iri) + irid_f(C[b + 29u], C[b + 30u], f0, voh) * iri;
}
// Sheen and clearcoat over the base result fb (raw::pbr::evalTerms).
float3 layers(uint b, float3 wo, float3 wi, float3 fb, float ms_on) {
    float3 f = fb;
    const float3 shc = cv3(b, 15u);
    const float sh = pmax3(shc);
    const float rs = C[b + 18u];
    if (sh > 0.0f) {
        const float a_sheen = min(1.0f - sh * read_sh(wo.z, rs), 1.0f - sh * read_sh(abs(wi.z), rs));
        f = f * a_sheen;
        if (wi.z > 0.0f) { f = f + shc * (charlie_d(pnorm(wo + wi), rs) * charlie_v(wo.z, wi.z, rs)); }
    }
    const float c = clamp(C[b + 10u], 0.0f, 1.0f);
    if (c <= 0.0f) { return f; }
    const float3 nc = pnorm(cv3(b, 12u));
    const float mo = pdot(nc, wo);
    const float mi = pdot(nc, wi);
    const float rc = clamp(C[b + 11u], MIN_ROUGH, 1.0f);
    const float a = rc * rc;
    const float co = max(mo, 0.0f);
    const float ci = ((wi.z > 0.0f) ? (max(mi, 0.0f)) : (abs(mi)));
    const float kc = kms(0.04f + 0.96f / 21.0f, tab_eavg(rc));
    const float eco = 0.04f * read2(OFF_A, N_THETA, N_ROUGH, co, rc) + read2(OFF_B, N_THETA, N_ROUGH, co, rc) + (1.0f - tab_e(co, rc)) * kc;
    const float eci = 0.04f * read2(OFF_A, N_THETA, N_ROUGH, ci, rc) + read2(OFF_B, N_THETA, N_ROUGH, ci, rc) + (1.0f - tab_e(ci, rc)) * kc;
    f = f * ((1.0f - c * eco) * (1.0f - c * eci));
    if (mo > 0.0f && mi > 0.0f && wi.z > 0.0f) {
        const float3 h = pnorm(wo + wi);
        const float hn = pdot(h, nc);
        const float cx = h.y * nc.z - h.z * nc.y;
        const float cy = h.z * nc.x - h.x * nc.z;
        const float cz = h.x * nc.y - h.y * nc.x;
        const float s2 = cx * cx + cy * cy + cz * cz;
        const float den = s2 + a * a * hn * hn;
        const float d = ((hn > 0.0f) ? (a * a / (PI * den * den)) : (0.0f));
        const float v = 0.5f / (mi * sqrt(mo * mo * (1.0f - a * a) + a * a) + mo * sqrt(mi * mi * (1.0f - a * a) + a * a));
        const float ms = (1.0f - tab_e(mo, rc)) * (1.0f - tab_e(mi, rc)) / (PI * (1.0f - tab_eavg(rc)));
        f = f + ((float3)(c * d * v * schlick(0.04f, 1.0f, pdot(wo, h)) + c * kc * ms * ms_on));
    }
    return f;
}
// Coat over sheen over base, as raw::pbr::evalTerms; returns the total f.
float3 eval_case(uint b, float3 wo, float3 wi) {
    if (wo.z <= 0.0f || wi.z == 0.0f) { return ((float3)(0.0f)); }
    const float ms_on = (((P.flags & FLAG_NO_MS) != 0u) ? (0.0f) : (1.0f));
    const float3 base = cv3(b, 0u);
    const float mt = clamp(C[b + 3u], 0.0f, 1.0f);
    const float rr = clamp(C[b + 4u], MIN_ROUGH, 1.0f);
    const float ak = clamp(C[b + 26u], 0.0f, 1.0f);
    const float a = alpha_of(C[b + 4u]);
    const float ax = a + (1.0f - a) * ak * ak;
    const float ay = a;
    const float abar = ((ak > 0.0f) ? (read2rk(OFF_AAVG2, rr, ak)) : (read1(OFF_AAVG, N_ROUGH, rr)));
    const float bbar = ((ak > 0.0f) ? (read2rk(OFF_BAVG2, rr, ak)) : (read1(OFF_BAVG, N_ROUGH, rr)));
    const float ebar = abar + bbar;
    const float ior = C[b + 5u];
    const float q = (ior - 1.0f) / (ior + 1.0f);
    const float f90 = C[b + 6u];
    const float3 f0d = min(q * q * cv3(b, 7u), ((float3)(1.0f))) * f90;
    const float3 km = kms3(base, 1.0f, ebar);
    const float3 kd = kms3(f0d, f90, ebar);
    const float3 es_avg = f0d * abar + ((float3)(f90 * bbar)) + (1.0f - ebar) * kd;
    const float cr = C[b + 27u];
    const float sr = C[b + 35u];
    const float3 o = float3(cr * wo.x + sr * wo.y, -sr * wo.x + cr * wo.y, wo.z);
    const float3 i = float3(cr * wi.x + sr * wi.y, -sr * wi.x + cr * wi.y, wi.z);
    const float2 abo = split_ab(o, rr, ak);
    const float2 abi = split_ab(i, rr, ak);
    const float3 es_o = es_at(abo, f0d, f90, kd);
    const float3 es_i = es_at(abi, f0d, f90, kd);
    const float tr = clamp(C[b + 19u], 0.0f, 1.0f);
    float3 f = ((float3)(0.0f));
    if (i.z > 0.0f) {
        const float3 h = pnorm(o + i);
        const float dv = ggx_d(h, ax, ay) * smith_v(o, i, ax, ay);
        const float voh = pdot(o, h);
        const float ms = (1.0f - abo.x - abo.y) * (1.0f - abi.x - abi.y) / (PI * (1.0f - ebar)) * ms_on;
        f = (fresnel3(base, 1.0f, voh, b) * mt + fresnel3(f0d, f90, voh, b) * (1.0f - mt)) * dv;
        f = f + (km * mt + kd * (1.0f - mt)) * ms;
        float3 w = (((float3)(1.0f)) - es_o) * (((float3)(1.0f)) - es_i) / (((float3)(1.0f)) - es_avg);
        const float iri = C[b + 28u];
        if (iri > 0.0f) {
            const float mo = pmax3(irid_f(C[b + 29u], C[b + 30u], f0d, o.z));
            const float mi = pmax3(irid_f(C[b + 29u], C[b + 30u], f0d, i.z));
            w = w * (1.0f - iri) + ((float3)((1.0f - mo) * (1.0f - mi) * iri));
        }
        f = f + base * w * ((1.0f - mt) * (1.0f - tr) / PI);
    } else if (tr > 0.0f && mt < 1.0f) {
        if (C[b + 20u] == 0.0f) {
            const float3 im = float3(i.x, i.y, -i.z);
            const float3 h = pnorm(o + im);
            const float2 abm = split_ab(im, rr, ak);
            const float g = ggx_d(h, ax, ay) * smith_v(o, im, ax, ay) + (1.0f - abo.x - abo.y) * (1.0f - abm.x - abm.y) / (PI * (1.0f - ebar)) * ms_on;
            f = base * min(((float3)(1.0f)) - es_o, ((float3)(1.0f)) - es_i) * (g * tr * (1.0f - mt));
        } else {
            float3 att = ((float3)(1.0f));
            if (C[b + 22u] > 0.0f && C[b + 21u] > 0.0f) {
                att = exp(log(max(cv3(b, 23u), ((float3)(1e-30f)))) / C[b + 22u] * C[b + 21u]);
            }
            const float3 wt = float3(walter(i, ior, o, 1.0f, ax, ay, f0d.x), walter(i, ior, o, 1.0f, ax, ay, f0d.y), walter(i, ior, o, 1.0f, ax, ay, f0d.z));
            f = base * att * wt * (tr * (1.0f - mt));
        }
    }
    return layers(b, wo, wi, f, ms_on);
}

float3 env_texel(uint level, uint f, int y, int x) {
    const uint n = cube_level_size(P.env_size, level);
    const uint3 t = cube_tap(n, f, y, x);
    const uint i = cube_level_offset(P.env_size, level) + ((t.x * n + t.y) * n + t.z) * 3u;
    return float3(E[i], E[i + 1u], E[i + 2u]);
}
float3 env_sample(uint level, float3 d) {
    const uint n = cube_level_size(P.env_size, level);
    const float3 fu = cube_face(d);
    const uint f = uint(fu.x);
    const float fx = fu.y * float(n) - 0.5f;
    const float fy = fu.z * float(n) - 0.5f;
    const int x0 = int(floor(fx));
    const int y0 = int(floor(fy));
    const float ax = fx - float(x0);
    const float ay = fy - float(y0);
    const float3 a = env_texel(level, f, y0, x0);
    const float3 b = env_texel(level, f, y0, x0 + 1);
    const float3 c = env_texel(level, f, y0 + 1, x0);
    const float3 e = env_texel(level, f, y0 + 1, x0 + 1);
    return (a * (1.0f - ax) + b * ax) * (1.0f - ay) + (c * (1.0f - ax) + e * ax) * ay;
}
float3 env_rough(float r, float3 d) {
    const float l = clamp(r, 0.0f, 1.0f) * float(P.env_levels - 1u);
    const uint l0 = min(uint(l), P.env_levels - 1u);
    const uint l1 = min(l0 + 1u, P.env_levels - 1u);
    const float f = l - float(l0);
    return env_sample(l0, d) * (1.0f - f) + env_sample(l1, d) * f;
}
// Irradiance / pi from the order-2 harmonics stored at E[P.sh_off] (9 RGB, raw::lighting::shIrradiance).
float3 sh_irr(float3 n) {
    float y[9] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
    y[0] = 0.282094791773878f;
    y[1] = 0.488602511902920f * n.y; y[2] = 0.488602511902920f * n.z; y[3] = 0.488602511902920f * n.x;
    y[4] = 1.092548430592079f * n.x * n.y; y[5] = 1.092548430592079f * n.y * n.z;
    y[6] = 0.315391565252520f * (3.0f * n.z * n.z - 1.0f);
    y[7] = 1.092548430592079f * n.x * n.z; y[8] = 0.546274215296040f * (n.x * n.x - n.y * n.y);
    float3 e = ((float3)(0.0f));
    for (uint k = 0u; k < 9u; k++) {
        const float band = ((k == 0u) ? (1.0f) : (((k < 4u) ? (2.0f / 3.0f) : (0.25f))));
        const uint o = P.sh_off + k * 3u;
        e = e + float3(E[o], E[o + 1u], E[o + 2u]) * (band * y[k]);
    }
    return max(e, ((float3)(0.0f)));
}
// raw::lighting::illuminance: lux per channel arriving at p, and the unit direction to the light.
float3 illum(uint i, float3 p, inout float3 to_light) {
    const uint b = i * 16u;
    const float3 col = float3(L[b + 7u], L[b + 8u], L[b + 9u]);
    if (L[b] == 0.0f) {
        to_light = -float3(L[b + 4u], L[b + 5u], L[b + 6u]);
        return col * L[b + 10u];
    }
    const float3 d = float3(L[b + 1u], L[b + 2u], L[b + 3u]) - p;
    const float d2 = dot(d, d);
    const float dist = sqrt(d2);
    if (dist <= 0.0f) { to_light = float3(0.0f, 0.0f, 1.0f); return ((float3)(0.0f)); }
    to_light = d / dist;
    float att = 1.0f / d2;
    const float range = L[b + 11u];
    if (range > 0.0f) {
        const float q = dist / range;
        const float w = clamp(1.0f - q * q * q * q, 0.0f, 1.0f);
        att = att * w * w;
    }
    if (L[b] == 2.0f) {
        const float cd = -dot(float3(L[b + 4u], L[b + 5u], L[b + 6u]), to_light);
        const float a = clamp(cd * L[b + 12u] + L[b + 13u], 0.0f, 1.0f);
        att = att * a * a;
    }
    return col * (L[b + 10u] * att);
}
// The lobe centroid's direction (raw::lighting dominant(), Tables::Dom).
float3 dominant(float3 n, float3 v, float rough) {
    const float nv = clamp(dot(n, v), 0.0f, 1.0f);
    const float e = read2(OFF_DOM, N_DOM, N_DOM, nv, rough);
    const float3 r = 2.0f * nv * n - v;
    const float3 p = r - dot(r, n) * n;
    const float pl = sqrt(dot(p, p));
    if (pl < 1e-12f) { return n; }
    return n * cos(e) + p * (sin(e) / pl);
}
float3 spec_w(uint b, float3 f0, float f90, float a, float bb, float mu) {
    const float3 w = f0 * a + ((float3)(f90 * bb));
    const float iri = C[b + 28u];
    if (iri <= 0.0f) { return w; }
    return w * (1.0f - iri) + irid_f(C[b + 29u], C[b + 30u], f0, mu) * ((a + bb) * iri);
}
// raw::pbr::iblResponse and raw::lighting::shadeIbl for one sample.
float3 ibl(uint b, float3 wo, float3 n, float3 t, float3 v) {
    const float3 base = cv3(b, 0u);
    const float mt = clamp(C[b + 3u], 0.0f, 1.0f);
    const float tr = clamp(C[b + 19u], 0.0f, 1.0f);
    const float rr = clamp(C[b + 4u], MIN_ROUGH, 1.0f);
    const float ak = clamp(C[b + 26u], 0.0f, 1.0f);
    const float abar = ((ak > 0.0f) ? (read2rk(OFF_AAVG2, rr, ak)) : (read1(OFF_AAVG, N_ROUGH, rr)));
    const float bbar = ((ak > 0.0f) ? (read2rk(OFF_BAVG2, rr, ak)) : (read1(OFF_BAVG, N_ROUGH, rr)));
    const float ebar = abar + bbar;
    const float q = (C[b + 5u] - 1.0f) / (C[b + 5u] + 1.0f);
    const float f90 = C[b + 6u];
    const float3 f0d = min(q * q * cv3(b, 7u), ((float3)(1.0f))) * f90;
    const float3 km = kms3(base, 1.0f, ebar);
    const float3 kd = kms3(f0d, f90, ebar);
    const float cr = C[b + 27u];
    const float sr = C[b + 35u];
    const float3 o = float3(cr * wo.x + sr * wo.y, -sr * wo.x + cr * wo.y, wo.z);
    const float2 ab = split_ab(o, rr, ak);
    const float e = ab.x + ab.y;
    const float3 es_o = es_at(ab, f0d, f90, kd);
    float3 spec = spec_w(b, base, 1.0f, ab.x, ab.y, o.z) * mt + spec_w(b, f0d, f90, ab.x, ab.y, o.z) * (1.0f - mt);
    float3 under = ((float3)(1.0f)) - es_o;
    const float iri = C[b + 28u];
    if (iri > 0.0f) { under = under * (1.0f - iri) + ((float3)((1.0f - pmax3(irid_f(C[b + 29u], C[b + 30u], f0d, o.z))) * iri)); }
    float3 irr = (km * mt + kd * (1.0f - mt)) * (1.0f - e) + base * under * ((1.0f - mt) * (1.0f - tr));
    float3 trans = ((float3)(0.0f));
    if (tr > 0.0f && mt < 1.0f) {
        float3 att = ((float3)(1.0f));
        if (C[b + 20u] != 0.0f && C[b + 22u] > 0.0f && C[b + 21u] > 0.0f) { att = exp(log(max(cv3(b, 23u), ((float3)(1e-30f)))) / C[b + 22u] * C[b + 21u]); }
        trans = base * att * under * (tr * (1.0f - mt));
    }
    const float3 shc = cv3(b, 15u);
    const float sh = pmax3(shc);
    if (sh > 0.0f) {
        const float e_sh = read_sh(wo.z, C[b + 18u]);
        const float keep = 1.0f - sh * e_sh;
        spec = spec * keep; irr = irr * keep; trans = trans * keep;
        irr = irr + shc * e_sh;
    }
    const float c = clamp(C[b + 10u], 0.0f, 1.0f);
    float coat = 0.0f;
    const float rc = clamp(C[b + 11u], MIN_ROUGH, 1.0f);
    if (c > 0.0f) {
        const float mu = max(dot(pnorm(cv3(b, 12u)), wo), 0.0f);
        const float kc = kms(0.04f + 0.96f / 21.0f, tab_eavg(rc));
        const float ac = read2(OFF_A, N_THETA, N_ROUGH, mu, rc);
        const float bc = read2(OFF_B, N_THETA, N_ROUGH, mu, rc);
        const float ec = 0.04f * ac + bc + (1.0f - ac - bc) * kc;
        const float keep = (1.0f - c * ec) * (1.0f - c * ec);
        spec = spec * keep; irr = irr * keep; trans = trans * keep;
        coat = c * (0.04f * ac + bc);
        irr = irr + ((float3)(c * kc * (1.0f - ac - bc)));
    }
    float3 acc = spec * env_rough(rr, dominant(n, v, rr)) + irr * sh_irr(n);
    if (pmax3(trans) > 0.0f) {
        float3 td = -v;
        if (C[b + 20u] != 0.0f) {
            const float eta = 1.0f / C[b + 5u];
            const float cs = dot(n, v);
            const float k = 1.0f - eta * eta * (1.0f - cs * cs);
            td = ((k < 0.0f) ? (-v + 2.0f * cs * n) : (eta * (-v) + (eta * cs - sqrt(max(k, 0.0f))) * n));
        }
        acc = acc + trans * env_rough(rr, td);
    }
    if (coat > 0.0f) {
        const float3 bt = cross(n, t);
        const float3 cl = cv3(b, 12u);
        const float3 cn = pnorm(t * cl.x + bt * cl.y + n * cl.z);
        acc = acc + ((float3)(coat)) * env_rough(rc, dominant(cn, v, rc));
    }
    return acc;
}

[numthreads(64, 1, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    const uint k = gid.x;
    if (k >= P.count) { return; }
    const uint b = k * SAMPLE;
    const float3 p = cv3(b, 36u);
    const float3 n = cv3(b, 39u);
    const float3 t = cv3(b, 42u);
    const float3 v = cv3(b, 45u);
    const float3 bt = cross(n, t);
    const float3 wo = float3(dot(v, t), dot(v, bt), dot(v, n));
    float3 sum = cv3(b, 31u) * C[b + 34u];
    const int c = cluster_of(p, P.grid);
    if (c >= 0) {
        const uint cnt = K[uint(c)];
        for (uint j = 0u; j < cnt; j++) {
            const uint li = K[NCLUSTERS + uint(c) * MAX_PER_CLUSTER + j];
            float3 dl = ((float3)(0.0f));
            const float3 e = illum(li, p, dl);
            if (e.x == 0.0f && e.y == 0.0f && e.z == 0.0f) { continue; }
            const float3 wi = float3(dot(dl, t), dot(dl, bt), dot(dl, n));
            sum = sum + eval_case(b, wo, wi) * e * abs(wi.z);
        }
    }
    const float3 o = (sum + ibl(b, wo, n, t, v)) * P.misc.x;
    const uint r = k * 3u;
    R[r] = o.x; R[r + 1u] = o.y; R[r + 2u] = o.z;
}
