// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/post.wgsl. Do not edit.
// WGSL sha256 1d0c5c7d36be2c6aa954cc3c5c1ab987ab213f0463c8246ae69e76d3b66754c1
// Pass: post_ssr

// raw-native GPU screen-space passes (ROADMAP M3): GTAO, mirror SSR and the TAA resolve, the
// float32 forms of src/renderer/post_gtao.cpp, post_ssr.cpp and taa.cpp. Their checks are
// src/renderer/gpu/post_parity.cpp; bounds in evidence/m3-post-bounds.json.

struct PostParams {
    uint width; uint height; uint slices; uint steps;
    uint refine; uint flags; uint ssr_steps; uint pad1;
    float4 view; // tan(fovy / 2), aspect, near plane, GTAO radius
    float4 ssr; // max distance, thickness
    float4 taa; // blend weight, clip sigma
};

struct Probe {
    int j;
    bool behind;
    bool within;
};
// A view-space G-buffer pixel: 8 floats. 0..2 position, 3 view depth (negative: empty), 4..6 normal.
static const uint GB = 8u;
static const float PI = 3.14159265358979f;

// One invocation per pixel: the hit pixel's index as a float, or -1.
ConstantBuffer<PostParams> P : register(b0);
RWStructuredBuffer<float> G : register(u1);
RWStructuredBuffer<float> O : register(u2);

bool on_screen(int x, int y) {
    return x >= 0 && y >= 0 && x < int(P.width) && y < int(P.height);
}
float3 project(float3 p) {
    // Screen position (pixels, y down) in xy; z is 1 when in front of the camera.
    if (p.z >= -1.0e-6f) { return float3(0.0f, 0.0f, 0.0f); }
    const float w = -p.z;
    const float sx = (p.x / (w * P.view.x * P.view.y) * 0.5f + 0.5f) * float(P.width);
    const float sy = (1.0f - (p.y / (w * P.view.x) * 0.5f + 0.5f)) * float(P.height);
    return float3(sx, sy, 1.0f);
}
Probe probe_at(float t, float3 a, float3 e, float k0, float k1) {
    Probe r = (Probe)0;
    r.behind = false;
    r.within = false;
    const int px = int(floor(a.x + (e.x - a.x) * t));
    const int py = int(floor(a.y + (e.y - a.y) * t));
    if (!on_screen(px, py)) { r.j = -2; return r; }
    r.j = py * int(P.width) + px;
    const float d = G[uint(r.j) * GB + 3u];
    if (d < 0.0f) { return r; }
    const float ray = 1.0f / (k0 + (k1 - k0) * t);
    r.behind = ray > d;
    r.within = r.behind && ray - d < P.ssr.y;
    return r;
}

[numthreads(64, 1, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    const uint i = gid.x;
    if (i >= P.width * P.height) { return; }
    O[i] = -1.0f;
    const uint b = i * GB;
    if (G[b + 3u] < 0.0f) { return; }
    const float3 pp = float3(G[b], G[b + 1u], G[b + 2u]);
    const float3 d = pp / length(pp);
    float3 nn = float3(G[b + 4u], G[b + 5u], G[b + 6u]);
    if ((P.flags & 1u) != 0u) { nn = -d; }
    const float3 r = d - 2.0f * dot(d, nn) * nn;
    float len = P.ssr.x;
    if (r.z > 1.0e-9f) { len = min(len, (-P.view.z - pp.z) / r.z * 0.999f); }
    if (len <= 0.0f) { return; }
    const float3 ee = pp + r * len;
    const float3 a = project(pp);
    float3 e = project(ee);
    if (a.z == 0.0f || e.z == 0.0f) { return; }
    const float k0 = -1.0f / pp.z;
    float k1 = -1.0f / ee.z;
    float tend = 1.0f;
    const float lim = 1.0e-3f;
    const float wf = float(P.width);
    const float hf = float(P.height);
    if (e.x > wf - lim && e.x != a.x) { tend = min(tend, (wf - lim - a.x) / (e.x - a.x)); }
    if (e.x < 0.0f && e.x != a.x) { tend = min(tend, (0.0f - a.x) / (e.x - a.x)); }
    if (e.y > hf - lim && e.y != a.y) { tend = min(tend, (hf - lim - a.y) / (e.y - a.y)); }
    if (e.y < 0.0f && e.y != a.y) { tend = min(tend, (0.0f - a.y) / (e.y - a.y)); }
    if (tend <= 0.0f) { return; }
    e = float3(a.x + (e.x - a.x) * tend, a.y + (e.y - a.y) * tend, 1.0f);
    k1 = k0 + (k1 - k0) * tend;
    float prev = 0.0f;
    for (uint s = 1u; s <= P.ssr_steps; s++) {
        const float t = float(s) / float(P.ssr_steps);
        const Probe pr = probe_at(t, a, e, k0, k1);
        if (pr.j == -2) { break; }
        if (pr.behind && pr.j != int(i)) {
            float lo = prev;
            float hi = t;
            for (uint m = 0u; m < P.refine; m++) {
                const float mid = 0.5f * (lo + hi);
                const Probe pm = probe_at(mid, a, e, k0, k1);
                if (pm.behind) { hi = mid; } else { lo = mid; }
            }
            const Probe ph = probe_at(hi, a, e, k0, k1);
            if (ph.within && ph.j >= 0 && ph.j != int(i)) { O[i] = float(ph.j); break; }
        }
        prev = t;
    }
}
