// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/post.wgsl. Do not edit.
// WGSL sha256 1d0c5c7d36be2c6aa954cc3c5c1ab987ab213f0463c8246ae69e76d3b66754c1
// Pass: post_gtao

// raw-native GPU screen-space passes (ROADMAP M3): GTAO, mirror SSR and the TAA resolve, the
// float32 forms of src/renderer/post_gtao.cpp, post_ssr.cpp and taa.cpp. Their checks are
// src/renderer/gpu/post_parity.cpp; bounds in evidence/m3-post-bounds.json.

struct PostParams {
    uint width; uint height; uint slices; uint steps;
    uint refine; uint flags; uint ssr_steps; uint pad1;
    float4 view; // tan(fovy / 2), aspect, near plane, GTAO radius
    float4 ssr; // max distance, thickness
    float4 taa; // blend weight, clip sigma
};
// A view-space G-buffer pixel: 8 floats. 0..2 position, 3 view depth (negative: empty), 4..6 normal.
static const uint GB = 8u;
static const float PI = 3.14159265358979f;

// One invocation per pixel: GTAO visibility (1 where nothing was drawn).
ConstantBuffer<PostParams> P : register(b0);
RWStructuredBuffer<float> G : register(u1);
RWStructuredBuffer<float> O : register(u2);

bool on_screen(int x, int y) {
    return x >= 0 && y >= 0 && x < int(P.width) && y < int(P.height);
}
float3 project(float3 p) {
    // Screen position (pixels, y down) in xy; z is 1 when in front of the camera.
    if (p.z >= -1.0e-6f) { return float3(0.0f, 0.0f, 0.0f); }
    const float w = -p.z;
    const float sx = (p.x / (w * P.view.x * P.view.y) * 0.5f + 0.5f) * float(P.width);
    const float sy = (1.0f - (p.y / (w * P.view.x) * 0.5f + 0.5f)) * float(P.height);
    return float3(sx, sy, 1.0f);
}

bool valid_px(int x, int y) {
    return on_screen(x, y) && G[(uint(y) * P.width + uint(x)) * GB + 3u] >= 0.0f;
}
float sample_depth(float fx, float fy, int sx, int sy) {
    const float nearest = G[(uint(sy) * P.width + uint(sx)) * GB + 3u];
    const int x0 = int(floor(fx - 0.5f));
    const int y0 = int(floor(fy - 0.5f));
    const float ax = fx - 0.5f - float(x0);
    const float ay = fy - 0.5f - float(y0);
    float k[4] = {0.0f, 0.0f, 0.0f, 0.0f};
    float lo = 1.0e30f;
    float hi = 0.0f;
    for (int q = 0; q < 4; q++) {
        const int qx = x0 + (q & 1);
        const int qy = y0 + (q >> 1u);
        if (!valid_px(qx, qy)) { return nearest; }
        const float d = G[(uint(qy) * P.width + uint(qx)) * GB + 3u];
        lo = min(lo, d);
        hi = max(hi, d);
        k[q] = 1.0f / d;
    }
    if (hi > 1.1f * lo) { return nearest; }
    const float inv = (k[0] * (1.0f - ax) + k[1] * ax) * (1.0f - ay) + (k[2] * (1.0f - ax) + k[3] * ax) * ay;
    return 1.0f / inv;
}

[numthreads(64, 1, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    const uint i = gid.x;
    if (i >= P.width * P.height) { return; }
    O[i] = 1.0f;
    const uint b = i * GB;
    const float depth = G[b + 3u];
    if (depth < 0.0f) { return; }
    const int x = int(i % P.width);
    const int y = int(i / P.width);
    const float3 pp = float3(G[b], G[b + 1u], G[b + 2u]);
    const float3 nn = float3(G[b + 4u], G[b + 5u], G[b + 6u]);
    const float3 vv = -pp / length(pp);
    const float rpx = P.view.w * float(P.height) / (2.0f * P.view.x * depth);
    float3 tt = float3(1.0f - vv.x * vv.x, -vv.x * vv.y, -vv.x * vv.z);
    tt = tt / length(tt);
    const float3 bb = cross(vv, tt);
    const float3 s0 = project(pp);
    float total = 0.0f;
    for (uint s = 0u; s < P.slices; s++) {
        const float phi = PI * (float(s) + 0.5f) / float(P.slices);
        const float3 dir = cos(phi) * tt + sin(phi) * bb;
        const float3 s1 = project(pp + dir * (1.0e-3f * depth));
        const float ddl = length(s1.xy - s0.xy);
        if (ddl < 1.0e-12f) { continue; }
        const float c = (s1.x - s0.x) / ddl;
        const float sn = (s1.y - s0.y) / ddl;
        const float3 od = dir - dot(dir, vv) * vv;
        const float3 ax = normalize(cross(od, vv));
        const float3 pn = nn - ax * dot(nn, ax);
        const float pnl = length(pn);
        if (pnl < 1.0e-9f) { continue; }
        const float sgn = ((dot(od, pn) >= 0.0f) ? (1.0f) : (-1.0f));
        const float cn = clamp(dot(pn, vv) / pnl, 0.0f, 1.0f);
        const float nang = sgn * acos(cn);
        float hc0 = cos(nang + PI / 2.0f);
        float hc1 = cos(nang - PI / 2.0f);
        for (uint side = 0u; side < 2u; side++) {
            const float sd = ((side == 0u) ? (1.0f) : (-1.0f));
            for (uint k = 1u; k <= P.steps; k++) {
                const float off = sd * rpx * float(k) / float(P.steps);
                const float fx = float(x) + 0.5f + off * c;
                const float fy = float(y) + 0.5f + off * sn;
                const int sx = int(floor(fx));
                const int sy = int(floor(fy));
                if (!valid_px(sx, sy) || (sx == x && sy == y)) { continue; }
                const float dd = sample_depth(fx, fy, sx, sy);
                const float3 q = float3((fx / float(P.width) * 2.0f - 1.0f) * dd * P.view.x * P.view.y, (1.0f - fy / float(P.height) * 2.0f) * dd * P.view.x, -dd);
                const float3 dv = q - pp;
                const float dl = length(dv);
                if (dl < 1.0e-9f || dl > P.view.w) { continue; }
                if (side == 0u) { hc0 = max(hc0, dot(dv, vv) / dl); } else { hc1 = max(hc1, dot(dv, vv) / dl); }
            }
        }
        const float h1 = nang + min(acos(clamp(hc0, -1.0f, 1.0f)) - nang, PI / 2.0f);
        const float h0 = nang + max(-acos(clamp(hc1, -1.0f, 1.0f)) - nang, -PI / 2.0f);
        const float sn2 = sin(nang);
        const float a0 = (cn + 2.0f * h0 * sn2 - cos(2.0f * h0 - nang)) / 4.0f;
        const float a1 = (cn + 2.0f * h1 * sn2 - cos(2.0f * h1 - nang)) / 4.0f;
        total += pnl * (a0 + a1);
    }
    O[i] = total / float(P.slices);
}
