// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/post.wgsl. Do not edit.
// WGSL sha256 1d0c5c7d36be2c6aa954cc3c5c1ab987ab213f0463c8246ae69e76d3b66754c1
// Pass: post_taa

// raw-native GPU screen-space passes (ROADMAP M3): GTAO, mirror SSR and the TAA resolve, the
// float32 forms of src/renderer/post_gtao.cpp, post_ssr.cpp and taa.cpp. Their checks are
// src/renderer/gpu/post_parity.cpp; bounds in evidence/m3-post-bounds.json.

struct PostParams {
    uint width; uint height; uint slices; uint steps;
    uint refine; uint flags; uint ssr_steps; uint pad1;
    float4 view; // tan(fovy / 2), aspect, near plane, GTAO radius
    float4 ssr; // max distance, thickness
    float4 taa; // blend weight, clip sigma
};
// A view-space G-buffer pixel: 8 floats. 0..2 position, 3 view depth (negative: empty), 4..6 normal.
static const uint GB = 8u;
static const float PI = 3.14159265358979f;

// One invocation per pixel: the TAA resolve. C holds the current frame (colour, view depth),
// R per pixel the history position x, y and the expected previous depth, D the previous depths,
// H the history colour; flags bit 1: clip, bit 2: depth test, bit 4: first frame.
ConstantBuffer<PostParams> P : register(b0);
RWStructuredBuffer<float> C : register(u1);
RWStructuredBuffer<float> R : register(u2);
RWStructuredBuffer<float> D : register(u3);
RWStructuredBuffer<float> H : register(u4);
RWStructuredBuffer<float> O : register(u5);

bool on_screen(int x, int y) {
    return x >= 0 && y >= 0 && x < int(P.width) && y < int(P.height);
}
float3 project(float3 p) {
    // Screen position (pixels, y down) in xy; z is 1 when in front of the camera.
    if (p.z >= -1.0e-6f) { return float3(0.0f, 0.0f, 0.0f); }
    const float w = -p.z;
    const float sx = (p.x / (w * P.view.x * P.view.y) * 0.5f + 0.5f) * float(P.width);
    const float sy = (1.0f - (p.y / (w * P.view.x) * 0.5f + 0.5f)) * float(P.height);
    return float3(sx, sy, 1.0f);
}

float3 ycocg(float3 c) {
    return float3(0.25f * c.x + 0.5f * c.y + 0.25f * c.z, 0.5f * c.x - 0.5f * c.z, -0.25f * c.x + 0.5f * c.y - 0.25f * c.z);
}
float3 rgb_of(float3 c) {
    return float3(c.x + c.y - c.z, c.x + c.z, c.x - c.y - c.z);
}
float4 cr_weights(float t) {
    const float t2 = t * t;
    const float t3 = t2 * t;
    return float4(-0.5f * t3 + t2 - 0.5f * t, 1.5f * t3 - 2.5f * t2 + 1.0f, -1.5f * t3 + 2.0f * t2 + 0.5f * t, 0.5f * t3 - 0.5f * t2);
}
float3 cur_rgb(int x, int y) {
    const uint j = (uint(y) * P.width + uint(x)) * 4u;
    return float3(C[j], C[j + 1u], C[j + 2u]);
}

[numthreads(64, 1, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    const uint i = gid.x;
    if (i >= P.width * P.height) { return; }
    const int w = int(P.width);
    const int h = int(P.height);
    const int x = int(i) % w;
    const int y = int(i) / w;
    const float3 cur = cur_rgb(x, y);
    O[i * 3u] = cur.x;
    O[i * 3u + 1u] = cur.y;
    O[i * 3u + 2u] = cur.z;
    if ((P.flags & 4u) != 0u) { return; }
    const float px = R[i * 3u];
    const float py = R[i * 3u + 1u];
    const float ed = R[i * 3u + 2u];
    if (px < 0.5f || py < 0.5f || px > float(w) - 0.5f || py > float(h) - 0.5f) { return; }
    if ((P.flags & 2u) != 0u) {
        const int nx = min(w - 1, int(px));
        const int ny = min(h - 1, int(py));
        float lo = 1.0e30f;
        float hi = -1.0f;
        bool empty = false;
        for (int b = -1; b <= 1; b++) {
            for (int a = -1; a <= 1; a++) {
                const int qx = clamp(nx + a, 0, w - 1);
                const int qy = clamp(ny + b, 0, h - 1);
                const float pd = D[uint(qy * w + qx)];
                if (pd < 0.0f) { empty = true; continue; }
                lo = min(lo, pd);
                hi = max(hi, pd);
            }
        }
        const float tol = 0.02f * ed + 0.02f;
        if (ed < 0.0f) {
            if (!empty) { return; }
        } else if (hi < 0.0f || ed < lo - tol || ed > hi + tol) {
            return;
        }
    }
    const float fx = px - 0.5f;
    const float fy = py - 0.5f;
    const int x0 = int(floor(fx));
    const int y0 = int(floor(fy));
    const float4 wx = cr_weights(fx - float(x0));
    const float4 wy = cr_weights(fy - float(y0));
    float3 hc = float3(0.0f, 0.0f, 0.0f);
    for (int tb = 0; tb < 4; tb++) {
        for (int ta = 0; ta < 4; ta++) {
            const int qx = clamp(x0 - 1 + ta, 0, w - 1);
            const int qy = clamp(y0 - 1 + tb, 0, h - 1);
            const uint j = uint(qy * w + qx) * 3u;
            hc += wx[ta] * wy[tb] * float3(H[j], H[j + 1u], H[j + 2u]);
        }
    }
    if ((P.flags & 1u) != 0u) {
        float3 m = float3(0.0f, 0.0f, 0.0f);
        float n = 0.0f;
        for (int nb = -1; nb <= 1; nb++) {
            for (int na = -1; na <= 1; na++) {
                const int qx = x + na;
                const int qy = y + nb;
                if (qx < 0 || qy < 0 || qx >= w || qy >= h) { continue; }
                m += ycocg(cur_rgb(qx, qy));
                n += 1.0f;
            }
        }
        m = m / n;
        float3 vr = float3(0.0f, 0.0f, 0.0f);
        for (int vb = -1; vb <= 1; vb++) {
            for (int va = -1; va <= 1; va++) {
                const int qx = x + va;
                const int qy = y + vb;
                if (qx < 0 || qy < 0 || qx >= w || qy >= h) { continue; }
                const float3 dv = ycocg(cur_rgb(qx, qy)) - m;
                vr += dv * dv;
            }
        }
        const float3 sd = sqrt(vr / n);
        const float3 ext = P.taa.y * sd + float3(1.0e-7f, 1.0e-7f, 1.0e-7f);
        float3 hy = ycocg(hc);
        const float3 q = abs(hy - m) / ext;
        const float scale = max(q.x, max(q.y, q.z));
        if (scale > 1.0f) { hy = m + (hy - m) / scale; }
        hc = rgb_of(hy);
    }
    const float3 res = hc + (cur - hc) * P.taa.x;
    O[i * 3u] = res.x;
    O[i * 3u + 1u] = res.y;
    O[i * 3u + 2u] = res.z;
}
