// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/pt.wgsl. Do not edit.
// WGSL sha256 33bf5032533b409282c3f931d1244cc04b6dd7e6d452c66557c7dae67663f644
// Pass: pt_finish

// raw-native's path tracer on the GPU (RT stage R2): the compute form of
// src/renderer/rt_pt_cpu.cpp and rt_pt_math.hpp, interface v1 (raw/renderer/rt_pathtrace.hpp).
// pt_trace accumulates a slice of samples per pixel into ACC; pt_finish writes the outputs.
//
// ACC, 16 floats a pixel: radiance sum (3), luminance Welford n, mean, M2 (3), albedo sum (3),
// normal sum (3), depth, motion (2), triangle. O, 16 floats a pixel: radiance (3), albedo (3),
// normal (3), depth, motion (2), variance, triangle (-1 a miss), pad (2).

struct PtParams {
    uint w; uint h; uint sppBegin; uint sppCount;
    uint maxBounces; uint flags; uint seedLo; uint seedHi;
    uint root; uint emitters; uint emitterOffset; float emitterArea;
    float4 eye; float4 fwd; float4 side; float4 up;
    float4 peye; float4 pfwd; float4 pside; float4 pup;
    float4 sun; float4 sunIrr; float4 sky;
};
static const float PI = 3.14159265f;
static const float BIG = 3.40282347e+38f;
static const float SLAB = 1.00000036f;
static const uint F_JITTER = 1u;
static const uint F_RR = 2u;
static const uint F_DROPCOS = 4u;
static const uint F_MISONE = 8u;
static const uint F_FIRST = 16u;

// One invocation per pixel: means, the variance of the mean, and the centre-ray AOVs into O.
ConstantBuffer<PtParams> P : register(b0);
RWStructuredBuffer<float> ACC : register(u1);
RWStructuredBuffer<float> O : register(u2);

uint2 pcg2d(uint2 v0) {
    uint2 v = v0 * 1664525u + 1013904223u;
    v.x = v.x + v.y * 1664525u;
    v.y = v.y + v.x * 1664525u;
    v = v ^ (v >> ((uint2)(16u)));
    v.x = v.x + v.y * 1664525u;
    v.y = v.y + v.x * 1664525u;
    v = v ^ (v >> ((uint2)(16u)));
    return v;
}
float2 rand2(uint seedLo, uint seedHi, uint px, uint smp, uint dim) {
    const uint2 v = pcg2d(uint2(px ^ (seedLo * 0x9E3779B9u), (smp * 64u + dim) ^ seedHi));
    return float2(float(v.x >> 8u), float(v.y >> 8u)) * 5.96046448e-8f;
}
float lum(float3 c) {
    return 0.2126f * c.x + 0.7152f * c.y + 0.0722f * c.z;
}
float ggx_d(float a2, float c) {
    const float d = c * c * (a2 - 1.0f) + 1.0f;
    return a2 / (PI * d * d);
}
float lambda_g(float a2, float c) {
    const float c2 = c * c;
    return (-1.0f + sqrt(1.0f + a2 * (1.0f - c2) / c2)) * 0.5f;
}
float lobe_prob(float metal, float spec) {
    return metal + (1.0f - metal) * 0.5f * spec;
}
// f cos and the mixture pdf, local frame: xyz f cos, w pdf.
float4 eval_bsdf(float3 base, float rough, float metal, float spec, float3 wo, float3 wi, bool dropCos) {
    if (wo.z <= 0.0f || wi.z <= 0.0f) { return ((float4)(0.0f)); }
    const float ps = lobe_prob(metal, spec);
    const float cosI = ((dropCos) ? (1.0f) : (wi.z));
    float3 f = base * ((1.0f - metal) / PI);
    float pdf = (1.0f - ps) * wi.z / PI;
    if (ps > 0.0f) {
        const float a = max(1e-4f, rough * rough);
        const float a2 = a * a;
        const float3 h = normalize(wo + wi);
        const float oh = dot(wo, h);
        const float dd = ggx_d(a2, h.z);
        const float g2 = 1.0f / (1.0f + lambda_g(a2, wo.z) + lambda_g(a2, wi.z));
        const float g1 = 1.0f / (1.0f + lambda_g(a2, wo.z));
        const float x1 = clamp(1.0f - oh, 0.0f, 1.0f);
        const float fw = x1 * x1 * x1 * x1 * x1;
        const float3 f0 = lerp(((float3)(0.04f * spec)), base, ((float3)(metal)));
        f = f + (f0 + (((float3)(1.0f)) - f0) * fw) * (dd * g2 / (4.0f * wo.z * wi.z));
        pdf = pdf + ps * g1 * dd / (4.0f * wo.z);
    }
    return float4(f * cosI, pdf);
}
float3 sample_vndf(float3 wo, float a, float u1, float u2) {
    const float3 vh = normalize(float3(a * wo.x, a * wo.y, wo.z));
    const float lensq = vh.x * vh.x + vh.y * vh.y;
    float3 t1 = float3(1.0f, 0.0f, 0.0f);
    if (lensq > 0.0f) { t1 = float3(-vh.y, vh.x, 0.0f) * (1.0f / sqrt(lensq)); }
    const float3 t2 = cross(vh, t1);
    const float r = sqrt(u1);
    const float phi = 2.0f * PI * u2;
    const float p1 = r * cos(phi);
    const float s = 0.5f * (1.0f + vh.z);
    const float p2 = (1.0f - s) * sqrt(max(0.0f, 1.0f - p1 * p1)) + s * (r * sin(phi));
    const float3 nh = t1 * p1 + t2 * p2 + vh * sqrt(max(0.0f, 1.0f - p1 * p1 - p2 * p2));
    return normalize(float3(a * nh.x, a * nh.y, max(0.0f, nh.z)));
}
// xyz the sampled direction (local), w 1 when it is above the surface.
float4 sample_bsdf(float rough, float metal, float spec, float3 wo, float pick, float u1, float u2) {
    float3 wi = ((float3)(0.0f));
    if (pick < lobe_prob(metal, spec)) {
        const float3 h = sample_vndf(wo, max(1e-4f, rough * rough), u1, u2);
        wi = h * (2.0f * dot(wo, h)) - wo;
    } else {
        const float r = sqrt(u1);
        const float phi = 2.0f * PI * u2;
        wi = float3(r * cos(phi), r * sin(phi), sqrt(max(0.0f, 1.0f - u1)));
    }
    return float4(wi, ((wi.z > 0.0f) ? (1.0f) : (0.0f)));
}
// Duff et al. 2017: tangent and bitangent of n.
float3 basis_t(float3 n) {
    const float s = ((n.z >= 0.0f) ? (1.0f) : (-1.0f));
    const float a = -1.0f / (s + n.z);
    return float3(1.0f + s * n.x * n.x * a, s * n.x * n.y * a, -s * n.x);
}
float3 basis_b(float3 n) {
    const float s = ((n.z >= 0.0f) ? (1.0f) : (-1.0f));
    const float a = -1.0f / (s + n.z);
    return float3(n.x * n.y * a, s + n.y * n.y * a, -n.y);
}

[numthreads(8, 8, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    if (gid.x >= P.w || gid.y >= P.h) { return; }
    const uint o = (gid.y * P.w + gid.x) * 16u;
    const float n = ACC[o + 3u];
    const float inv = ((n > 0.0f) ? (1.0f / n) : (0.0f));
    for (uint k = 0u; k < 3u; k++) {
        O[o + k] = ACC[o + k] * inv;
        O[o + 3u + k] = ACC[o + 6u + k] * inv;
        O[o + 6u + k] = ACC[o + 9u + k] * inv;
    }
    O[o + 9u] = ACC[o + 12u];
    O[o + 10u] = ACC[o + 13u];
    O[o + 11u] = ACC[o + 14u];
    O[o + 12u] = ((n > 1.0f) ? (ACC[o + 5u] / (n - 1.0f) / n) : (0.0f));
    O[o + 13u] = ACC[o + 15u];
    O[o + 14u] = 0.0f;
    O[o + 15u] = 0.0f;
}
