// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/pt.wgsl. Do not edit.
// WGSL sha256 c9f03d8eb58a8dee49a64c2b8b8712c9a5415a010516309eada30704c346837b
// Pass: pt_hybrid

// raw-native's path tracer on the GPU (RT stage R2): the compute form of
// src/renderer/rt_pt_cpu.cpp and rt_pt_math.hpp, interface v1 (raw/renderer/rt_pathtrace.hpp).
// pt_trace accumulates a slice of samples per pixel into ACC; pt_finish writes the outputs.
//
// ACC, 16 floats a pixel: radiance sum (3), luminance Welford n, mean, M2 (3), albedo sum (3),
// normal sum (3), depth, motion (2), triangle. O, 16 floats a pixel: radiance (3), albedo (3),
// normal (3), depth, motion (2), variance, triangle (-1 a miss), pad (2).

struct PtParams {
    uint w; uint h; uint sppBegin; uint sppCount;
    uint maxBounces; uint flags; uint seedLo; uint seedHi;
    uint root; uint emitters; uint emitterOffset; float emitterArea;
    float4 eye; float4 fwd; float4 side; float4 up;
    float4 peye; float4 pfwd; float4 pside; float4 pup;
    float4 sun; float4 sunIrr; float4 sky;
};
static const float PI = 3.14159265f;
static const float BIG = 3.40282347e+38f;
static const float SLAB = 1.00000036f;
static const uint F_JITTER = 1u;
static const uint F_RR = 2u;
static const uint F_DROPCOS = 4u;
static const uint F_MISONE = 8u;
static const uint F_FIRST = 16u;

// One invocation per pixel of a raster G-buffer (swr_gbuffer): a sun shadow ray (any hit) and
// one mirror reflection ray about the shading normal (closest hit) through the BVH. P.flags
// bit 32 drops the origin offset (H1 control), bit 64 tilts the shading normal by 0.05 rad (H2 control).
// O: 4 floats a pixel: 1 lit / 0 shadowed (-1 uncovered), reflected triangle (-1 none), its t, pad.
ConstantBuffer<PtParams> P : register(b0);
RWStructuredBuffer<int> NI : register(u1);
RWStructuredBuffer<float> NB : register(u2);
RWStructuredBuffer<float> T : register(u3);
RWStructuredBuffer<float> G : register(u4);
RWStructuredBuffer<float> O : register(u5);

uint2 pcg2d(uint2 v0) {
    uint2 v = v0 * 1664525u + 1013904223u;
    v.x = v.x + v.y * 1664525u;
    v.y = v.y + v.x * 1664525u;
    v = v ^ (v >> ((uint2)(16u)));
    v.x = v.x + v.y * 1664525u;
    v.y = v.y + v.x * 1664525u;
    v = v ^ (v >> ((uint2)(16u)));
    return v;
}
float2 rand2(uint seedLo, uint seedHi, uint px, uint smp, uint dim) {
    const uint2 v = pcg2d(uint2(px ^ (seedLo * 0x9E3779B9u), (smp * 64u + dim) ^ seedHi));
    return float2(float(v.x >> 8u), float(v.y >> 8u)) * 5.96046448e-8f;
}
float lum(float3 c) {
    return 0.2126f * c.x + 0.7152f * c.y + 0.0722f * c.z;
}
float ggx_d(float a2, float c) {
    const float d = c * c * (a2 - 1.0f) + 1.0f;
    return a2 / (PI * d * d);
}
float lambda_g(float a2, float c) {
    const float c2 = c * c;
    return (-1.0f + sqrt(1.0f + a2 * (1.0f - c2) / c2)) * 0.5f;
}
float lobe_prob(float metal, float spec) {
    return metal + (1.0f - metal) * 0.5f * spec;
}
// f cos and the mixture pdf, local frame: xyz f cos, w pdf.
float4 eval_bsdf(float3 base, float rough, float metal, float spec, float3 wo, float3 wi, bool dropCos) {
    if (wo.z <= 0.0f || wi.z <= 0.0f) { return ((float4)(0.0f)); }
    const float ps = lobe_prob(metal, spec);
    const float cosI = ((dropCos) ? (1.0f) : (wi.z));
    float3 f = base * ((1.0f - metal) / PI);
    float pdf = (1.0f - ps) * wi.z / PI;
    if (ps > 0.0f) {
        const float a = max(1e-4f, rough * rough);
        const float a2 = a * a;
        const float3 h = normalize(wo + wi);
        const float oh = dot(wo, h);
        const float dd = ggx_d(a2, h.z);
        const float g2 = 1.0f / (1.0f + lambda_g(a2, wo.z) + lambda_g(a2, wi.z));
        const float g1 = 1.0f / (1.0f + lambda_g(a2, wo.z));
        const float x1 = clamp(1.0f - oh, 0.0f, 1.0f);
        const float fw = x1 * x1 * x1 * x1 * x1;
        const float3 f0 = lerp(((float3)(0.04f * spec)), base, ((float3)(metal)));
        f = f + (f0 + (((float3)(1.0f)) - f0) * fw) * (dd * g2 / (4.0f * wo.z * wi.z));
        pdf = pdf + ps * g1 * dd / (4.0f * wo.z);
    }
    return float4(f * cosI, pdf);
}
float3 sample_vndf(float3 wo, float a, float u1, float u2) {
    const float3 vh = normalize(float3(a * wo.x, a * wo.y, wo.z));
    const float lensq = vh.x * vh.x + vh.y * vh.y;
    float3 t1 = float3(1.0f, 0.0f, 0.0f);
    if (lensq > 0.0f) { t1 = float3(-vh.y, vh.x, 0.0f) * (1.0f / sqrt(lensq)); }
    const float3 t2 = cross(vh, t1);
    const float r = sqrt(u1);
    const float phi = 2.0f * PI * u2;
    const float p1 = r * cos(phi);
    const float s = 0.5f * (1.0f + vh.z);
    const float p2 = (1.0f - s) * sqrt(max(0.0f, 1.0f - p1 * p1)) + s * (r * sin(phi));
    const float3 nh = t1 * p1 + t2 * p2 + vh * sqrt(max(0.0f, 1.0f - p1 * p1 - p2 * p2));
    return normalize(float3(a * nh.x, a * nh.y, max(0.0f, nh.z)));
}
// xyz the sampled direction (local), w 1 when it is above the surface.
float4 sample_bsdf(float rough, float metal, float spec, float3 wo, float pick, float u1, float u2) {
    float3 wi = ((float3)(0.0f));
    if (pick < lobe_prob(metal, spec)) {
        const float3 h = sample_vndf(wo, max(1e-4f, rough * rough), u1, u2);
        wi = h * (2.0f * dot(wo, h)) - wo;
    } else {
        const float r = sqrt(u1);
        const float phi = 2.0f * PI * u2;
        wi = float3(r * cos(phi), r * sin(phi), sqrt(max(0.0f, 1.0f - u1)));
    }
    return float4(wi, ((wi.z > 0.0f) ? (1.0f) : (0.0f)));
}
// Duff et al. 2017: tangent and bitangent of n.
float3 basis_t(float3 n) {
    const float s = ((n.z >= 0.0f) ? (1.0f) : (-1.0f));
    const float a = -1.0f / (s + n.z);
    return float3(1.0f + s * n.x * n.x * a, s * n.x * n.y * a, -s * n.x);
}
float3 basis_b(float3 n) {
    const float s = ((n.z >= 0.0f) ? (1.0f) : (-1.0f));
    const float a = -1.0f / (s + n.z);
    return float3(n.x * n.y * a, s + n.y * n.y * a, -n.y);
}

float3 vtx(uint t, uint k) {
    return float3(T[t * 9u + k * 3u], T[t * 9u + k * 3u + 1u], T[t * 9u + k * 3u + 2u]);
}
float4 hit_tri(uint t, float3 o, float3 d) {
    const float3 a = vtx(t, 0u);
    const float3 e1 = vtx(t, 1u) - a;
    const float3 e2 = vtx(t, 2u) - a;
    const float3 p = float3(d.y * e2.z - d.z * e2.y, d.z * e2.x - d.x * e2.z, d.x * e2.y - d.y * e2.x);
    const float det = e1.x * p.x + e1.y * p.y + e1.z * p.z;
    if (det > -1e-7f && det < 1e-7f) { return ((float4)(0.0f)); }
    const float inv = 1.0f / det;
    const float3 tv = o - a;
    const float u = (tv.x * p.x + tv.y * p.y + tv.z * p.z) * inv;
    if (u < 0.0f || u > 1.0f) { return ((float4)(0.0f)); }
    const float3 q = float3(tv.y * e1.z - tv.z * e1.y, tv.z * e1.x - tv.x * e1.z, tv.x * e1.y - tv.y * e1.x);
    const float v = (d.x * q.x + d.y * q.y + d.z * q.z) * inv;
    if (v < 0.0f || u + v > 1.0f) { return ((float4)(0.0f)); }
    const float tt = (e2.x * q.x + e2.y * q.y + e2.z * q.z) * inv;
    return float4(tt, u, v, ((tt > 1e-4f) ? (1.0f) : (0.0f)));
}
float inv_c(float x) {
    if (x != 0.0f) { return 1.0f / x; }
    return ((x >= 0.0f) ? (BIG) : (-BIG));
}
float4 trace(float3 o, float3 d, float tMax, bool anyHit) {
    const float3 iv = float3(inv_c(d.x), inv_c(d.y), inv_c(d.z));
    float4 best = float4(tMax, 0.0f, 0.0f, -1.0f);
    uint stack[64] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    uint sp = 1u;
    stack[0] = P.root;
    for (uint guard = 0u; guard < 1000000u; guard++) {
        if (sp == 0u) { break; }
        sp = sp - 1u;
        const uint n = stack[sp];
        const float3 lo = (float3(NB[n * 8u], NB[n * 8u + 1u], NB[n * 8u + 2u]) - o) * iv;
        const float3 hi = (float3(NB[n * 8u + 3u], NB[n * 8u + 4u], NB[n * 8u + 5u]) - o) * iv;
        const float3 mn = min(lo, hi);
        const float3 mx = max(lo, hi);
        const float t0 = max(max(max(0.0f, mn.x), mn.y), mn.z);
        const float t1 = min(min(min(best.x, mx.x), mx.y), mx.z);
        if (!(t0 <= t1 * SLAB)) { continue; }
        const int leaf = NI[n * 4u + 2u];
        if (leaf >= 0) {
            const float4 h = hit_tri(uint(leaf), o, d);
            if (h.w > 0.0f && (h.x < best.x || (best.w >= 0.0f && h.x == best.x && float(leaf) < best.w))) {
                best = float4(h.x, h.y, h.z, float(leaf));
                if (anyHit) { break; }
            }
            continue;
        }
        if (sp + 2u > 64u) { break; }
        stack[sp] = uint(NI[n * 4u + 1u]);
        stack[sp + 1u] = uint(NI[n * 4u]);
        sp = sp + 2u;
    }
    return best;
}
float3 offset_h(float3 p, float3 ng, float3 dir) {
    if ((P.flags & 32u) != 0u) { return p; }
    const float e = 2e-4f * (1.0f + max(abs(p.x), max(abs(p.y), abs(p.z))));
    return p + ng * ((dot(ng, dir) > 0.0f) ? (e) : (-e));
}

[numthreads(8, 8, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    if (gid.x >= P.w || gid.y >= P.h) { return; }
    const uint p = gid.y * P.w + gid.x;
    O[p * 4u] = -1.0f;
    O[p * 4u + 1u] = -1.0f;
    O[p * 4u + 2u] = 0.0f;
    O[p * 4u + 3u] = 0.0f;
    if (G[p * 12u + 9u] == 0.0f) { return; }
    const float3 pos = float3(G[p * 12u], G[p * 12u + 1u], G[p * 12u + 2u]);
    const float3 d = normalize(pos - P.eye.xyz);
    float3 ng = float3(G[p * 12u + 3u], G[p * 12u + 4u], G[p * 12u + 5u]);
    float3 n = float3(G[p * 12u + 6u], G[p * 12u + 7u], G[p * 12u + 8u]);
    if (dot(ng, d) > 0.0f) { ng = -ng; }
    if (dot(n, ng) < 0.0f) { n = -n; }
    if ((P.flags & 64u) != 0u) { n = normalize(n + basis_t(n) * 0.05f); }
    const float3 l = P.sun.xyz;
    O[p * 4u] = ((trace(offset_h(pos, ng, l), l, BIG, true).w < 0.0f) ? (1.0f) : (0.0f));
    const float3 r = d - n * (2.0f * dot(d, n));
    const float4 h = trace(offset_h(pos, ng, r), r, BIG, false);
    O[p * 4u + 1u] = h.w;
    O[p * 4u + 2u] = ((h.w >= 0.0f) ? (h.x) : (0.0f));
}
