// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/pt.wgsl. Do not edit.
// WGSL sha256 c9f03d8eb58a8dee49a64c2b8b8712c9a5415a010516309eada30704c346837b
// Pass: pt_trace

// raw-native's path tracer on the GPU (RT stage R2): the compute form of
// src/renderer/rt_pt_cpu.cpp and rt_pt_math.hpp, interface v1 (raw/renderer/rt_pathtrace.hpp).
// pt_trace accumulates a slice of samples per pixel into ACC; pt_finish writes the outputs.
//
// ACC, 16 floats a pixel: radiance sum (3), luminance Welford n, mean, M2 (3), albedo sum (3),
// normal sum (3), depth, motion (2), triangle. O, 16 floats a pixel: radiance (3), albedo (3),
// normal (3), depth, motion (2), variance, triangle (-1 a miss), pad (2).

struct PtParams {
    uint w; uint h; uint sppBegin; uint sppCount;
    uint maxBounces; uint flags; uint seedLo; uint seedHi;
    uint root; uint emitters; uint emitterOffset; float emitterArea;
    float4 eye; float4 fwd; float4 side; float4 up;
    float4 peye; float4 pfwd; float4 pside; float4 pup;
    float4 sun; float4 sunIrr; float4 sky;
};
static const float PI = 3.14159265f;
static const float BIG = 3.40282347e+38f;
static const float SLAB = 1.00000036f;
static const uint F_JITTER = 1u;
static const uint F_RR = 2u;
static const uint F_DROPCOS = 4u;
static const uint F_MISONE = 8u;
static const uint F_FIRST = 16u;

// One invocation per pixel: samples [P.sppBegin, P.sppBegin + P.sppCount) added into ACC.
// NI, NB the BVH (rt.wgsl's layout, root P.root); T triangles (9 floats); A attributes
// (16 floats a triangle: u v nx ny nz of each vertex, texture); TX textures (offset, width,
// height per texture, then texels); M materials (8 floats a texture: factor, roughness,
// metallic, specular, emission rgb, pad) then from P.emitterOffset (triangle, cdf) pairs.
ConstantBuffer<PtParams> P : register(b0);
RWStructuredBuffer<int> NI : register(u1);
RWStructuredBuffer<float> NB : register(u2);
RWStructuredBuffer<float> T : register(u3);
RWStructuredBuffer<float> A : register(u4);
RWStructuredBuffer<uint> TX : register(u5);
RWStructuredBuffer<float> M : register(u6);
RWStructuredBuffer<float> ACC : register(u7);

uint2 pcg2d(uint2 v0) {
    uint2 v = v0 * 1664525u + 1013904223u;
    v.x = v.x + v.y * 1664525u;
    v.y = v.y + v.x * 1664525u;
    v = v ^ (v >> ((uint2)(16u)));
    v.x = v.x + v.y * 1664525u;
    v.y = v.y + v.x * 1664525u;
    v = v ^ (v >> ((uint2)(16u)));
    return v;
}
float2 rand2(uint seedLo, uint seedHi, uint px, uint smp, uint dim) {
    const uint2 v = pcg2d(uint2(px ^ (seedLo * 0x9E3779B9u), (smp * 64u + dim) ^ seedHi));
    return float2(float(v.x >> 8u), float(v.y >> 8u)) * 5.96046448e-8f;
}
float lum(float3 c) {
    return 0.2126f * c.x + 0.7152f * c.y + 0.0722f * c.z;
}
float ggx_d(float a2, float c) {
    const float d = c * c * (a2 - 1.0f) + 1.0f;
    return a2 / (PI * d * d);
}
float lambda_g(float a2, float c) {
    const float c2 = c * c;
    return (-1.0f + sqrt(1.0f + a2 * (1.0f - c2) / c2)) * 0.5f;
}
float lobe_prob(float metal, float spec) {
    return metal + (1.0f - metal) * 0.5f * spec;
}
// f cos and the mixture pdf, local frame: xyz f cos, w pdf.
float4 eval_bsdf(float3 base, float rough, float metal, float spec, float3 wo, float3 wi, bool dropCos) {
    if (wo.z <= 0.0f || wi.z <= 0.0f) { return ((float4)(0.0f)); }
    const float ps = lobe_prob(metal, spec);
    const float cosI = ((dropCos) ? (1.0f) : (wi.z));
    float3 f = base * ((1.0f - metal) / PI);
    float pdf = (1.0f - ps) * wi.z / PI;
    if (ps > 0.0f) {
        const float a = max(1e-4f, rough * rough);
        const float a2 = a * a;
        const float3 h = normalize(wo + wi);
        const float oh = dot(wo, h);
        const float dd = ggx_d(a2, h.z);
        const float g2 = 1.0f / (1.0f + lambda_g(a2, wo.z) + lambda_g(a2, wi.z));
        const float g1 = 1.0f / (1.0f + lambda_g(a2, wo.z));
        const float x1 = clamp(1.0f - oh, 0.0f, 1.0f);
        const float fw = x1 * x1 * x1 * x1 * x1;
        const float3 f0 = lerp(((float3)(0.04f * spec)), base, ((float3)(metal)));
        f = f + (f0 + (((float3)(1.0f)) - f0) * fw) * (dd * g2 / (4.0f * wo.z * wi.z));
        pdf = pdf + ps * g1 * dd / (4.0f * wo.z);
    }
    return float4(f * cosI, pdf);
}
float3 sample_vndf(float3 wo, float a, float u1, float u2) {
    const float3 vh = normalize(float3(a * wo.x, a * wo.y, wo.z));
    const float lensq = vh.x * vh.x + vh.y * vh.y;
    float3 t1 = float3(1.0f, 0.0f, 0.0f);
    if (lensq > 0.0f) { t1 = float3(-vh.y, vh.x, 0.0f) * (1.0f / sqrt(lensq)); }
    const float3 t2 = cross(vh, t1);
    const float r = sqrt(u1);
    const float phi = 2.0f * PI * u2;
    const float p1 = r * cos(phi);
    const float s = 0.5f * (1.0f + vh.z);
    const float p2 = (1.0f - s) * sqrt(max(0.0f, 1.0f - p1 * p1)) + s * (r * sin(phi));
    const float3 nh = t1 * p1 + t2 * p2 + vh * sqrt(max(0.0f, 1.0f - p1 * p1 - p2 * p2));
    return normalize(float3(a * nh.x, a * nh.y, max(0.0f, nh.z)));
}
// xyz the sampled direction (local), w 1 when it is above the surface.
float4 sample_bsdf(float rough, float metal, float spec, float3 wo, float pick, float u1, float u2) {
    float3 wi = ((float3)(0.0f));
    if (pick < lobe_prob(metal, spec)) {
        const float3 h = sample_vndf(wo, max(1e-4f, rough * rough), u1, u2);
        wi = h * (2.0f * dot(wo, h)) - wo;
    } else {
        const float r = sqrt(u1);
        const float phi = 2.0f * PI * u2;
        wi = float3(r * cos(phi), r * sin(phi), sqrt(max(0.0f, 1.0f - u1)));
    }
    return float4(wi, ((wi.z > 0.0f) ? (1.0f) : (0.0f)));
}
// Duff et al. 2017: tangent and bitangent of n.
float3 basis_t(float3 n) {
    const float s = ((n.z >= 0.0f) ? (1.0f) : (-1.0f));
    const float a = -1.0f / (s + n.z);
    return float3(1.0f + s * n.x * n.x * a, s * n.x * n.y * a, -s * n.x);
}
float3 basis_b(float3 n) {
    const float s = ((n.z >= 0.0f) ? (1.0f) : (-1.0f));
    const float a = -1.0f / (s + n.z);
    return float3(n.x * n.y * a, s + n.y * n.y * a, -n.y);
}

float3 vtx(uint t, uint k) {
    return float3(T[t * 9u + k * 3u], T[t * 9u + k * 3u + 1u], T[t * 9u + k * 3u + 2u]);
}
// Moeller-Trumbore, raw/math/primitives.hpp's order: x t, y u, z v, w 1 on a hit.
float4 hit_tri(uint t, float3 o, float3 d) {
    const float3 a = vtx(t, 0u);
    const float3 e1 = vtx(t, 1u) - a;
    const float3 e2 = vtx(t, 2u) - a;
    const float3 p = float3(d.y * e2.z - d.z * e2.y, d.z * e2.x - d.x * e2.z, d.x * e2.y - d.y * e2.x);
    const float det = e1.x * p.x + e1.y * p.y + e1.z * p.z;
    if (det > -1e-7f && det < 1e-7f) { return ((float4)(0.0f)); }
    const float inv = 1.0f / det;
    const float3 tv = o - a;
    const float u = (tv.x * p.x + tv.y * p.y + tv.z * p.z) * inv;
    if (u < 0.0f || u > 1.0f) { return ((float4)(0.0f)); }
    const float3 q = float3(tv.y * e1.z - tv.z * e1.y, tv.z * e1.x - tv.x * e1.z, tv.x * e1.y - tv.y * e1.x);
    const float v = (d.x * q.x + d.y * q.y + d.z * q.z) * inv;
    if (v < 0.0f || u + v > 1.0f) { return ((float4)(0.0f)); }
    const float tt = (e2.x * q.x + e2.y * q.y + e2.z * q.z) * inv;
    return float4(tt, u, v, ((tt > 1e-4f) ? (1.0f) : (0.0f)));
}
float inv_c(float x) {
    if (x != 0.0f) { return 1.0f / x; }
    return ((x >= 0.0f) ? (BIG) : (-BIG));
}
// The nearest hit with t < tMax (any hit when anyHit): x t, y u, z v, w triangle (-1 none).
float4 trace(float3 o, float3 d, float tMax, bool anyHit) {
    const float3 iv = float3(inv_c(d.x), inv_c(d.y), inv_c(d.z));
    float4 best = float4(tMax, 0.0f, 0.0f, -1.0f);
    uint stack[64] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    uint sp = 1u;
    stack[0] = P.root;
    for (uint guard = 0u; guard < 1000000u; guard++) {
        if (sp == 0u) { break; }
        sp = sp - 1u;
        const uint n = stack[sp];
        const float3 lo = (float3(NB[n * 8u], NB[n * 8u + 1u], NB[n * 8u + 2u]) - o) * iv;
        const float3 hi = (float3(NB[n * 8u + 3u], NB[n * 8u + 4u], NB[n * 8u + 5u]) - o) * iv;
        const float3 mn = min(lo, hi);
        const float3 mx = max(lo, hi);
        const float t0 = max(max(max(0.0f, mn.x), mn.y), mn.z);
        const float t1 = min(min(min(best.x, mx.x), mx.y), mx.z);
        if (!(t0 <= t1 * SLAB)) { continue; }
        const int leaf = NI[n * 4u + 2u];
        if (leaf >= 0) {
            const float4 h = hit_tri(uint(leaf), o, d);
            if (h.w > 0.0f && (h.x < best.x || (best.w >= 0.0f && h.x == best.x && float(leaf) < best.w))) {
                best = float4(h.x, h.y, h.z, float(leaf));
                if (anyHit) { break; }
            }
            continue;
        }
        if (sp + 2u > 64u) { break; }
        stack[sp] = uint(NI[n * 4u + 1u]);
        stack[sp + 1u] = uint(NI[n * 4u]);
        sp = sp + 2u;
    }
    return best;
}
float attr(uint t, uint k, float3 b) {
    return A[t * 16u + k] * b.x + A[t * 16u + 5u + k] * b.y + A[t * 16u + 10u + k] * b.z;
}
float3 texel(uint tex, float u, float v) {
    const uint w = TX[tex * 3u + 1u];
    const uint h = TX[tex * 3u + 2u];
    const uint tx = uint(int(floor(u * float(w)))) & (w - 1u);
    const uint ty = uint(int(floor(v * float(h)))) & (h - 1u);
    const uint c = TX[TX[tex * 3u] + ty * w + tx];
    return float3(float(c & 255u), float((c >> 8u) & 255u), float((c >> 16u) & 255u));
}
float3 offset_p(float3 p, float3 ng, float3 dir) {
    const float e = 2e-4f * (1.0f + max(abs(p.x), max(abs(p.y), abs(p.z))));
    return p + ng * ((dot(ng, dir) > 0.0f) ? (e) : (-e));
}
float3 cam_dir(float px, float py, float4 eye, float4 fwd, float4 side, float4 up) {
    const float nx = px / float(P.w) * 2.0f - 1.0f;
    const float ny = 1.0f - py / float(P.h) * 2.0f;
    return normalize(fwd.xyz + side.xyz * (nx * eye.w * fwd.w) + up.xyz * (ny * eye.w));
}

[numthreads(8, 8, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    if (gid.x >= P.w || gid.y >= P.h) { return; }
    const uint px = gid.y * P.w + gid.x;
    const uint o = px * 16u;
    if ((P.flags & F_FIRST) != 0u) {
        for (uint z = 0u; z < 16u; z++) { ACC[o + z] = 0.0f; }
        ACC[o + 15u] = -1.0f;
        const float3 cd = cam_dir(float(gid.x) + 0.5f, float(gid.y) + 0.5f, P.eye, P.fwd, P.side, P.up);
        const float4 ch = trace(P.eye.xyz, cd, BIG, false);
        if (ch.w >= 0.0f) {
            const float3 hp = P.eye.xyz + cd * ch.x;
            ACC[o + 12u] = dot(hp - P.eye.xyz, P.fwd.xyz);
            ACC[o + 15u] = ch.w;
            const float3 v = hp - P.peye.xyz;
            const float z = dot(v, P.pfwd.xyz);
            const float nx = dot(v, P.pside.xyz) / (z * P.peye.w * P.pfwd.w);
            const float ny = dot(v, P.pup.xyz) / (z * P.peye.w);
            ACC[o + 13u] = (nx * 0.5f + 0.5f) * float(P.w) - (float(gid.x) + 0.5f);
            ACC[o + 14u] = (1.0f - (ny * 0.5f + 0.5f)) * float(P.h) - (float(gid.y) + 0.5f);
        }
    }
    const bool dropCos = (P.flags & F_DROPCOS) != 0u;
    const bool misOne = (P.flags & F_MISONE) != 0u;
    for (uint k = 0u; k < P.sppCount; k++) {
        const uint smp = P.sppBegin + k;
        float2 j = ((float2)(0.5f));
        if ((P.flags & F_JITTER) != 0u) { j = rand2(P.seedLo, P.seedHi, px, smp, 0u); }
        float3 ro = P.eye.xyz;
        float3 rd = cam_dir(float(gid.x) + j.x, float(gid.y) + j.y, P.eye, P.fwd, P.side, P.up);
        float3 tp = ((float3)(1.0f));
        float3 l = ((float3)(0.0f));
        float prevPdf = 0.0f;
        for (uint b = 0u; b <= P.maxBounces; b++) {
            const float4 h = trace(ro, rd, BIG, false);
            if (h.w < 0.0f) {
                l = l + tp * P.sky.xyz;
                break;
            }
            const uint t = uint(h.w);
            const float3 bc = float3(1.0f - h.y - h.z, h.y, h.z);
            const float3 p = ro + rd * h.x;
            float3 ng = normalize(cross(vtx(t, 1u) - vtx(t, 0u), vtx(t, 2u) - vtx(t, 0u)));
            float3 n = normalize(float3(attr(t, 2u, bc), attr(t, 3u, bc), attr(t, 4u, bc)));
            const uint tex = uint(A[t * 16u + 15u]);
            const uint mb = tex * 8u;
            const float3 base = texel(tex, attr(t, 0u, bc), attr(t, 1u, bc)) * (M[mb] / 255.0f);
            if (dot(ng, rd) > 0.0f) { ng = -ng; }
            if (dot(n, ng) < 0.0f) { n = -n; }
            if (b == 0u) {
                ACC[o + 6u] = ACC[o + 6u] + base.x; ACC[o + 7u] = ACC[o + 7u] + base.y; ACC[o + 8u] = ACC[o + 8u] + base.z;
                ACC[o + 9u] = ACC[o + 9u] + n.x; ACC[o + 10u] = ACC[o + 10u] + n.y; ACC[o + 11u] = ACC[o + 11u] + n.z;
            }
            const float3 le = float3(M[mb + 4u], M[mb + 5u], M[mb + 6u]);
            if (max(le.x, max(le.y, le.z)) > 0.0f) {
                float w = 1.0f;
                if (b > 0u && !misOne) {
                    const float pl = h.x * h.x / (abs(dot(ng, rd)) * P.emitterArea);
                    w = prevPdf * prevPdf / (prevPdf * prevPdf + pl * pl);
                }
                l = l + tp * le * w;
            }
            if (b == P.maxBounces) { break; }
            const float3 tb = basis_t(n);
            const float3 bb = basis_b(n);
            const float3 wo = float3(dot(-rd, tb), dot(-rd, bb), dot(-rd, n));
            if (wo.z <= 0.0f) { break; }
            const float rough = M[mb + 1u];
            const float metal = M[mb + 2u];
            const float spec = M[mb + 3u];
            const uint dim = 2u + b * 4u;
            // Next-event estimation: the sun, then one emitter sample.
            if (P.sun.w > 0.0f) {
                const float3 ls = P.sun.xyz;
                const float4 es = eval_bsdf(base, rough, metal, spec, wo, float3(dot(ls, tb), dot(ls, bb), dot(ls, n)), dropCos);
                if (max(es.x, max(es.y, es.z)) > 0.0f) {
                    if (trace(offset_p(p, ng, ls), ls, BIG, true).w < 0.0f) { l = l + tp * es.xyz * P.sunIrr.xyz; }
                }
            }
            if (P.emitters > 0u) {
                const float2 ra = rand2(P.seedLo, P.seedHi, px, smp, dim + 2u);
                const float2 rb = rand2(P.seedLo, P.seedHi, px, smp, dim + 3u);
                const float want = ra.x * P.emitterArea;
                uint lo = 0u;
                uint hi = P.emitters;
                for (uint it = 0u; it < 32u; it++) {
                    if (lo >= hi) { break; }
                    const uint mid = (lo + hi) / 2u;
                    if (M[P.emitterOffset + mid * 2u + 1u] <= want) { lo = mid + 1u; } else { hi = mid; }
                }
                const uint et = uint(M[P.emitterOffset + min(lo, P.emitters - 1u) * 2u]);
                const float su = sqrt(ra.y);
                const float3 q = vtx(et, 0u) * (1.0f - su) + vtx(et, 1u) * (su * (1.0f - rb.x)) + vtx(et, 2u) * (su * rb.x);
                const float3 to = q - p;
                const float dist = length(to);
                const float3 wl = to * (1.0f / dist);
                const float cosL = abs(dot(normalize(cross(vtx(et, 1u) - vtx(et, 0u), vtx(et, 2u) - vtx(et, 0u))), wl));
                if (cosL > 0.0f) {
                    const float pl = dist * dist / (cosL * P.emitterArea);
                    const float4 ee = eval_bsdf(base, rough, metal, spec, wo, float3(dot(wl, tb), dot(wl, bb), dot(wl, n)), dropCos);
                    if (max(ee.x, max(ee.y, ee.z)) > 0.0f && trace(offset_p(p, ng, wl), wl, dist * (1.0f - 1e-3f), true).w < 0.0f) {
                        float wm = 1.0f;
                        if (!misOne) { wm = pl * pl / (pl * pl + ee.w * ee.w); }
                        const uint em = uint(A[et * 16u + 15u]) * 8u;
                        l = l + tp * ee.xyz * float3(M[em + 4u], M[em + 5u], M[em + 6u]) * (wm / pl);
                    }
                }
            }
            // BSDF sampling.
            const float2 u = rand2(P.seedLo, P.seedHi, px, smp, dim);
            const float2 r = rand2(P.seedLo, P.seedHi, px, smp, dim + 1u);
            const float4 s = sample_bsdf(rough, metal, spec, wo, r.x, u.x, u.y);
            if (s.w <= 0.0f) { break; }
            const float4 e = eval_bsdf(base, rough, metal, spec, wo, s.xyz, dropCos);
            if (e.w <= 0.0f) { break; }
            tp = tp * e.xyz * (1.0f / e.w);
            prevPdf = e.w;
            if ((P.flags & F_RR) != 0u && b >= 3u) {
                const float qq = min(0.95f, max(tp.x, max(tp.y, tp.z)));
                if (r.y >= qq) { break; }
                tp = tp * (1.0f / qq);
            }
            const float3 wi = tb * s.x + bb * s.y + n * s.z;
            ro = offset_p(p, ng, wi);
            rd = wi;
        }
        ACC[o] = ACC[o] + l.x; ACC[o + 1u] = ACC[o + 1u] + l.y; ACC[o + 2u] = ACC[o + 2u] + l.z;
        const float y = lum(l);
        const float cnt = ACC[o + 3u] + 1.0f;
        const float dl = y - ACC[o + 4u];
        ACC[o + 3u] = cnt;
        ACC[o + 4u] = ACC[o + 4u] + dl / cnt;
        ACC[o + 5u] = ACC[o + 5u] + dl * (y - ACC[o + 4u]);
    }
}
