// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/common.wgsl and passes.wgsl. Do not edit.
// WGSL sha256 ee2eabebbbb369d4f8e477e75c67866c2a55e659c088e23c2e1620c142863703
// Pass: raster

// raw-native GPU passes: definitions shared by every pass.
// This WGSL is the one shader source. WebGPU runs it as written; the D3D12
// backend runs src/renderer/gpu/shaders/hlsl/, which scripts/wgsl_to_hlsl.py generates from it
// (CI fails when the two differ). The translator needs every let and var to
// carry an explicit type.
// Each function mirrors one C++ function in src/ line for line, with the same
// operation order, so the GPU computes the same float32 expressions as the CPU
// reference. Shader compilers may still fuse or reorder; the reconcile
// certificate (raw/renderer/gpu_reconcile.hpp) measures what that costs.

struct Params {
    float4 vp[4]; // current view-projection, rows (raw/math/mat.hpp is row-major)
    float4 pvp[4]; // previous view-projection, rows
    float4 light; // xyz direction, w intensity
    float4 misc; // x AO radius (world), y SSAO pixel radius
    uint w; uint h; uint ntri; uint rt_samples;
    uint ss_samples; uint rtao; uint pad0; uint pad1;
};

// Triangle input: 24 floats each. 0..8 world positions a,b,c; 9..17 normals; 18..20 albedo.
static const uint TRI_STRIDE = 24u;
// Triangle setup output: 16 floats each.
// 0 valid, 1..3 screen x, 4..6 screen y, 7..9 view distance, 10..12 1/w, 13 area,
// 14 unused, 15 unused. Integer bounds live in the parallel u32 array (4 per triangle).
static const uint SETUP_STRIDE = 16u;

// Rasterization (src/renderer/raster.cpp, the per-pixel half): every triangle in scene
// order, the same edge functions, the same strict depth test, perspective-correct
// position and normal. One invocation per pixel, so no atomics are needed and
// draw order is the CPU's.
ConstantBuffer<Params> P : register(b0);
RWStructuredBuffer<float> tris : register(u1);
RWStructuredBuffer<float> setupF : register(u2);
RWStructuredBuffer<int> setupI : register(u3);
RWStructuredBuffer<float> depth : register(u4);
RWStructuredBuffer<float4> position : register(u5);
RWStructuredBuffer<float4> normal : register(u6);
RWStructuredBuffer<float4> albedoMask : register(u7); // xyz albedo, w mask

float vlen(float3 v) { return sqrt(v.x * v.x + v.y * v.y + v.z * v.z); }
// raw::normalize: l > 0 ? v * (1/l) : v
float3 vnorm(float3 v) {
    const float l = vlen(v);
    if (l > 0.0f) { const float s = 1.0f / l; return float3(v.x * s, v.y * s, v.z * s); }
    return v;
}
float3 vcross(float3 a, float3 b) {
    return float3(a.y * b.z - a.z * b.y, a.z * b.x - a.x * b.z, a.x * b.y - a.y * b.x);
}
float vdot(float3 a, float3 b) { return a.x * b.x + a.y * b.y + a.z * b.z; }
// raw::mul(Mat4, Vec4), row by row, left to right.
float mrow(float4 r, float4 v) { return r.x * v.x + r.y * v.y + r.z * v.z + r.w * v.w; }
float4 mmul(float4 m[4], float4 v) {
    return float4(mrow(m[0], v), mrow(m[1], v), mrow(m[2], v), mrow(m[3], v));
}
// The deterministic per-pixel hash of src/renderer/ssao.cpp and src/renderer/ray_ao.cpp.
float hash01(uint x, uint y, uint s) {
    uint h = x * 374761393u + y * 668265263u + s * 2246822519u;
    h = (h ^ (h >> 13u)) * 1274126177u;
    h = h ^ (h >> 16u);
    return float(h & 0xFFFFFFu) / 16777216.0f;
}
// std::lround: halves round away from zero (WGSL round() rounds halves to even).
int lround(float v) {
    if (v >= 0.0f) { return int(floor(v + 0.5f)); }
    return -int(floor(-v + 0.5f));
}
uint pix(uint x, uint y) { return y * P.w + x; }

[numthreads(8, 8, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    if (gid.x >= P.w || gid.y >= P.h) { return; }
    const int x = int(gid.x); const int y = int(gid.y);
    float best = 3.40282347e+38f; // largest f32; WGSL has no infinity. The host writes +inf for uncovered pixels.
    float3 pos = ((float3)(0.0f)); float3 nrm = ((float3)(0.0f)); float3 alb = ((float3)(0.0f)); float covered = 0.0f;
    const float px = float(x) + 0.5f; const float py = float(y) + 0.5f;
    for (uint t = 0u; t < P.ntri; t++) {
        const uint o = t * SETUP_STRIDE;
        if (setupF[o] == 0.0f) { continue; }
        const uint oi = t * 4u;
        if (x < setupI[oi] || x > setupI[oi + 1u] || y < setupI[oi + 2u] || y > setupI[oi + 3u]) { continue; }
        const float2 s0 = float2(setupF[o + 1u], setupF[o + 4u]);
        const float2 s1 = float2(setupF[o + 2u], setupF[o + 5u]);
        const float2 s2 = float2(setupF[o + 3u], setupF[o + 6u]);
        const float area = setupF[o + 13u];
        const float w0 = ((s1.x - px) * (s2.y - py) - (s1.y - py) * (s2.x - px)) / area;
        const float w1 = ((s2.x - px) * (s0.y - py) - (s2.y - py) * (s0.x - px)) / area;
        const float w2 = 1.0f - w0 - w1;
        if (w0 < 0.0f || w1 < 0.0f || w2 < 0.0f) { continue; }
        const float i0 = setupF[o + 10u]; const float i1 = setupF[o + 11u]; const float i2 = setupF[o + 12u];
        const float iw = w0 * i0 + w1 * i1 + w2 * i2;
        const float d = w0 * setupF[o + 7u] + w1 * setupF[o + 8u] + w2 * setupF[o + 9u];
        if (d >= best) { continue; }
        const uint b = t * TRI_STRIDE;
        float pc[6] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
        for (uint c = 0u; c < 6u; c++) {
            // c < 3: position component c (tri floats 0..8); c >= 3: normal component c-3 (9..17)
            const uint base = ((c < 3u) ? (b + c) : (b + 9u + (c - 3u)));
            pc[c] = (w0 * tris[base] * i0 + w1 * tris[base + 3u] * i1 + w2 * tris[base + 6u] * i2) / iw;
        }
        best = d;
        pos = float3(pc[0], pc[1], pc[2]);
        nrm = vnorm(float3(pc[3], pc[4], pc[5]));
        alb = float3(tris[b + 18u], tris[b + 19u], tris[b + 20u]);
        covered = 1.0f;
    }
    const uint i = pix(gid.x, gid.y);
    depth[i] = best;
    position[i] = float4(pos, 0.0f);
    normal[i] = float4(nrm, 0.0f);
    albedoMask[i] = float4(alb, covered);
}
