// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/rt.wgsl. Do not edit.
// WGSL sha256 cd3acdcace9cfcf57f877947265290e24f5e21148b70a95c05651dc3c909a114
// Pass: rt_bounds_chunk

// raw-native's ray-tracing passes (RT stage R2): the compute PLOC build of
// src/renderer/rt_bvh.cpp, in the same float32 operation order, and BVH traversal. No
// atomics: the sort is bitonic, node ids and survivor positions come from prefix sums, so the
// tree does not depend on scheduling.
//
// Buffers: T triangles (9 floats each, input order); NI nodes (left, right, tri, pad; a leaf
// has tri >= 0); NB node boxes (lo xyz, hi xyz, pad 2); K, V sort keys (code, triangle);
// C cluster node ids; NN nearest neighbours; S prefix sums; G globals.

struct RtParams {
    uint n; uint m; uint radius; uint nextId;
    uint k; uint j; uint count; uint mode;
    float farScale; float pad0; float pad1; float pad2;
};
static const float BIG = 3.40282347e+38f; // FLT_MAX exactly
static const uint CHUNK = 256u;

// One invocation per chunk of 256 triangles: the centroid box of the chunk into G
// (6 floats a chunk, from G[8]).
ConstantBuffer<RtParams> P : register(b0);
RWStructuredBuffer<float> T : register(u1);
RWStructuredBuffer<float> G : register(u2);

float box_area(float lx, float ly, float lz, float hx, float hy, float hz) {
    const float dx = hx - lx;
    const float dy = hy - ly;
    const float dz = hz - lz;
    return 2.0f * (dy * (dx + dz) + dz * dx); // the CPU's factored form (rt_bvh.cpp)
}
uint spread(uint v0) {
    uint v = v0;
    v = (v | (v << 16u)) & 0x030000FFu;
    v = (v | (v << 8u)) & 0x0300F00Fu;
    v = (v | (v << 4u)) & 0x030C30C3u;
    v = (v | (v << 2u)) & 0x09249249u;
    return v;
}

[numthreads(64, 1, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    const uint c = gid.x;
    if (c * CHUNK >= P.n) { return; }
    float3 lo = ((float3)(BIG));
    float3 hi = ((float3)(-BIG));
    const uint end = min(P.n, (c + 1u) * CHUNK);
    for (uint i = c * CHUNK; i < end; i++) {
        const uint b = i * 9u;
        const float third = 0.333333343f;
        const float x = (T[b] + T[b + 3u] + T[b + 6u]) * third;
        const float y = (T[b + 1u] + T[b + 4u] + T[b + 7u]) * third;
        const float z = (T[b + 2u] + T[b + 5u] + T[b + 8u]) * third;
        lo = min(lo, float3(x, y, z));
        hi = max(hi, float3(x, y, z));
    }
    const uint o = 8u + c * 6u;
    G[o] = lo.x; G[o + 1u] = lo.y; G[o + 2u] = lo.z; G[o + 3u] = hi.x; G[o + 4u] = hi.y; G[o + 5u] = hi.z;
}
