// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/rt.wgsl. Do not edit.
// WGSL sha256 cd3acdcace9cfcf57f877947265290e24f5e21148b70a95c05651dc3c909a114
// Pass: rt_bounds_final

// raw-native's ray-tracing passes (RT stage R2): the compute PLOC build of
// src/renderer/rt_bvh.cpp, in the same float32 operation order, and BVH traversal. No
// atomics: the sort is bitonic, node ids and survivor positions come from prefix sums, so the
// tree does not depend on scheduling.
//
// Buffers: T triangles (9 floats each, input order); NI nodes (left, right, tri, pad; a leaf
// has tri >= 0); NB node boxes (lo xyz, hi xyz, pad 2); K, V sort keys (code, triangle);
// C cluster node ids; NN nearest neighbours; S prefix sums; G globals.

struct RtParams {
    uint n; uint m; uint radius; uint nextId;
    uint k; uint j; uint count; uint mode;
    float farScale; float pad0; float pad1; float pad2;
};
static const float BIG = 3.40282347e+38f; // FLT_MAX exactly
static const uint CHUNK = 256u;

// One invocation: the chunks' boxes into G[0..2] (lo) and the power-of-two scale G[3].
ConstantBuffer<RtParams> P : register(b0);
RWStructuredBuffer<float> G : register(u1);

float box_area(float lx, float ly, float lz, float hx, float hy, float hz) {
    const float dx = hx - lx;
    const float dy = hy - ly;
    const float dz = hz - lz;
    return 2.0f * (dy * (dx + dz) + dz * dx); // the CPU's factored form (rt_bvh.cpp)
}
uint spread(uint v0) {
    uint v = v0;
    v = (v | (v << 16u)) & 0x030000FFu;
    v = (v | (v << 8u)) & 0x0300F00Fu;
    v = (v | (v << 4u)) & 0x030C30C3u;
    v = (v | (v << 2u)) & 0x09249249u;
    return v;
}

[numthreads(1, 1, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    if (gid.x != 0u) { return; }
    float3 lo = ((float3)(BIG));
    float3 hi = ((float3)(-BIG));
    const uint chunks = (P.n + CHUNK - 1u) / CHUNK;
    for (uint c = 0u; c < chunks; c++) {
        const uint o = 8u + c * 6u;
        lo = min(lo, float3(G[o], G[o + 1u], G[o + 2u]));
        hi = max(hi, float3(G[o + 3u], G[o + 4u], G[o + 5u]));
    }
    const float extent = max(hi.x - lo.x, max(hi.y - lo.y, hi.z - lo.z));
    float s = 1.0f;
    if (extent > 0.0f) {
        for (uint a = 0u; a < 300u; a++) {
            if (extent * s > 1.0f) { s = s * 0.5f; } else { break; }
        }
        for (uint b = 0u; b < 300u; b++) {
            if (extent * s <= 0.5f) { s = s * 2.0f; } else { break; }
        }
    }
    G[0] = lo.x; G[1] = lo.y; G[2] = lo.z; G[3] = s;
}
