// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/rt.wgsl. Do not edit.
// WGSL sha256 cd3acdcace9cfcf57f877947265290e24f5e21148b70a95c05651dc3c909a114
// Pass: rt_ploc_nn

// raw-native's ray-tracing passes (RT stage R2): the compute PLOC build of
// src/renderer/rt_bvh.cpp, in the same float32 operation order, and BVH traversal. No
// atomics: the sort is bitonic, node ids and survivor positions come from prefix sums, so the
// tree does not depend on scheduling.
//
// Buffers: T triangles (9 floats each, input order); NI nodes (left, right, tri, pad; a leaf
// has tri >= 0); NB node boxes (lo xyz, hi xyz, pad 2); K, V sort keys (code, triangle);
// C cluster node ids; NN nearest neighbours; S prefix sums; G globals.

struct RtParams {
    uint n; uint m; uint radius; uint nextId;
    uint k; uint j; uint count; uint mode;
    float farScale; float pad0; float pad1; float pad2;
};
static const float BIG = 3.40282347e+38f; // FLT_MAX exactly
static const uint CHUNK = 256u;

// One invocation per cluster (P.m): its nearest neighbour within P.radius positions by the
// surface area of the merged box, ties to the lower position.
ConstantBuffer<RtParams> P : register(b0);
RWStructuredBuffer<float> NB : register(u1);
RWStructuredBuffer<uint> C : register(u2);
RWStructuredBuffer<uint> NN : register(u3);

float box_area(float lx, float ly, float lz, float hx, float hy, float hz) {
    const float dx = hx - lx;
    const float dy = hy - ly;
    const float dz = hz - lz;
    return 2.0f * (dy * (dx + dz) + dz * dx); // the CPU's factored form (rt_bvh.cpp)
}
uint spread(uint v0) {
    uint v = v0;
    v = (v | (v << 16u)) & 0x030000FFu;
    v = (v | (v << 8u)) & 0x0300F00Fu;
    v = (v | (v << 4u)) & 0x030C30C3u;
    v = (v | (v << 2u)) & 0x09249249u;
    return v;
}

[numthreads(64, 1, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    const uint i = gid.x;
    if (i >= P.m) { return; }
    const uint a = C[i] * 8u;
    const uint first = ((i > P.radius) ? (i - P.radius) : (0u));
    const uint last = min(P.m - 1u, i + P.radius);
    float best = BIG;
    uint nn = i;
    for (uint j = first; j <= last; j++) {
        if (j == i) { continue; }
        const uint b = C[j] * 8u;
        const float d = box_area(min(NB[a], NB[b]), min(NB[a + 1u], NB[b + 1u]), min(NB[a + 2u], NB[b + 2u]), max(NB[a + 3u], NB[b + 3u]), max(NB[a + 4u], NB[b + 4u]), max(NB[a + 5u], NB[b + 5u]));
        if (d < best) {
            best = d;
            nn = j;
        }
    }
    NN[i] = nn;
}
