// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/rt.wgsl. Do not edit.
// WGSL sha256 cd3acdcace9cfcf57f877947265290e24f5e21148b70a95c05651dc3c909a114
// Pass: rt_ploc_merge

// raw-native's ray-tracing passes (RT stage R2): the compute PLOC build of
// src/renderer/rt_bvh.cpp, in the same float32 operation order, and BVH traversal. No
// atomics: the sort is bitonic, node ids and survivor positions come from prefix sums, so the
// tree does not depend on scheduling.
//
// Buffers: T triangles (9 floats each, input order); NI nodes (left, right, tri, pad; a leaf
// has tri >= 0); NB node boxes (lo xyz, hi xyz, pad 2); K, V sort keys (code, triangle);
// C cluster node ids; NN nearest neighbours; S prefix sums; G globals.

struct RtParams {
    uint n; uint m; uint radius; uint nextId;
    uint k; uint j; uint count; uint mode;
    float farScale; float pad0; float pad1; float pad2;
};
static const float BIG = 3.40282347e+38f; // FLT_MAX exactly
static const uint CHUNK = 256u;

// One invocation per cluster: the lower of a mutual pair makes node P.nextId + S[i] from the
// pair; every survivor lands at SV[i] in D. The last invocation writes the survivor and merge
// counts into W.
ConstantBuffer<RtParams> P : register(b0);
RWStructuredBuffer<uint> NN : register(u1);
RWStructuredBuffer<uint> C : register(u2);
RWStructuredBuffer<uint> S : register(u3);
RWStructuredBuffer<uint> SV : register(u4);
RWStructuredBuffer<int> NI : register(u5);
RWStructuredBuffer<float> NB : register(u6);
RWStructuredBuffer<uint> D : register(u7);

float box_area(float lx, float ly, float lz, float hx, float hy, float hz) {
    const float dx = hx - lx;
    const float dy = hy - ly;
    const float dz = hz - lz;
    return 2.0f * (dy * (dx + dz) + dz * dx); // the CPU's factored form (rt_bvh.cpp)
}
uint spread(uint v0) {
    uint v = v0;
    v = (v | (v << 16u)) & 0x030000FFu;
    v = (v | (v << 8u)) & 0x0300F00Fu;
    v = (v | (v << 4u)) & 0x030C30C3u;
    v = (v | (v << 2u)) & 0x09249249u;
    return v;
}

[numthreads(64, 1, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    const uint i = gid.x;
    if (i >= P.m) { return; }
    const uint j = NN[i];
    const bool mutual = NN[j] == i;
    const bool merges = mutual && i < j;
    const bool survives = !(mutual && i > j);
    if (i == P.m - 1u) {
        D[P.m] = SV[i] + ((survives) ? (1u) : (0u));
        D[P.m + 1u] = S[i] + ((merges) ? (1u) : (0u));
    }
    if (!survives) { return; }
    if (!merges) {
        D[SV[i]] = C[i];
        return;
    }
    const uint id = P.nextId + S[i];
    const uint a = C[i];
    const uint b = C[j];
    NI[id * 4u] = int(a); NI[id * 4u + 1u] = int(b); NI[id * 4u + 2u] = -1; NI[id * 4u + 3u] = 0;
    for (uint k = 0u; k < 3u; k++) {
        NB[id * 8u + k] = min(NB[a * 8u + k], NB[b * 8u + k]);
        NB[id * 8u + 3u + k] = max(NB[a * 8u + 3u + k], NB[b * 8u + 3u + k]);
    }
    D[SV[i]] = id;
}
