// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/rt.wgsl. Do not edit.
// WGSL sha256 cd3acdcace9cfcf57f877947265290e24f5e21148b70a95c05651dc3c909a114
// Pass: rt_trace

// raw-native's ray-tracing passes (RT stage R2): the compute PLOC build of
// src/renderer/rt_bvh.cpp, in the same float32 operation order, and BVH traversal. No
// atomics: the sort is bitonic, node ids and survivor positions come from prefix sums, so the
// tree does not depend on scheduling.
//
// Buffers: T triangles (9 floats each, input order); NI nodes (left, right, tri, pad; a leaf
// has tri >= 0); NB node boxes (lo xyz, hi xyz, pad 2); K, V sort keys (code, triangle);
// C cluster node ids; NN nearest neighbours; S prefix sums; G globals.

struct RtParams {
    uint n; uint m; uint radius; uint nextId;
    uint k; uint j; uint count; uint mode;
    float farScale; float pad0; float pad1; float pad2;
};
static const float BIG = 3.40282347e+38f; // FLT_MAX exactly
static const uint CHUNK = 256u;

// One invocation per ray (R: origin, direction, tMax, pad): closest hit (P.mode 0) or any hit
// (1) through the tree rooted at P.nextId. O: t (or -1), the triangle (-1 none, -2 stack
// overflow) as a float-exact integer, and the steps taken. The slab exit is widened by
// P.farScale (1 + 2 gamma(3), Ize 2013; the control shortens it).
ConstantBuffer<RtParams> P : register(b0);
RWStructuredBuffer<int> NI : register(u1);
RWStructuredBuffer<float> NB : register(u2);
RWStructuredBuffer<float> T : register(u3);
RWStructuredBuffer<float> R : register(u4);
RWStructuredBuffer<float> O : register(u5);

float box_area(float lx, float ly, float lz, float hx, float hy, float hz) {
    const float dx = hx - lx;
    const float dy = hy - ly;
    const float dz = hz - lz;
    return 2.0f * (dy * (dx + dz) + dz * dx); // the CPU's factored form (rt_bvh.cpp)
}
uint spread(uint v0) {
    uint v = v0;
    v = (v | (v << 16u)) & 0x030000FFu;
    v = (v | (v << 8u)) & 0x0300F00Fu;
    v = (v | (v << 4u)) & 0x030C30C3u;
    v = (v | (v << 2u)) & 0x09249249u;
    return v;
}

float inv_dir(float x) {
    if (x != 0.0f) { return 1.0f / x; }
    return ((x >= 0.0f) ? (BIG) : (-BIG));
}

// Moeller-Trumbore in raw/math/primitives.hpp's operation order; x: t, y: 1 when hit.
float2 hit_tri(uint t, float ox, float oy, float oz, float dx, float dy, float dz) {
    const uint b = t * 9u;
    const float e1x = T[b + 3u] - T[b];
    const float e1y = T[b + 4u] - T[b + 1u];
    const float e1z = T[b + 5u] - T[b + 2u];
    const float e2x = T[b + 6u] - T[b];
    const float e2y = T[b + 7u] - T[b + 1u];
    const float e2z = T[b + 8u] - T[b + 2u];
    const float px = dy * e2z - dz * e2y;
    const float py = dz * e2x - dx * e2z;
    const float pz = dx * e2y - dy * e2x;
    const float det = e1x * px + e1y * py + e1z * pz;
    if (det > -1e-7f && det < 1e-7f) { return float2(0.0f, 0.0f); }
    const float inv = 1.0f / det;
    const float tx = ox - T[b];
    const float ty = oy - T[b + 1u];
    const float tz = oz - T[b + 2u];
    const float u = (tx * px + ty * py + tz * pz) * inv;
    if (u < 0.0f || u > 1.0f) { return float2(0.0f, 0.0f); }
    const float qx = ty * e1z - tz * e1y;
    const float qy = tz * e1x - tx * e1z;
    const float qz = tx * e1y - ty * e1x;
    const float v = (dx * qx + dy * qy + dz * qz) * inv;
    if (v < 0.0f || u + v > 1.0f) { return float2(0.0f, 0.0f); }
    const float tt = (e2x * qx + e2y * qy + e2z * qz) * inv;
    return float2(tt, ((tt > 1e-4f) ? (1.0f) : (0.0f)));
}

[numthreads(64, 1, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    const uint r = gid.x;
    if (r >= P.count) { return; }
    const float ox = R[r * 8u];
    const float oy = R[r * 8u + 1u];
    const float oz = R[r * 8u + 2u];
    const float dx = R[r * 8u + 3u];
    const float dy = R[r * 8u + 4u];
    const float dz = R[r * 8u + 5u];
    const float ix = inv_dir(dx);
    const float iy = inv_dir(dy);
    const float iz = inv_dir(dz);
    float best = R[r * 8u + 6u];
    int tri = -1;
    uint steps = 0u;
    uint stack[64] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    uint sp = 1u;
    stack[0] = P.nextId;
    for (uint guard = 0u; guard < 1000000u; guard++) {
        if (sp == 0u) { break; }
        sp = sp - 1u;
        const uint n = stack[sp];
        steps = steps + 1u;
        const float a0 = (NB[n * 8u] - ox) * ix;
        const float b0 = (NB[n * 8u + 3u] - ox) * ix;
        const float a1 = (NB[n * 8u + 1u] - oy) * iy;
        const float b1 = (NB[n * 8u + 4u] - oy) * iy;
        const float a2 = (NB[n * 8u + 2u] - oz) * iz;
        const float b2 = (NB[n * 8u + 5u] - oz) * iz;
        const float t0 = max(max(max(0.0f, min(a0, b0)), min(a1, b1)), min(a2, b2));
        const float t1 = min(min(min(best, max(a0, b0)), max(a1, b1)), max(a2, b2));
        if (!(t0 <= t1 * P.farScale)) { continue; }
        const int leaf = NI[n * 4u + 2u];
        if (leaf >= 0) {
            const float2 h = hit_tri(uint(leaf), ox, oy, oz, dx, dy, dz);
            if (h.y > 0.0f && (h.x < best || (tri >= 0 && h.x == best && leaf < tri))) {
                best = h.x;
                tri = leaf;
                if (P.mode == 1u) { break; }
            }
            continue;
        }
        if (sp + 2u > 64u) {
            tri = -2;
            break;
        }
        stack[sp] = uint(NI[n * 4u + 1u]);
        stack[sp + 1u] = uint(NI[n * 4u]);
        sp = sp + 2u;
    }
    O[r * 4u] = ((tri >= 0) ? (best) : (-1.0f));
    O[r * 4u + 1u] = float(tri);
    O[r * 4u + 2u] = float(steps);
    O[r * 4u + 3u] = 0.0f;
}
