// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/common.wgsl and passes.wgsl. Do not edit.
// WGSL sha256 ee2eabebbbb369d4f8e477e75c67866c2a55e659c088e23c2e1620c142863703
// Pass: rtao

// raw-native GPU passes: definitions shared by every pass.
// This WGSL is the one shader source. WebGPU runs it as written; the D3D12
// backend runs src/renderer/gpu/shaders/hlsl/, which scripts/wgsl_to_hlsl.py generates from it
// (CI fails when the two differ). The translator needs every let and var to
// carry an explicit type.
// Each function mirrors one C++ function in src/ line for line, with the same
// operation order, so the GPU computes the same float32 expressions as the CPU
// reference. Shader compilers may still fuse or reorder; the reconcile
// certificate (raw/renderer/gpu_reconcile.hpp) measures what that costs.

struct Params {
    float4 vp[4]; // current view-projection, rows (raw/math/mat.hpp is row-major)
    float4 pvp[4]; // previous view-projection, rows
    float4 light; // xyz direction, w intensity
    float4 misc; // x AO radius (world), y SSAO pixel radius
    uint w; uint h; uint ntri; uint rt_samples;
    uint ss_samples; uint rtao; uint pad0; uint pad1;
};

// Triangle input: 24 floats each. 0..8 world positions a,b,c; 9..17 normals; 18..20 albedo.
static const uint TRI_STRIDE = 24u;
// Triangle setup output: 16 floats each.
// 0 valid, 1..3 screen x, 4..6 screen y, 7..9 view distance, 10..12 1/w, 13 area,
// 14 unused, 15 unused. Integer bounds live in the parallel u32 array (4 per triangle).
static const uint SETUP_STRIDE = 16u;

// Ray-traced AO reference (src/renderer/ray_ao.cpp with src/renderer/accel.cpp and the
// Moller-Trumbore test in raw/math/primitives.hpp).
ConstantBuffer<Params> P : register(b0);
RWStructuredBuffer<float> tris : register(u1);
RWStructuredBuffer<float4> position : register(u2);
RWStructuredBuffer<float4> normal : register(u3);
RWStructuredBuffer<float4> albedoMask : register(u4);
RWStructuredBuffer<float> aoRT : register(u5);

float vlen(float3 v) { return sqrt(v.x * v.x + v.y * v.y + v.z * v.z); }
// raw::normalize: l > 0 ? v * (1/l) : v
float3 vnorm(float3 v) {
    const float l = vlen(v);
    if (l > 0.0f) { const float s = 1.0f / l; return float3(v.x * s, v.y * s, v.z * s); }
    return v;
}
float3 vcross(float3 a, float3 b) {
    return float3(a.y * b.z - a.z * b.y, a.z * b.x - a.x * b.z, a.x * b.y - a.y * b.x);
}
float vdot(float3 a, float3 b) { return a.x * b.x + a.y * b.y + a.z * b.z; }
// raw::mul(Mat4, Vec4), row by row, left to right.
float mrow(float4 r, float4 v) { return r.x * v.x + r.y * v.y + r.z * v.z + r.w * v.w; }
float4 mmul(float4 m[4], float4 v) {
    return float4(mrow(m[0], v), mrow(m[1], v), mrow(m[2], v), mrow(m[3], v));
}
// The deterministic per-pixel hash of src/renderer/ssao.cpp and src/renderer/ray_ao.cpp.
float hash01(uint x, uint y, uint s) {
    uint h = x * 374761393u + y * 668265263u + s * 2246822519u;
    h = (h ^ (h >> 13u)) * 1274126177u;
    h = h ^ (h >> 16u);
    return float(h & 0xFFFFFFu) / 16777216.0f;
}
// std::lround: halves round away from zero (WGSL round() rounds halves to even).
int lround(float v) {
    if (v >= 0.0f) { return int(floor(v + 0.5f)); }
    return -int(floor(-v + 0.5f));
}
uint pix(uint x, uint y) { return y * P.w + x; }

float3 triVert(uint t, uint k) {
    const uint b = t * TRI_STRIDE + 3u * k;
    return float3(tris[b], tris[b + 1u], tris[b + 2u]);
}
bool hit(float3 o, float3 d, uint t, float maxDist) {
    const float3 a = triVert(t, 0u);
    const float3 e1 = triVert(t, 1u) - a;
    const float3 e2 = triVert(t, 2u) - a;
    const float3 p = vcross(d, e2);
    const float det = vdot(e1, p);
    if (det > -1e-7f && det < 1e-7f) { return false; }
    const float inv = 1.0f / det;
    const float3 tv = o - a;
    const float u = vdot(tv, p) * inv;
    if (u < 0.0f || u > 1.0f) { return false; }
    const float3 q = vcross(tv, e1);
    const float v = vdot(d, q) * inv;
    if (v < 0.0f || u + v > 1.0f) { return false; }
    const float dist = vdot(e2, q) * inv;
    return dist > 1e-4f && dist < maxDist;
}

[numthreads(8, 8, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    if (gid.x >= P.w || gid.y >= P.h) { return; }
    const uint i = pix(gid.x, gid.y);
    if (albedoMask[i].w == 0.0f) { aoRT[i] = 1.0f; return; }
    const float3 p = position[i].xyz;
    const float3 n = normal[i].xyz;
    float3 ax = float3(1.0f, 0.0f, 0.0f);
    if (abs(n.x) > 0.9f) { ax = float3(0.0f, 1.0f, 0.0f); }
    const float3 tb = vnorm(vcross(ax, n));
    const float3 bb = vcross(n, tb);
    const float3 origin = p + n * 1e-3f;
    uint open = 0u;
    for (uint s = 0u; s < P.rt_samples; s++) {
        const float u1 = hash01(gid.x, gid.y, 2u * s);
        const float u2 = hash01(gid.x, gid.y, 2u * s + 1u);
        const float r = sqrt(u1);
        const float phi = 6.2831853f * u2;
        const float lx = r * cos(phi);
        const float ly = r * sin(phi);
        const float lz = sqrt(max(0.0f, 1.0f - u1));
        const float3 dir = vnorm(tb * lx + bb * ly + n * lz);
        bool blocked = false;
        for (uint t = 0u; t < P.ntri; t++) {
            if (hit(origin, dir, t, P.misc.x)) { blocked = true; break; }
        }
        if (!blocked) { open++; }
    }
    aoRT[i] = float(open) / float(P.rt_samples);
}
