// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/sdf.wgsl. Do not edit.
// WGSL sha256 298ebcda3c307af916c88771edfe7df93b08ff734dc684c31b1a6278e129efe6
// Pass: sdf_god

// raw-native's ray marcher on the GPU (RT stage R3): the float32 form of
// src/renderer/sdf_eval.cpp and sdf_march.cpp, read with raw/renderer/sdf.hpp. The SDF is a
// postfix program in N (16 floats a node); the evaluator keeps a distance stack and a stack of
// query frames as scalar arrays.

struct SdfParams {
    uint w; uint h; uint nodes; uint flags;
    uint count; uint pad0; uint pad1; uint pad2;
    float tMax; float step; float softK; float fogA;
    float fogB; float fogMax; float near; float far;
    float4 eye; float4 fwd; float4 side; float4 up;
    float4 sun;
};
// flags: 1 force sun visibility to 1 (M5 control), 2 SDF always in front (M6 control)
static const float PI = 3.14159265f;

// One invocation per pixel: single scattering of the sun along the camera ray up to
// min(hit, P.fogMax), 64 midpoint samples, each with a hard SDF shadow ray (P.flags 1: none).
// M: sdf_march's output. O: 4 floats a pixel: in-scatter, clear samples, end distance, pad.
ConstantBuffer<SdfParams> P : register(b0);
RWStructuredBuffer<float> N : register(u1);
RWStructuredBuffer<float> M : register(u2);
RWStructuredBuffer<float> O : register(u3);

float bulb_de(float3 p, int iters, float power) {
    float3 z = p;
    float dr = 1.0f;
    float r = length(z);
    for (int i = 0; i < iters; i++) {
        r = length(z);
        if (r > 2.0f) { break; }
        const float theta = acos(clamp(z.z / r, -1.0f, 1.0f)) * power;
        const float phi = atan2(z.y, z.x) * power;
        dr = pow(r, power - 1.0f) * power * dr + 1.0f;
        const float zr = pow(r, power);
        z = float3(sin(theta) * cos(phi), sin(phi) * sin(theta), cos(theta)) * zr + p;
    }
    r = length(z);
    return 0.5f * log(r) * r / dr;
}
float mandelbox_de(float3 p, int iters, float scale) {
    float3 z = p;
    float dr = 1.0f;
    for (int i = 0; i < iters; i++) {
        z = clamp(z, ((float3)(-1.0f)), ((float3)(1.0f))) * 2.0f - z;
        const float r2 = dot(z, z);
        if (r2 < 0.25f) {
            z = z * 4.0f;
            dr = dr * 4.0f;
        } else {
            if (r2 < 1.0f) {
                const float k = 1.0f / r2;
                z = z * k;
                dr = dr * k;
            }
        }
        z = z * scale + p;
        dr = dr * abs(scale) + 1.0f;
    }
    return length(z) / abs(dr);
}
// Every pass binds P at 0 and the program N at 1, so the shared evaluator below can read N.
float prim(uint b, float3 p) {
    const int op = int(N[b]);
    if (op == 1) { return length(p) - N[b + 2u]; }
    if (op == 2 || op == 3) {
        const float r = ((op == 3) ? (N[b + 5u]) : (0.0f));
        const float3 q = abs(p) - (float3(N[b + 2u], N[b + 3u], N[b + 4u]) - ((float3)(r)));
        return length(max(q, ((float3)(0.0f)))) + min(max(q.x, max(q.y, q.z)), 0.0f) - r;
    }
    if (op == 4) {
        const float a = sqrt(p.x * p.x + p.z * p.z) - N[b + 2u];
        return sqrt(a * a + p.y * p.y) - N[b + 3u];
    }
    if (op == 5) {
        const float3 a = float3(N[b + 2u], N[b + 3u], N[b + 4u]);
        const float3 pa = p - a;
        const float3 ba = float3(N[b + 5u], N[b + 6u], N[b + 7u]) - a;
        const float hh = clamp(dot(pa, ba) / dot(ba, ba), 0.0f, 1.0f);
        return length(pa - ba * hh) - N[b + 8u];
    }
    if (op == 6) {
        const float dx = sqrt(p.x * p.x + p.z * p.z) - N[b + 2u];
        const float dy = abs(p.y) - N[b + 3u];
        return min(max(dx, dy), 0.0f) + sqrt(max(dx, 0.0f) * max(dx, 0.0f) + max(dy, 0.0f) * max(dy, 0.0f));
    }
    if (op == 7) { return p.x * N[b + 2u] + p.y * N[b + 3u] + p.z * N[b + 4u] + N[b + 5u]; }
    if (op == 8) { return bulb_de(p, int(N[b + 2u]), N[b + 3u]); }
    return mandelbox_de(p, int(N[b + 2u]), N[b + 3u]);
}
float rep1(float v, float per) {
    if (per > 0.0f) { return v - per * floor(v / per + 0.5f); }
    return v;
}
// x: distance, y: material.
float2 sdf_eval(float3 q) {
    float sd[16] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
    float sm[16] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
    float fx[16] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
    float fy[16] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
    float fz[16] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
    float fs[16] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
    uint sp = 0u;
    uint fsp = 0u;
    float3 p = q;
    float scale = 1.0f;
    for (uint i = 0u; i < P.nodes; i++) {
        const uint b = i * 16u;
        const int op = int(N[b]);
        if (op < 20) {
            sd[sp] = prim(b, p) * scale;
            sm[sp] = N[b + 1u];
            sp = sp + 1u;
            continue;
        }
        if (op == 30) {
            fx[fsp] = p.x; fy[fsp] = p.y; fz[fsp] = p.z; fs[fsp] = scale;
            fsp = fsp + 1u;
            const float3 d = p - float3(N[b + 11u], N[b + 12u], N[b + 13u]);
            p = float3(N[b + 2u] * d.x + N[b + 3u] * d.y + N[b + 4u] * d.z, N[b + 5u] * d.x + N[b + 6u] * d.y + N[b + 7u] * d.z, N[b + 8u] * d.x + N[b + 9u] * d.y + N[b + 10u] * d.z) * (1.0f / N[b + 14u]);
            scale = scale * N[b + 14u];
            continue;
        }
        if (op == 31) {
            fsp = fsp - 1u;
            p = float3(fx[fsp], fy[fsp], fz[fsp]);
            scale = fs[fsp];
            continue;
        }
        if (op == 32) {
            p = float3(rep1(p.x, N[b + 2u]), rep1(p.y, N[b + 3u]), rep1(p.z, N[b + 4u]));
            continue;
        }
        const float bd = sd[sp - 1u];
        const float bm = sm[sp - 1u];
        const float ad = sd[sp - 2u];
        const float am = sm[sp - 2u];
        sp = sp - 2u;
        float rd = ad;
        float rm = am;
        if (op == 20) {
            if (bd < ad) { rd = bd; rm = bm; }
        } else if (op == 22) {
            rd = max(ad, -bd);
        } else if (op == 23) {
            if (bd > ad) { rd = bd; rm = bm; }
        } else {
            const float k = N[b + 2u];
            const float hh = clamp(0.5f + 0.5f * (bd - ad) / k, 0.0f, 1.0f);
            rd = bd + (ad - bd) * hh - k * hh * (1.0f - hh);
            rm = ((hh > 0.5f) ? (am) : (bm));
        }
        sd[sp] = rd;
        sm[sp] = rm;
        sp = sp + 1u;
    }
    if (sp == 0u) { return float2(1e30f, -1.0f); }
    return float2(sd[sp - 1u], sm[sp - 1u]);
}
float3 sdf_normal(float3 x, float t) {
    const float e = 1e-4f * (1.0f + t);
    const float a = sdf_eval(float3(x.x + e, x.y - e, x.z - e)).x;
    const float b = sdf_eval(float3(x.x - e, x.y - e, x.z + e)).x;
    const float c = sdf_eval(float3(x.x - e, x.y + e, x.z - e)).x;
    const float d = sdf_eval(float3(x.x + e, x.y + e, x.z + e)).x;
    return normalize(float3(a - b - c + d, -a - b + c + d, -a + b - c + d));
}
// Method notes 1 and 2 of evidence/rt-r3-bounds.json: bracket the surface by sign, bisect.
float sdf_refine(float3 o, float3 d, float t, float e) {
    float t2 = t;
    float step = e;
    bool inside = false;
    for (uint k = 0u; k < 64u; k++) {
        if (inside) { break; }
        t2 = t2 + step;
        inside = sdf_eval(o + d * t2).x < 0.0f;
    }
    for (uint k2 = 0u; k2 < 16u; k2++) {
        if (inside) { break; }
        t2 = t2 + step;
        step = step * 2.0f;
        inside = sdf_eval(o + d * t2).x < 0.0f;
    }
    if (!inside) { return t; }
    float a = t;
    float b = t2;
    for (uint i = 0u; i < 24u; i++) {
        const float m = 0.5f * (a + b);
        if (sdf_eval(o + d * m).x > 0.0f) { a = m; } else { b = m; }
    }
    return 0.5f * (a + b);
}
// x: t (-1 a miss), y: material, z: closest d / (1 + t), w: steps.
float4 sdf_march(float3 o, float3 d, float tMax) {
    float t = 0.0f;
    float closest = 1e30f;
    for (uint i = 0u; i < 512u; i++) {
        const float2 s = sdf_eval(o + d * t);
        closest = min(closest, s.x / (1.0f + t));
        if (s.x < 1e-4f * (1.0f + t)) {
            return float4(sdf_refine(o, d, t, 1e-4f * (1.0f + t)), s.y, closest, float(i + 1u));
        }
        t = t + s.x * P.step;
        if (t > tMax) { break; }
    }
    return float4(-1.0f, -1.0f, closest, 512.0f);
}
float soft_shadow(float3 x, float3 l, float k) {
    float res = 1.0f;
    float t = 0.02f;
    for (uint i = 0u; i < 128u; i++) {
        const float h = sdf_eval(x + l * t).x;
        res = min(res, k * h / t);
        if (res < 1e-3f) { return 0.0f; }
        t = t + clamp(h, 0.01f, 0.5f);
        if (t > 30.0f) { break; }
    }
    return clamp(res, 0.0f, 1.0f);
}
float ambient_occlusion(float3 x, float3 n) {
    float occ = 0.0f;
    float sca = 1.0f;
    for (uint i = 0u; i < 5u; i++) {
        const float h = 0.02f + 0.12f * float(i);
        occ = occ + (h - sdf_eval(x + n * h).x) * sca;
        sca = sca * 0.85f;
    }
    return clamp(1.0f - 3.0f * occ, 0.0f, 1.0f);
}
bool hard_shadow(float3 x, float3 l) {
    return sdf_march(x + l * 0.02f, l, 30.0f).x >= 0.0f;
}
float fog_height(float3 o, float3 d, float t) {
    const float base = P.fogA * exp(-P.fogB * o.y);
    const float k = P.fogB * d.y;
    float optical = base * t;
    if (abs(k) >= 1e-9f) { optical = base * (1.0f - exp(-k * t)) / k; }
    return exp(-optical);
}
float3 cam_ray(uint x, uint y) {
    const float nx = (float(x) + 0.5f) / float(P.w) * 2.0f - 1.0f;
    const float ny = 1.0f - (float(y) + 0.5f) / float(P.h) * 2.0f;
    return normalize(P.fwd.xyz + P.side.xyz * (nx * P.eye.w * P.fwd.w) + P.up.xyz * (ny * P.eye.w));
}

[numthreads(8, 8, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    if (gid.x >= P.w || gid.y >= P.h) { return; }
    const uint px = gid.y * P.w + gid.x;
    const float3 d = cam_ray(gid.x, gid.y);
    float tEnd = P.fogMax;
    if (M[px * 8u] >= 0.0f) { tEnd = min(tEnd, M[px * 8u]); }
    const float dt = tEnd / 64.0f;
    const float g = 0.6f;
    const float c = dot(d, P.sun.xyz);
    const float phase = (1.0f - g * g) / (4.0f * PI * pow(1.0f + g * g - 2.0f * g * c, 1.5f));
    float l = 0.0f;
    uint clear = 0u;
    for (uint i = 0u; i < 64u; i++) {
        const float t = (float(i) + 0.5f) * dt;
        const float3 x = P.eye.xyz + d * t;
        if ((P.flags & 1u) == 0u) {
            if (hard_shadow(x, P.sun.xyz)) { continue; }
        }
        clear = clear + 1u;
        l = l + P.fogA * exp(-P.fogB * x.y) * fog_height(P.eye.xyz, d, t) * phase * dt;
    }
    O[px * 4u] = l;
    O[px * 4u + 1u] = float(clear);
    O[px * 4u + 2u] = tEnd;
    O[px * 4u + 3u] = 0.0f;
}
