// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/common.wgsl and passes.wgsl. Do not edit.
// WGSL sha256 ee2eabebbbb369d4f8e477e75c67866c2a55e659c088e23c2e1620c142863703
// Pass: setup

// raw-native GPU passes: definitions shared by every pass.
// This WGSL is the one shader source. WebGPU runs it as written; the D3D12
// backend runs src/renderer/gpu/shaders/hlsl/, which scripts/wgsl_to_hlsl.py generates from it
// (CI fails when the two differ). The translator needs every let and var to
// carry an explicit type.
// Each function mirrors one C++ function in src/ line for line, with the same
// operation order, so the GPU computes the same float32 expressions as the CPU
// reference. Shader compilers may still fuse or reorder; the reconcile
// certificate (raw/renderer/gpu_reconcile.hpp) measures what that costs.

struct Params {
    float4 vp[4]; // current view-projection, rows (raw/math/mat.hpp is row-major)
    float4 pvp[4]; // previous view-projection, rows
    float4 light; // xyz direction, w intensity
    float4 misc; // x AO radius (world), y SSAO pixel radius
    uint w; uint h; uint ntri; uint rt_samples;
    uint ss_samples; uint rtao; uint pad0; uint pad1;
};

// Triangle input: 24 floats each. 0..8 world positions a,b,c; 9..17 normals; 18..20 albedo.
static const uint TRI_STRIDE = 24u;
// Triangle setup output: 16 floats each.
// 0 valid, 1..3 screen x, 4..6 screen y, 7..9 view distance, 10..12 1/w, 13 area,
// 14 unused, 15 unused. Integer bounds live in the parallel u32 array (4 per triangle).
static const uint SETUP_STRIDE = 16u;

// Triangle setup (src/renderer/raster.cpp, the per-triangle half): clip space, perspective
// divide, screen mapping, bounds and signed area. One invocation per triangle.
ConstantBuffer<Params> P : register(b0);
RWStructuredBuffer<float> tris : register(u1);
RWStructuredBuffer<float> setupF : register(u2);
RWStructuredBuffer<int> setupI : register(u3);

float vlen(float3 v) { return sqrt(v.x * v.x + v.y * v.y + v.z * v.z); }
// raw::normalize: l > 0 ? v * (1/l) : v
float3 vnorm(float3 v) {
    const float l = vlen(v);
    if (l > 0.0f) { const float s = 1.0f / l; return float3(v.x * s, v.y * s, v.z * s); }
    return v;
}
float3 vcross(float3 a, float3 b) {
    return float3(a.y * b.z - a.z * b.y, a.z * b.x - a.x * b.z, a.x * b.y - a.y * b.x);
}
float vdot(float3 a, float3 b) { return a.x * b.x + a.y * b.y + a.z * b.z; }
// raw::mul(Mat4, Vec4), row by row, left to right.
float mrow(float4 r, float4 v) { return r.x * v.x + r.y * v.y + r.z * v.z + r.w * v.w; }
float4 mmul(float4 m[4], float4 v) {
    return float4(mrow(m[0], v), mrow(m[1], v), mrow(m[2], v), mrow(m[3], v));
}
// The deterministic per-pixel hash of src/renderer/ssao.cpp and src/renderer/ray_ao.cpp.
float hash01(uint x, uint y, uint s) {
    uint h = x * 374761393u + y * 668265263u + s * 2246822519u;
    h = (h ^ (h >> 13u)) * 1274126177u;
    h = h ^ (h >> 16u);
    return float(h & 0xFFFFFFu) / 16777216.0f;
}
// std::lround: halves round away from zero (WGSL round() rounds halves to even).
int lround(float v) {
    if (v >= 0.0f) { return int(floor(v + 0.5f)); }
    return -int(floor(-v + 0.5f));
}
uint pix(uint x, uint y) { return y * P.w + x; }

[numthreads(64, 1, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    const uint t = gid.x;
    if (t >= P.ntri) { return; }
    const uint b = t * TRI_STRIDE;
    const uint o = t * SETUP_STRIDE;
    setupF[o] = 0.0f;
    float sx[3] = {0.0f, 0.0f, 0.0f}; float sy[3] = {0.0f, 0.0f, 0.0f}; float sz[3] = {0.0f, 0.0f, 0.0f}; float iw[3] = {0.0f, 0.0f, 0.0f};
    for (uint k = 0u; k < 3u; k++) {
        const float4 wp = float4(tris[b + 3u * k], tris[b + 3u * k + 1u], tris[b + 3u * k + 2u], 1.0f);
        const float4 cs = mmul(P.vp, wp);
        if (cs.w <= 1e-6f) { return; }
        const float inv = 1.0f / cs.w;
        const float nx = cs.x * inv;
        const float ny = cs.y * inv;
        sx[k] = (nx * 0.5f + 0.5f) * float(P.w);
        sy[k] = (1.0f - (ny * 0.5f + 0.5f)) * float(P.h);
        sz[k] = cs.w;
        iw[k] = inv;
    }
    const float area = (sx[1] - sx[0]) * (sy[2] - sy[0]) - (sy[1] - sy[0]) * (sx[2] - sx[0]);
    if (abs(area) < 1e-9f) { return; }
    for (uint j = 0u; j < 3u; j++) {
        setupF[o + 1u + j] = sx[j]; setupF[o + 4u + j] = sy[j];
        setupF[o + 7u + j] = sz[j]; setupF[o + 10u + j] = iw[j];
    }
    setupF[o + 13u] = area;
    const uint oi = t * 4u;
    setupI[oi]      = max(0, int(floor(min(min(sx[0], sx[1]), sx[2]))));
    setupI[oi + 1u] = min(int(P.w) - 1, int(ceil(max(max(sx[0], sx[1]), sx[2]))));
    setupI[oi + 2u] = max(0, int(floor(min(min(sy[0], sy[1]), sy[2]))));
    setupI[oi + 3u] = min(int(P.h) - 1, int(ceil(max(max(sy[0], sy[1]), sy[2]))));
    setupF[o] = 1.0f;
}
