// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/shadow.wgsl. Do not edit.
// WGSL sha256 c2cbfdb3e556b4212aade08181ec416f712c3ea1068862e2bc60b23e729edec0
// Pass: shadow_lookup

// raw-native GPU shadow passes (ROADMAP M3 shadows): cascaded shadow-map lookups (hard, PCF
// and PCSS) and the screen-space contact-shadow march, the float32 forms of
// raw::shadows::lookup and raw::shadows::contactShadows (src/renderer/shadows.cpp and
// src/renderer/shadow_raster.cpp). The maps come from the shadow_depth raster pass.

struct ShadowParams {
    uint count; uint size; uint width; uint height;
    uint steps; uint pad0; uint pad1; uint pad2;
    float4 right;
    float4 up;
    float4 light;
    float4 box[4]; // per cascade: light-space centre x, y, radius, split (view depth)
    float4 span[4]; // per cascade: zNear, zFar
    float4 cfg; // tan(sun angle), normal offset (texels), depth bias (texels), contact thickness
    float4 vp[4]; // contact: the camera's view-projection rows
    float4 march; // contact: direction to the light (unit), march length
};
// A point: 8 floats. 0..2 world position, 3 view depth, 4..6 unit normal, 7 valid (1) or not (0).
static const uint POINT = 8u;

// One invocation per point: its cascade, then the hard, PCF (5 x 5 tent) and PCSS
// visibilities, written as three floats. M holds the four maps' normalised depths, size x size
// each, in cascade order; T the tap table of raw::shadows::poissonTaps (16 blocker taps, then
// 25 filter taps, as x, y pairs).
ConstantBuffer<ShadowParams> P : register(b0);
RWStructuredBuffer<float> M : register(u1);
RWStructuredBuffer<float> Q : register(u2);
RWStructuredBuffer<float> T : register(u3);
RWStructuredBuffer<float> O : register(u4);

int cascade_of(float depth) {
    for (int k = 0; k < 4; k++) {
        if (depth <= P.box[k].w) { return k; }
    }
    return -1;
}
float map_depth(int k, int ix, int iy) {
    const int s = int(P.size);
    return M[uint(k * s * s + iy * s + ix)];
}
bool inside(int ix, int iy) {
    const int s = int(P.size);
    return ix >= 0 && iy >= 0 && ix < s && iy < s;
}
float lit(int k, float x, float y, float d) {
    const int ix = int(floor(x));
    const int iy = int(floor(y));
    if (!inside(ix, iy)) { return 1.0f; }
    return ((d <= map_depth(k, ix, iy)) ? (1.0f) : (0.0f));
}

[numthreads(64, 1, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    const uint i = gid.x;
    if (i >= P.count) { return; }
    const uint b = i * POINT;
    O[3u * i] = 1.0f;
    O[3u * i + 1u] = 1.0f;
    O[3u * i + 2u] = 1.0f;
    if (Q[b + 7u] == 0.0f) { return; }
    const int k = cascade_of(Q[b + 3u]);
    if (k < 0) { return; }
    const float cx = P.box[k].x;
    const float cy = P.box[k].y;
    const float r = P.box[k].z;
    const float zn = P.span[k].x;
    const float range = P.span[k].y - zn;
    const float sz = float(P.size);
    const float tw = 2.0f * r / sz;
    const float off = P.cfg.y * tw;
    const float3 q = float3(Q[b] + Q[b + 4u] * off, Q[b + 1u] + Q[b + 5u] * off, Q[b + 2u] + Q[b + 6u] * off);
    const float lx = q.x * P.right.x + q.y * P.right.y + q.z * P.right.z;
    const float ly = q.x * P.up.x + q.y * P.up.y + q.z * P.up.z;
    const float lz = q.x * P.light.x + q.y * P.light.y + q.z * P.light.z;
    const float u = (lx - cx) / r;
    const float v = (ly - cy) / r;
    const float d = (lz - zn) / range - P.cfg.z * tw / range;
    const float fx = (u * 0.5f + 0.5f) * sz;
    const float fy = (1.0f - (v * 0.5f + 0.5f)) * sz;
    O[3u * i] = lit(k, fx, fy, d);
    float s = 0.0f;
    for (int bb = -2; bb <= 2; bb++) {
        for (int aa = -2; aa <= 2; aa++) {
            s += float((3 - abs(aa)) * (3 - abs(bb))) * lit(k, fx + float(aa), fy + float(bb), d);
        }
    }
    O[3u * i + 1u] = s / 81.0f;
    const float tanSun = P.cfg.x;
    const float rs = clamp(10.0f * tanSun / tw, 1.0f, 16.0f);
    float blocker = 0.0f;
    int found = 0;
    for (uint t = 0u; t < 16u; t++) {
        const int ix = int(floor(fx + T[2u * t] * rs));
        const int iy = int(floor(fy + T[2u * t + 1u] * rs));
        if (inside(ix, iy)) {
            const float z = map_depth(k, ix, iy);
            if (z < d) { blocker += z; found += 1; }
        }
    }
    if (found == 0) { return; }
    const float penumbra = (d - blocker / float(found)) * range * tanSun;
    const float rk = clamp(penumbra / tw, 1.0f, 16.0f);
    float f = 0.0f;
    for (uint j = 16u; j < 41u; j++) {
        f += lit(k, fx + T[2u * j] * rk, fy + T[2u * j + 1u] * rk, d);
    }
    O[3u * i + 2u] = f / 25.0f;
}
