// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/raster.wgsl. Do not edit.
// WGSL sha256 fb145cf9e6d3c744aa240359221fcc3c0121b9ff5262c83e13210986bbe4e171
// Raster pass: shadow_depth (entry points vs, fs)

// One cascade of a directional light's shadow map (ROADMAP M3 shadows): the triangles of
// the gbuffer pass, through the cascade's orthographic light-space matrix (rows; clip z is
// already in [0, 1] and w = 1), depth-tested in hardware. Target: (triangle index + 1,
// normalised depth); the CPU twin is raw::shadows::rasterizeCascade.
struct Light {
    float4 m[4];
};
struct SdOut {
    float4 clip : SV_Position;
    nointerpolation uint tri : TEXCOORD0;
    float z : TEXCOORD1;
};
ConstantBuffer<Light> U : register(b0);
RWStructuredBuffer<float> T : register(u0);
float mrow(float4 r, float4 v) { return r.x * v.x + r.y * v.y + r.z * v.z + r.w * v.w; }

SdOut vs(uint i : SV_VertexID) {
    const uint t = i / 3u;
    const uint k = i % 3u;
    const uint b = t * 24u;
    const float4 wp = float4(T[b + 3u * k], T[b + 3u * k + 1u], T[b + 3u * k + 2u], 1.0f);
    SdOut o = (SdOut)0;
    o.z = mrow(U.m[2], wp);
    o.clip = float4(mrow(U.m[0], wp), mrow(U.m[1], wp), o.z, 1.0f);
    o.tri = t + 1u;
    return o;
}

float4 fs(SdOut v) : SV_Target0 {
    return float4(float(v.tri), v.z, 0.0f, 1.0f);
}
