// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/shadow.wgsl. Do not edit.
// WGSL sha256 c2cbfdb3e556b4212aade08181ec416f712c3ea1068862e2bc60b23e729edec0
// Pass: shadow_contact

// raw-native GPU shadow passes (ROADMAP M3 shadows): cascaded shadow-map lookups (hard, PCF
// and PCSS) and the screen-space contact-shadow march, the float32 forms of
// raw::shadows::lookup and raw::shadows::contactShadows (src/renderer/shadows.cpp and
// src/renderer/shadow_raster.cpp). The maps come from the shadow_depth raster pass.

struct ShadowParams {
    uint count; uint size; uint width; uint height;
    uint steps; uint pad0; uint pad1; uint pad2;
    float4 right;
    float4 up;
    float4 light;
    float4 box[4]; // per cascade: light-space centre x, y, radius, split (view depth)
    float4 span[4]; // per cascade: zNear, zFar
    float4 cfg; // tan(sun angle), normal offset (texels), depth bias (texels), contact thickness
    float4 vp[4]; // contact: the camera's view-projection rows
    float4 march; // contact: direction to the light (unit), march length
};
// A point: 8 floats. 0..2 world position, 3 view depth, 4..6 unit normal, 7 valid (1) or not (0).
static const uint POINT = 8u;

// One invocation per pixel: march from the pixel's surface toward the light; a step that lands
// behind the depth buffer's surface by less than the thickness is an occluder. D holds the
// view depth per pixel, negative where nothing was drawn.
ConstantBuffer<ShadowParams> P : register(b0);
RWStructuredBuffer<float> D : register(u1);
RWStructuredBuffer<float> Q : register(u2);
RWStructuredBuffer<float> O : register(u3);

float mrow(float4 r, float4 v) { return r.x * v.x + r.y * v.y + r.z * v.z + r.w * v.w; }

[numthreads(64, 1, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    const uint i = gid.x;
    if (i >= P.width * P.height) { return; }
    float vis = 1.0f;
    if (D[i] >= 0.0f) {
        const uint b = i * POINT;
        const int w = int(P.width);
        const int h = int(P.height);
        for (uint s = 1u; s <= P.steps; s++) {
            const float t = P.march.w * float(s) / float(P.steps);
            const float4 p = float4(Q[b] + P.march.x * t, Q[b + 1u] + P.march.y * t, Q[b + 2u] + P.march.z * t, 1.0f);
            const float cw = mrow(P.vp[3], p);
            if (cw <= 1.0e-6f) { break; }
            const int sx = int(floor((mrow(P.vp[0], p) / cw * 0.5f + 0.5f) * float(w)));
            const int sy = int(floor((1.0f - (mrow(P.vp[1], p) / cw * 0.5f + 0.5f)) * float(h)));
            if (sx < 0 || sy < 0 || sx >= w || sy >= h) { break; }
            const float d = D[uint(sy * w + sx)];
            if (d >= 0.0f && cw > d + 1.0e-3f && cw - d < P.cfg.w) { vis = 0.0f; break; }
        }
    }
    O[i] = vis;
}
