// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/swr.wgsl. Do not edit.
// WGSL sha256 ea9576f5ccc36a70783c4f92e31667cfab7d8f2b6430a79758681bcccab4ebc9
// Pass: swr_bin_fill

// raw-native's own GPU triangle rasterizer (RT stage R1): the compute form of
// src/renderer/swr_setup.cpp and swr_raster.cpp, read with raw/renderer/swr.hpp. No
// fixed-function raster and no atomics: bins are counted, scanned and filled by
// invocations that each own one bin, so the lists come out in slot order and the result
// does not depend on scheduling. Edge functions are exact 64-bit integers carried as
// (lo, hi) pairs of u32, since WGSL has no 64-bit integers.

struct SwrParams {
    uint w; uint h; uint slots; uint tile;
    uint tilesX; uint tilesY; uint rule; uint depthTest;
    uint affine; uint depthBits; uint cullBack; uint snapShift;
    float scale; float guard; uint tris; float maxQ;
    float4 m0; float4 m1; float4 m2; float4 m3;
    float4 light;
};
static const uint SI_N = 12u;
static const uint SF_N = 16u;
static const uint SLOTS = 7u;

// One invocation per bin: its slots, in slot order, at its offset in Q.
ConstantBuffer<SwrParams> P : register(b0);
RWStructuredBuffer<int> SI : register(u1);
RWStructuredBuffer<uint> C : register(u2);
RWStructuredBuffer<uint> Q : register(u3);

uint2 neg64(uint2 a) {
    const uint lo = ~a.x + 1u;
    return uint2(lo, ~a.y + ((lo == 0u) ? (1u) : (0u)));
}
uint2 add64(uint2 a, uint2 b) {
    const uint lo = a.x + b.x;
    return uint2(lo, a.y + b.y + ((lo < a.x) ? (1u) : (0u)));
}
// The exact product of two i32 as a 64-bit (lo, hi) pair, two's complement.
uint2 mul64(int a, int b) {
    const uint ua = uint(abs(a));
    const uint ub = uint(abs(b));
    const uint a0 = ua & 0xffffu;
    const uint a1 = ua >> 16u;
    const uint b0 = ub & 0xffffu;
    const uint b1 = ub >> 16u;
    const uint p00 = a0 * b0;
    const uint p01 = a0 * b1;
    const uint mid = p01 + a1 * b0;
    const uint mc = ((mid < p01) ? (0x10000u) : (0u));
    const uint lo = p00 + (mid << 16u);
    const uint hi = a1 * b1 + (mid >> 16u) + mc + ((lo < p00) ? (1u) : (0u));
    uint2 r = uint2(lo, hi);
    if ((a < 0) != (b < 0)) { r = neg64(r); }
    return r;
}
// E_ij(p) = (xj - xi)(py - yi) - (yj - yi)(px - xi)
uint2 edge64(int xi, int yi, int xj, int yj, int px, int py) {
    return add64(mul64(xj - xi, py - yi), neg64(mul64(yj - yi, px - xi)));
}
bool is_neg(uint2 e) {
    return int(e.y) < 0;
}
bool is_zero(uint2 e) {
    return e.x == 0u && e.y == 0u;
}
// Every conversion exact, the two adds rounded: the CPU's edgeToFloat. e >= 0.
float to_f(uint2 e) {
    return (float(e.y) * 4294967296.0f + float(e.x >> 16u) * 65536.0f) + float(e.x & 0xffffu);
}
bool top_left(int dx, int dy) {
    return (dy == 0 && dx > 0) || dy < 0;
}
bool covers(uint2 e, bool tl, uint rule) {
    if (is_neg(e)) { return false; }
    if (!is_zero(e)) { return true; }
    if (rule == 0u) { return tl; }
    if (rule == 1u) { return !tl; }
    return rule == 2u;
}
// The 4 x 4 Bayer matrix, packed four bits an entry (0 8 2 10 / 12 4 14 6 / 3 11 1 9 / 15 7 13 5).
uint bayer4(uint x, uint y) {
    const uint i = (y & 3u) * 4u + (x & 3u);
    const uint word = ((i >= 8u) ? (0x5d7f91b3u) : (0x6e4ca280u));
    return (word >> (4u * (i & 7u))) & 15u;
}
// The three edge functions of a slot at a sample: x, y, z are f(E_12), f(E_20), f(E_01) and
// w is 1 when the sample is covered under `rule`, -1 when it is not.
float4 cover_edges(int x0, int y0, int x1, int y1, int x2, int y2, int px, int py, uint rule) {
    const uint2 e12 = edge64(x1, y1, x2, y2, px, py);
    const uint2 e20 = edge64(x2, y2, x0, y0, px, py);
    const uint2 e01 = edge64(x0, y0, x1, y1, px, py);
    const bool a = covers(e12, top_left(x2 - x1, y2 - y1), rule);
    const bool b = covers(e20, top_left(x0 - x2, y0 - y2), rule);
    const bool c = covers(e01, top_left(x1 - x0, y1 - y0), rule);
    if (!(a && b && c)) { return float4(0.0f, 0.0f, 0.0f, -1.0f); }
    return float4(to_f(e12), to_f(e20), to_f(e01), 1.0f);
}
int ceil_div256(int v) {
    return -((-v) >> 8u);
}
float plane_dist(float x, float y, float z, float w, uint plane, float g) {
    if (plane == 0u) { return z + w; }
    if (plane == 1u) { return w - z; }
    if (plane == 2u) { return g * w - x; }
    if (plane == 3u) { return g * w + x; }
    if (plane == 4u) { return g * w - y; }
    return g * w + y;
}

[numthreads(64, 1, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    const uint bins = P.tilesX * P.tilesY;
    const uint bin = gid.x;
    if (bin >= bins) { return; }
    const int x0 = int((bin % P.tilesX) * P.tile);
    const int y0 = int((bin / P.tilesX) * P.tile);
    const int x1 = x0 + int(P.tile) - 1;
    const int y1 = y0 + int(P.tile) - 1;
    uint at = C[bins + bin];
    for (uint s = 0u; s < P.slots; s++) {
        const uint i = s * SI_N;
        if (SI[i + 6u] == 0) { continue; }
        if (SI[i + 7u] <= x1 && SI[i + 9u] >= x0 && SI[i + 8u] <= y1 && SI[i + 10u] >= y0) {
            Q[at] = s;
            at = at + 1u;
        }
    }
}
