// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/swr.wgsl. Do not edit.
// WGSL sha256 87630466b2c3dff8bedc8d58b979e7c4cb50a2234b66f03fd3d6df0a386b8564
// Pass: swr_setup

// raw-native's own GPU triangle rasterizer (RT stage R1): the compute form of
// src/renderer/swr_setup.cpp and swr_raster.cpp, read with raw/renderer/swr.hpp. No
// fixed-function raster and no atomics: bins are counted, scanned and filled by
// invocations that each own one bin, so the lists come out in slot order and the result
// does not depend on scheduling. Edge functions are exact 64-bit integers carried as
// (lo, hi) pairs of u32, since WGSL has no 64-bit integers.

struct SwrParams {
    uint w; uint h; uint slots; uint tile;
    uint tilesX; uint tilesY; uint rule; uint depthTest;
    uint affine; uint depthBits; uint cullBack; uint snapShift;
    float scale; float guard; uint tris; float maxQ;
    float4 m0; float4 m1; float4 m2; float4 m3;
    float4 light;
};
static const uint SI_N = 12u;
static const uint SF_N = 16u;
static const uint SLOTS = 7u;

// One invocation per source triangle: transform, clip (near, far, guard band), snap to the
// fixed-point grid and fan into up to 7 slots, as raw::swr::setup does; unused slots are
// cleared. V: positions, three floats a vertex; X: indices, three a triangle.
ConstantBuffer<SwrParams> P : register(b0);
RWStructuredBuffer<float> V : register(u1);
RWStructuredBuffer<uint> X : register(u2);
RWStructuredBuffer<int> SI : register(u3);
RWStructuredBuffer<float> SF : register(u4);

uint2 neg64(uint2 a) {
    const uint lo = ~a.x + 1u;
    return uint2(lo, ~a.y + ((lo == 0u) ? (1u) : (0u)));
}
uint2 add64(uint2 a, uint2 b) {
    const uint lo = a.x + b.x;
    return uint2(lo, a.y + b.y + ((lo < a.x) ? (1u) : (0u)));
}
// The exact product of two i32 as a 64-bit (lo, hi) pair, two's complement.
uint2 mul64(int a, int b) {
    const uint ua = uint(abs(a));
    const uint ub = uint(abs(b));
    const uint a0 = ua & 0xffffu;
    const uint a1 = ua >> 16u;
    const uint b0 = ub & 0xffffu;
    const uint b1 = ub >> 16u;
    const uint p00 = a0 * b0;
    const uint p01 = a0 * b1;
    const uint mid = p01 + a1 * b0;
    const uint mc = ((mid < p01) ? (0x10000u) : (0u));
    const uint lo = p00 + (mid << 16u);
    const uint hi = a1 * b1 + (mid >> 16u) + mc + ((lo < p00) ? (1u) : (0u));
    uint2 r = uint2(lo, hi);
    if ((a < 0) != (b < 0)) { r = neg64(r); }
    return r;
}
// E_ij(p) = (xj - xi)(py - yi) - (yj - yi)(px - xi)
uint2 edge64(int xi, int yi, int xj, int yj, int px, int py) {
    return add64(mul64(xj - xi, py - yi), neg64(mul64(yj - yi, px - xi)));
}
bool is_neg(uint2 e) {
    return int(e.y) < 0;
}
bool is_zero(uint2 e) {
    return e.x == 0u && e.y == 0u;
}
// Every conversion exact, the two adds rounded: the CPU's edgeToFloat. e >= 0.
float to_f(uint2 e) {
    return (float(e.y) * 4294967296.0f + float(e.x >> 16u) * 65536.0f) + float(e.x & 0xffffu);
}
bool top_left(int dx, int dy) {
    return (dy == 0 && dx > 0) || dy < 0;
}
bool covers(uint2 e, bool tl, uint rule) {
    if (is_neg(e)) { return false; }
    if (!is_zero(e)) { return true; }
    if (rule == 0u) { return tl; }
    if (rule == 1u) { return !tl; }
    return rule == 2u;
}
// The 4 x 4 Bayer matrix, packed four bits an entry (0 8 2 10 / 12 4 14 6 / 3 11 1 9 / 15 7 13 5).
uint bayer4(uint x, uint y) {
    const uint i = (y & 3u) * 4u + (x & 3u);
    const uint word = ((i >= 8u) ? (0x5d7f91b3u) : (0x6e4ca280u));
    return (word >> (4u * (i & 7u))) & 15u;
}
// The three edge functions of a slot at a sample: x, y, z are f(E_12), f(E_20), f(E_01) and
// w is 1 when the sample is covered under `rule`, -1 when it is not.
float4 cover_edges(int x0, int y0, int x1, int y1, int x2, int y2, int px, int py, uint rule) {
    const uint2 e12 = edge64(x1, y1, x2, y2, px, py);
    const uint2 e20 = edge64(x2, y2, x0, y0, px, py);
    const uint2 e01 = edge64(x0, y0, x1, y1, px, py);
    const bool a = covers(e12, top_left(x2 - x1, y2 - y1), rule);
    const bool b = covers(e20, top_left(x0 - x2, y0 - y2), rule);
    const bool c = covers(e01, top_left(x1 - x0, y1 - y0), rule);
    if (!(a && b && c)) { return float4(0.0f, 0.0f, 0.0f, -1.0f); }
    return float4(to_f(e12), to_f(e20), to_f(e01), 1.0f);
}
int ceil_div256(int v) {
    return -((-v) >> 8u);
}
float plane_dist(float x, float y, float z, float w, uint plane, float g) {
    if (plane == 0u) { return z + w; }
    if (plane == 1u) { return w - z; }
    if (plane == 2u) { return g * w - x; }
    if (plane == 3u) { return g * w + x; }
    if (plane == 4u) { return g * w - y; }
    return g * w + y;
}

void clear_slot(uint slot) {
    for (uint k = 0u; k < SI_N; k++) { SI[slot * SI_N + k] = 0; }
    for (uint j = 0u; j < SF_N; j++) { SF[slot * SF_N + j] = 0.0f; }
    SI[slot * SI_N + 7u] = 1;
}

// One fan triangle (vertex columns a, b, c of the snapped arrays) into `slot`.
void write_slot(uint slot, uint src, int ax, int ay, int bx0, int by0, int cx0, int cy0, float za, float zb0, float zc0, float wa, float wb0, float wc0, float sa, float sb0, float sc0, float ta, float tb0, float tc0) {
    uint2 area = edge64(ax, ay, bx0, by0, cx0, cy0);
    if (is_zero(area)) { return; }
    int bx = bx0;
    int by = by0;
    int cx = cx0;
    int cy = cy0;
    float zb = zb0;
    float zc = zc0;
    float wb = wb0;
    float wc = wc0;
    float sb = sb0;
    float sc = sc0;
    float tb = tb0;
    float tc = tc0;
    if (is_neg(area)) {
        if (P.cullBack == 1u) { return; }
        bx = cx0; by = cy0; cx = bx0; cy = by0;
        zb = zc0; zc = zb0; wb = wc0; wc = wb0; sb = sc0; sc = sb0; tb = tc0; tc = tb0;
        area = neg64(area);
    }
    const uint i = slot * SI_N;
    const uint f = slot * SF_N;
    SI[i] = ax; SI[i + 1u] = ay; SI[i + 2u] = bx; SI[i + 3u] = by; SI[i + 4u] = cx; SI[i + 5u] = cy;
    SI[i + 6u] = int(src + 1u);
    SI[i + 7u] = max(0, ceil_div256(min(ax, min(bx, cx)) - 128));
    SI[i + 8u] = max(0, ceil_div256(min(ay, min(by, cy)) - 128));
    SI[i + 9u] = min(int(P.w) - 1, (max(ax, max(bx, cx)) - 128) >> 8u);
    SI[i + 10u] = min(int(P.h) - 1, (max(ay, max(by, cy)) - 128) >> 8u);
    SF[f] = za; SF[f + 1u] = zb; SF[f + 2u] = zc;
    SF[f + 3u] = wa; SF[f + 4u] = wb; SF[f + 5u] = wc;
    SF[f + 6u] = 1.0f / to_f(area);
    SF[f + 7u] = sa; SF[f + 8u] = ta; SF[f + 9u] = sb; SF[f + 10u] = tb; SF[f + 11u] = sc; SF[f + 12u] = tc;
}

[numthreads(64, 1, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    const uint t = gid.x;
    if (t >= P.tris) { return; }
    for (uint k = 0u; k < SLOTS; k++) { clear_slot(t * SLOTS + k); }
    float cx[9] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
    float cy[9] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
    float cz[9] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
    float cw[9] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
    float cs[9] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
    float ct[9] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
    float ox[9] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
    float oy[9] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
    float oz[9] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
    float ow[9] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
    float os[9] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
    float ot[9] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
    for (uint v = 0u; v < 3u; v++) {
        const uint j = X[t * 3u + v] * 3u;
        const float px = V[j];
        const float py = V[j + 1u];
        const float pz = V[j + 2u];
        cx[v] = P.m0.x * px + P.m0.y * py + P.m0.z * pz + P.m0.w;
        cy[v] = P.m1.x * px + P.m1.y * py + P.m1.z * pz + P.m1.w;
        cz[v] = P.m2.x * px + P.m2.y * py + P.m2.z * pz + P.m2.w;
        cw[v] = P.m3.x * px + P.m3.y * py + P.m3.z * pz + P.m3.w;
        cs[v] = ((v == 1u) ? (1.0f) : (0.0f));
        ct[v] = ((v == 2u) ? (1.0f) : (0.0f));
    }
    uint n = 3u;
    for (uint plane = 0u; plane < 6u; plane++) {
        if (n < 3u) { break; }
        uint m = 0u;
        for (uint i = 0u; i < n; i++) {
            const uint j = (i + 1u) % n;
            const float da = plane_dist(cx[i], cy[i], cz[i], cw[i], plane, P.guard);
            const float db = plane_dist(cx[j], cy[j], cz[j], cw[j], plane, P.guard);
            if (da >= 0.0f) {
                ox[m] = cx[i]; oy[m] = cy[i]; oz[m] = cz[i]; ow[m] = cw[i]; os[m] = cs[i]; ot[m] = ct[i];
                m = m + 1u;
            }
            if ((da >= 0.0f) != (db >= 0.0f)) {
                const float q = da / (da - db);
                ox[m] = cx[i] + (cx[j] - cx[i]) * q;
                oy[m] = cy[i] + (cy[j] - cy[i]) * q;
                oz[m] = cz[i] + (cz[j] - cz[i]) * q;
                ow[m] = cw[i] + (cw[j] - cw[i]) * q;
                os[m] = cs[i] + (cs[j] - cs[i]) * q;
                ot[m] = ct[i] + (ct[j] - ct[i]) * q;
                m = m + 1u;
            }
        }
        n = m;
        for (uint c = 0u; c < n; c++) {
            cx[c] = ox[c]; cy[c] = oy[c]; cz[c] = oz[c]; cw[c] = ow[c]; cs[c] = os[c]; ct[c] = ot[c];
        }
    }
    if (n < 3u) { return; }
    int fx[9] = {0, 0, 0, 0, 0, 0, 0, 0, 0};
    int fy[9] = {0, 0, 0, 0, 0, 0, 0, 0, 0};
    const int grid = int(1u << P.snapShift);
    for (uint s = 0u; s < n; s++) {
        const float iw = 1.0f / cw[s];
        const float nx = cx[s] * iw;
        const float ny = cy[s] * iw;
        cz[s] = cz[s] * iw;
        cw[s] = iw;
        const float sx = (nx * 0.5f + 0.5f) * float(P.w);
        const float sy = (1.0f - (ny * 0.5f + 0.5f)) * float(P.h);
        fx[s] = int(floor(sx * P.scale + 0.5f)) * grid;
        fy[s] = int(floor(sy * P.scale + 0.5f)) * grid;
    }
    for (uint k2 = 1u; k2 + 1u < n; k2++) {
        const uint b = k2;
        const uint c2 = k2 + 1u;
        write_slot(t * SLOTS + k2 - 1u, t, fx[0], fy[0], fx[b], fy[b], fx[c2], fy[c2], cz[0], cz[b], cz[c2], cw[0], cw[b], cw[c2], cs[0], cs[b], cs[c2], ct[0], ct[b], ct[c2]);
    }
}
