// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/swr.wgsl. Do not edit.
// WGSL sha256 ea9576f5ccc36a70783c4f92e31667cfab7d8f2b6430a79758681bcccab4ebc9
// Pass: swr_resolve

// raw-native's own GPU triangle rasterizer (RT stage R1): the compute form of
// src/renderer/swr_setup.cpp and swr_raster.cpp, read with raw/renderer/swr.hpp. No
// fixed-function raster and no atomics: bins are counted, scanned and filled by
// invocations that each own one bin, so the lists come out in slot order and the result
// does not depend on scheduling. Edge functions are exact 64-bit integers carried as
// (lo, hi) pairs of u32, since WGSL has no 64-bit integers.

struct SwrParams {
    uint w; uint h; uint slots; uint tile;
    uint tilesX; uint tilesY; uint rule; uint depthTest;
    uint affine; uint depthBits; uint cullBack; uint snapShift;
    float scale; float guard; uint tris; float maxQ;
    float4 m0; float4 m1; float4 m2; float4 m3;
    float4 light;
};
static const uint SI_N = 12u;
static const uint SF_N = 16u;
static const uint SLOTS = 7u;

// One invocation per pixel: perspective-correct (or affine) weights of the visible slot, the
// source triangle's attributes (A: 16 floats a triangle, u v nx ny nz of each vertex, then the
// texture), a nearest wrapping texel (T: per texture offset width height, then texels) and the
// lit colour. OF: uv and texel coordinate (4 floats a pixel); OU: texel id and colour.
ConstantBuffer<SwrParams> P : register(b0);
RWStructuredBuffer<int> SI : register(u1);
RWStructuredBuffer<float> SF : register(u2);
RWStructuredBuffer<uint> B : register(u3);
RWStructuredBuffer<float> A : register(u4);
RWStructuredBuffer<uint> T : register(u5);
RWStructuredBuffer<float> OF : register(u6);
RWStructuredBuffer<uint> OU : register(u7);

uint2 neg64(uint2 a) {
    const uint lo = ~a.x + 1u;
    return uint2(lo, ~a.y + ((lo == 0u) ? (1u) : (0u)));
}
uint2 add64(uint2 a, uint2 b) {
    const uint lo = a.x + b.x;
    return uint2(lo, a.y + b.y + ((lo < a.x) ? (1u) : (0u)));
}
// The exact product of two i32 as a 64-bit (lo, hi) pair, two's complement.
uint2 mul64(int a, int b) {
    const uint ua = uint(abs(a));
    const uint ub = uint(abs(b));
    const uint a0 = ua & 0xffffu;
    const uint a1 = ua >> 16u;
    const uint b0 = ub & 0xffffu;
    const uint b1 = ub >> 16u;
    const uint p00 = a0 * b0;
    const uint p01 = a0 * b1;
    const uint mid = p01 + a1 * b0;
    const uint mc = ((mid < p01) ? (0x10000u) : (0u));
    const uint lo = p00 + (mid << 16u);
    const uint hi = a1 * b1 + (mid >> 16u) + mc + ((lo < p00) ? (1u) : (0u));
    uint2 r = uint2(lo, hi);
    if ((a < 0) != (b < 0)) { r = neg64(r); }
    return r;
}
// E_ij(p) = (xj - xi)(py - yi) - (yj - yi)(px - xi)
uint2 edge64(int xi, int yi, int xj, int yj, int px, int py) {
    return add64(mul64(xj - xi, py - yi), neg64(mul64(yj - yi, px - xi)));
}
bool is_neg(uint2 e) {
    return int(e.y) < 0;
}
bool is_zero(uint2 e) {
    return e.x == 0u && e.y == 0u;
}
// Every conversion exact, the two adds rounded: the CPU's edgeToFloat. e >= 0.
float to_f(uint2 e) {
    return (float(e.y) * 4294967296.0f + float(e.x >> 16u) * 65536.0f) + float(e.x & 0xffffu);
}
bool top_left(int dx, int dy) {
    return (dy == 0 && dx > 0) || dy < 0;
}
bool covers(uint2 e, bool tl, uint rule) {
    if (is_neg(e)) { return false; }
    if (!is_zero(e)) { return true; }
    if (rule == 0u) { return tl; }
    if (rule == 1u) { return !tl; }
    return rule == 2u;
}
// The 4 x 4 Bayer matrix, packed four bits an entry (0 8 2 10 / 12 4 14 6 / 3 11 1 9 / 15 7 13 5).
uint bayer4(uint x, uint y) {
    const uint i = (y & 3u) * 4u + (x & 3u);
    const uint word = ((i >= 8u) ? (0x5d7f91b3u) : (0x6e4ca280u));
    return (word >> (4u * (i & 7u))) & 15u;
}
// The three edge functions of a slot at a sample: x, y, z are f(E_12), f(E_20), f(E_01) and
// w is 1 when the sample is covered under `rule`, -1 when it is not.
float4 cover_edges(int x0, int y0, int x1, int y1, int x2, int y2, int px, int py, uint rule) {
    const uint2 e12 = edge64(x1, y1, x2, y2, px, py);
    const uint2 e20 = edge64(x2, y2, x0, y0, px, py);
    const uint2 e01 = edge64(x0, y0, x1, y1, px, py);
    const bool a = covers(e12, top_left(x2 - x1, y2 - y1), rule);
    const bool b = covers(e20, top_left(x0 - x2, y0 - y2), rule);
    const bool c = covers(e01, top_left(x1 - x0, y1 - y0), rule);
    if (!(a && b && c)) { return float4(0.0f, 0.0f, 0.0f, -1.0f); }
    return float4(to_f(e12), to_f(e20), to_f(e01), 1.0f);
}
int ceil_div256(int v) {
    return -((-v) >> 8u);
}
float plane_dist(float x, float y, float z, float w, uint plane, float g) {
    if (plane == 0u) { return z + w; }
    if (plane == 1u) { return w - z; }
    if (plane == 2u) { return g * w - x; }
    if (plane == 3u) { return g * w + x; }
    if (plane == 4u) { return g * w - y; }
    return g * w + y;
}

float attr(uint src, uint k, float b0, float b1, float b2) {
    const uint a = src * 16u + k;
    return A[a] * b0 + A[a + 5u] * b1 + A[a + 10u] * b2;
}

uint channel(uint c, uint k, float shade) {
    const float ch = float((c >> (8u * k)) & 255u) * shade;
    return min(255u, uint(floor(ch + 0.5f))) << (8u * k);
}

[numthreads(8, 8, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    if (gid.x >= P.w || gid.y >= P.h) { return; }
    const uint p = gid.y * P.w + gid.x;
    const uint slot1 = B[p * 2u];
    if (slot1 == 0u) {
        OF[p * 4u] = 0.0f;
        OF[p * 4u + 1u] = 0.0f;
        OF[p * 4u + 2u] = 0.0f;
        OF[p * 4u + 3u] = 0.0f;
        OU[p * 2u] = 0xffffffffu;
        OU[p * 2u + 1u] = 0u;
        return;
    }
    const uint s = slot1 - 1u;
    const uint i = s * SI_N;
    const uint f = s * SF_N;
    const float4 e = cover_edges(SI[i], SI[i + 1u], SI[i + 2u], SI[i + 3u], SI[i + 4u], SI[i + 5u], int(gid.x) * 256 + 128, int(gid.y) * 256 + 128, 2u);
    const float w0 = e.x * SF[f + 6u];
    const float w1 = e.y * SF[f + 6u];
    const float w2 = e.z * SF[f + 6u];
    float l0 = 0.0f;
    float l1 = 0.0f;
    float l2 = 0.0f;
    if (P.affine == 1u) {
        const float sum = w0 + w1 + w2;
        l0 = w0 / sum;
        l1 = w1 / sum;
        l2 = w2 / sum;
    } else {
        const float q0 = w0 * SF[f + 3u];
        const float q1 = w1 * SF[f + 4u];
        const float q2 = w2 * SF[f + 5u];
        const float den = q0 + q1 + q2;
        l0 = q0 / den;
        l1 = q1 / den;
        l2 = q2 / den;
    }
    const float b1 = l0 * SF[f + 7u] + l1 * SF[f + 9u] + l2 * SF[f + 11u];
    const float b2 = l0 * SF[f + 8u] + l1 * SF[f + 10u] + l2 * SF[f + 12u];
    const float b0 = (1.0f - b1) - b2;
    const uint src = uint(SI[i + 6u] - 1);
    const float u = attr(src, 0u, b0, b1, b2);
    const float v = attr(src, 1u, b0, b1, b2);
    const float nx = attr(src, 2u, b0, b1, b2);
    const float ny = attr(src, 3u, b0, b1, b2);
    const float nz = attr(src, 4u, b0, b1, b2);
    const float nl = 1.0f / sqrt(nx * nx + ny * ny + nz * nz);
    const float shade = 0.35f + 0.65f * max(0.0f, (nx * P.light.x + ny * P.light.y + nz * P.light.z) * nl);
    const uint tex = uint(A[src * 16u + 15u]);
    const uint tw = T[tex * 3u + 1u];
    const uint th = T[tex * 3u + 2u];
    const float tu = u * float(tw);
    const float tv = v * float(th);
    const uint tx = uint(int(floor(tu))) & (tw - 1u);
    const uint ty = uint(int(floor(tv))) & (th - 1u);
    const uint c = T[T[tex * 3u] + ty * tw + tx];
    OF[p * 4u] = u;
    OF[p * 4u + 1u] = v;
    OF[p * 4u + 2u] = tu;
    OF[p * 4u + 3u] = tv;
    OU[p * 2u] = tx | (ty << 12u) | (tex << 24u);
    OU[p * 2u + 1u] = 0xff000000u | channel(c, 0u, shade) | channel(c, 1u, shade) | channel(c, 2u, shade);
}
