// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/swr.wgsl. Do not edit.
// WGSL sha256 87630466b2c3dff8bedc8d58b979e7c4cb50a2234b66f03fd3d6df0a386b8564
// Pass: swr_gbuffer

// raw-native's own GPU triangle rasterizer (RT stage R1): the compute form of
// src/renderer/swr_setup.cpp and swr_raster.cpp, read with raw/renderer/swr.hpp. No
// fixed-function raster and no atomics: bins are counted, scanned and filled by
// invocations that each own one bin, so the lists come out in slot order and the result
// does not depend on scheduling. Edge functions are exact 64-bit integers carried as
// (lo, hi) pairs of u32, since WGSL has no 64-bit integers.

struct SwrParams {
    uint w; uint h; uint slots; uint tile;
    uint tilesX; uint tilesY; uint rule; uint depthTest;
    uint affine; uint depthBits; uint cullBack; uint snapShift;
    float scale; float guard; uint tris; float maxQ;
    float4 m0; float4 m1; float4 m2; float4 m3;
    float4 light;
};
static const uint SI_N = 12u;
static const uint SF_N = 16u;
static const uint SLOTS = 7u;

// One invocation per pixel: world position, geometric and shading normal of the visible slot,
// by the perspective-correct source weights of swr_resolve (RT stage R2, hybrid rays).
// VP: positions, 9 floats a source triangle; A: swr_resolve's attributes; G: 12 floats a
// pixel (position, geometric normal, shading normal, 1 when covered, pad 2).
ConstantBuffer<SwrParams> P : register(b0);
RWStructuredBuffer<int> SI : register(u1);
RWStructuredBuffer<float> SF : register(u2);
RWStructuredBuffer<uint> B : register(u3);
RWStructuredBuffer<float> VP : register(u4);
RWStructuredBuffer<float> A : register(u5);
RWStructuredBuffer<float> G : register(u6);

uint2 neg64(uint2 a) {
    const uint lo = ~a.x + 1u;
    return uint2(lo, ~a.y + ((lo == 0u) ? (1u) : (0u)));
}
uint2 add64(uint2 a, uint2 b) {
    const uint lo = a.x + b.x;
    return uint2(lo, a.y + b.y + ((lo < a.x) ? (1u) : (0u)));
}
// The exact product of two i32 as a 64-bit (lo, hi) pair, two's complement.
uint2 mul64(int a, int b) {
    const uint ua = uint(abs(a));
    const uint ub = uint(abs(b));
    const uint a0 = ua & 0xffffu;
    const uint a1 = ua >> 16u;
    const uint b0 = ub & 0xffffu;
    const uint b1 = ub >> 16u;
    const uint p00 = a0 * b0;
    const uint p01 = a0 * b1;
    const uint mid = p01 + a1 * b0;
    const uint mc = ((mid < p01) ? (0x10000u) : (0u));
    const uint lo = p00 + (mid << 16u);
    const uint hi = a1 * b1 + (mid >> 16u) + mc + ((lo < p00) ? (1u) : (0u));
    uint2 r = uint2(lo, hi);
    if ((a < 0) != (b < 0)) { r = neg64(r); }
    return r;
}
// E_ij(p) = (xj - xi)(py - yi) - (yj - yi)(px - xi)
uint2 edge64(int xi, int yi, int xj, int yj, int px, int py) {
    return add64(mul64(xj - xi, py - yi), neg64(mul64(yj - yi, px - xi)));
}
bool is_neg(uint2 e) {
    return int(e.y) < 0;
}
bool is_zero(uint2 e) {
    return e.x == 0u && e.y == 0u;
}
// Every conversion exact, the two adds rounded: the CPU's edgeToFloat. e >= 0.
float to_f(uint2 e) {
    return (float(e.y) * 4294967296.0f + float(e.x >> 16u) * 65536.0f) + float(e.x & 0xffffu);
}
bool top_left(int dx, int dy) {
    return (dy == 0 && dx > 0) || dy < 0;
}
bool covers(uint2 e, bool tl, uint rule) {
    if (is_neg(e)) { return false; }
    if (!is_zero(e)) { return true; }
    if (rule == 0u) { return tl; }
    if (rule == 1u) { return !tl; }
    return rule == 2u;
}
// The 4 x 4 Bayer matrix, packed four bits an entry (0 8 2 10 / 12 4 14 6 / 3 11 1 9 / 15 7 13 5).
uint bayer4(uint x, uint y) {
    const uint i = (y & 3u) * 4u + (x & 3u);
    const uint word = ((i >= 8u) ? (0x5d7f91b3u) : (0x6e4ca280u));
    return (word >> (4u * (i & 7u))) & 15u;
}
// The three edge functions of a slot at a sample: x, y, z are f(E_12), f(E_20), f(E_01) and
// w is 1 when the sample is covered under `rule`, -1 when it is not.
float4 cover_edges(int x0, int y0, int x1, int y1, int x2, int y2, int px, int py, uint rule) {
    const uint2 e12 = edge64(x1, y1, x2, y2, px, py);
    const uint2 e20 = edge64(x2, y2, x0, y0, px, py);
    const uint2 e01 = edge64(x0, y0, x1, y1, px, py);
    const bool a = covers(e12, top_left(x2 - x1, y2 - y1), rule);
    const bool b = covers(e20, top_left(x0 - x2, y0 - y2), rule);
    const bool c = covers(e01, top_left(x1 - x0, y1 - y0), rule);
    if (!(a && b && c)) { return float4(0.0f, 0.0f, 0.0f, -1.0f); }
    return float4(to_f(e12), to_f(e20), to_f(e01), 1.0f);
}
int ceil_div256(int v) {
    return -((-v) >> 8u);
}
float plane_dist(float x, float y, float z, float w, uint plane, float g) {
    if (plane == 0u) { return z + w; }
    if (plane == 1u) { return w - z; }
    if (plane == 2u) { return g * w - x; }
    if (plane == 3u) { return g * w + x; }
    if (plane == 4u) { return g * w - y; }
    return g * w + y;
}

float3 vp(uint t, uint k) {
    return float3(VP[t * 9u + k * 3u], VP[t * 9u + k * 3u + 1u], VP[t * 9u + k * 3u + 2u]);
}

[numthreads(8, 8, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    if (gid.x >= P.w || gid.y >= P.h) { return; }
    const uint p = gid.y * P.w + gid.x;
    for (uint z = 0u; z < 12u; z++) { G[p * 12u + z] = 0.0f; }
    const uint slot1 = B[p * 2u];
    if (slot1 == 0u) { return; }
    const uint s = slot1 - 1u;
    const uint i = s * SI_N;
    const uint f = s * SF_N;
    const float4 e = cover_edges(SI[i], SI[i + 1u], SI[i + 2u], SI[i + 3u], SI[i + 4u], SI[i + 5u], int(gid.x) * 256 + 128, int(gid.y) * 256 + 128, 2u);
    const float q0 = e.x * SF[f + 6u] * SF[f + 3u];
    const float q1 = e.y * SF[f + 6u] * SF[f + 4u];
    const float q2 = e.z * SF[f + 6u] * SF[f + 5u];
    const float den = q0 + q1 + q2;
    const float l0 = q0 / den;
    const float l1 = q1 / den;
    const float l2 = q2 / den;
    const float b1 = l0 * SF[f + 7u] + l1 * SF[f + 9u] + l2 * SF[f + 11u];
    const float b2 = l0 * SF[f + 8u] + l1 * SF[f + 10u] + l2 * SF[f + 12u];
    const float b0 = (1.0f - b1) - b2;
    const uint t = uint(SI[i + 6u] - 1);
    const float3 pos = vp(t, 0u) * b0 + vp(t, 1u) * b1 + vp(t, 2u) * b2;
    const float3 ng = normalize(cross(vp(t, 1u) - vp(t, 0u), vp(t, 2u) - vp(t, 0u)));
    const uint a = t * 16u;
    const float3 n = normalize(float3(A[a + 2u] * b0 + A[a + 7u] * b1 + A[a + 12u] * b2, A[a + 3u] * b0 + A[a + 8u] * b1 + A[a + 13u] * b2, A[a + 4u] * b0 + A[a + 9u] * b1 + A[a + 14u] * b2));
    G[p * 12u] = pos.x; G[p * 12u + 1u] = pos.y; G[p * 12u + 2u] = pos.z;
    G[p * 12u + 3u] = ng.x; G[p * 12u + 4u] = ng.y; G[p * 12u + 5u] = ng.z;
    G[p * 12u + 6u] = n.x; G[p * 12u + 7u] = n.y; G[p * 12u + 8u] = n.z;
    G[p * 12u + 9u] = 1.0f;
}
