// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/raster.wgsl. Do not edit.
// WGSL sha256 899319093bd45fd62feb145418c5590edf5674c435a67884e0fdd43960ec439b
// Raster pass: texture_identity (entry points vs, fs)

// ROADMAP M2 criterion 3: one full-screen triangle; each target pixel samples the source
// at uv = pixel centre / target size * scale + offset, mip level 0. The CPU twin is
// raw/renderer/sampler.hpp; the check is src/renderer/gpu/texture_identity.cpp.
struct Map {
    float2 size;
    float2 scale;
    float2 offset;
    float2 pad;
};
ConstantBuffer<Map> M : register(b0);
Texture2D<float4> src : register(t0);
SamplerState smp : register(s0);

float4 vs(uint i : SV_VertexID) : SV_Position {
    const float x = float((i << 1u) & 2u);
    const float y = float(i & 2u);
    return float4(x * 2.0f - 1.0f, 1.0f - y * 2.0f, 0.0f, 1.0f);
}

float4 fs(float4 q : SV_Position) : SV_Target0 {
    const float2 uv = q.xy / M.size * M.scale + M.offset;
    return src.SampleLevel(smp, uv, 0.0f);
}
