// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/threads.wgsl. Do not edit.
// WGSL sha256 8fa08424ec68ee1de040b090e671897ce9897be2cb75cca59c2f4637b1c30632
// Pass: threads_rd_seed

// Threads: particles flow along the zero set of a form field and leave luminous
// trails, tone-mapped by log density. A creative module: it has no CPU
// reference and writes no certificate (docs/architecture/adr/0010-web-host.md).
//
// One shader source for every backend. WebGPU runs it as written (web/ and the
// wasm build); D3D12 runs src/renderer/gpu/shaders/hlsl/threads_*.hlsl, which
// scripts/wgsl_to_hlsl.py generates from it. The code before the first pass
// marker is shared by every pass. Ported from a GLSL thread renderer: same
// fields, same motion and the same finish. Splats are integer atomics into a
// fixed-point accumulator instead of additive point blending, so the same
// passes run on a backend with compute only.

struct Params {
    float t; float dt; float fr; float aspect;
    float u; float ta; float tb; float spacing;
    float nlev; float gain; float scale; float keep;
    float expo; float spec; float dur; float fxs;
    float4 pr0;
    float4 pr1;
    uint np; int wa; int wb; int ch;
    uint w; uint h; uint substeps; uint simw;
    uint simh; uint seedbase; float simt; uint pad0;
};

// One level of the bloom pyramid: full-frame size, the level written, and the
// scale from accumulator units to density.
struct Level {
    uint w; uint h; uint level; float inv;
};

static const float PI = 3.14159265f;

// The reaction-diffusion field behind the Morphogen world, seeded with spots.
ConstantBuffer<Params> P : register(b0);
RWStructuredBuffer<float2> dst : register(u1);

float hash2(float2 p) { return frac(sin(dot(p, float2(127.1f, 311.7f))) * 43758.5453f); }
uint hashu(uint x0) {
    uint x = x0;
    x = x ^ (x >> 16u);
    x = x * 0x7feb352du;
    x = x ^ (x >> 15u);
    x = x * 0x846ca68bu;
    x = x ^ (x >> 16u);
    return x;
}
// The bloom pyramid: level l is max(1, size >> l) on each side. Odd levels live
// in one buffer and even levels in another, each packed after the earlier
// levels of the same parity, so a pass reads one buffer and writes the other.
uint levelDim(uint n, uint l) { return max(1u, n >> l); }
uint levelBase(uint w, uint h, uint l) {
    uint o = 0u;
    for (uint j = 2u - (l % 2u); j < l; j = j + 2u) {
        o = o + levelDim(w, j) * levelDim(h, j);
    }
    return o;
}
[numthreads(16, 16, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    if (gid.x >= P.simw || gid.y >= P.simh) { return; }
    const float2 q = (float2(float(gid.x), float(gid.y)) - float2(float(P.simw), float(P.simh)) * 0.5f) / float(P.simh);
    float v = step(length(q), 0.02f);
    for (int k = 0; k < 40; k++) {
        const float fk = float(k);
        const float2 sp = float2(frac(sin(fk * 12.9898f) * 43758.5f) * 1.7f - 0.85f, frac(sin(fk * 78.233f) * 12345.6f) - 0.5f);
        v = v + step(length(q - sp), 0.006f);
    }
    dst[gid.y * P.simw + gid.x] = float2(1.0f, min(v, 1.0f));
}
