// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/threads.wgsl. Do not edit.
// WGSL sha256 2b4d8c239a8394e8a4155d5642e68641d7c17764320b3fb32fdef22b1eeb1bca
// Pass: threads_finish

// Threads: particles flow along the zero set of a form field and leave luminous
// trails, tone-mapped by log density. A creative module: it has no CPU
// reference and writes no certificate (docs/architecture/adr/0010-web-host.md).
//
// One shader source for every backend. WebGPU runs it as written (web/ and the
// wasm build); D3D12 runs src/renderer/gpu/shaders/hlsl/threads_*.hlsl, which
// scripts/wgsl_to_hlsl.py generates from it. The code before the first pass
// marker is shared by every pass. Ported from a GLSL thread renderer: same
// fields, same motion and the same finish. Splats are integer atomics into a
// fixed-point accumulator instead of additive point blending, so the same
// passes run on a backend with compute only.

struct Params {
    float t; float dt; float fr; float aspect;
    float u; float ta; float tb; float spacing;
    float nlev; float gain; float scale; float keep;
    float expo; float spec; float dur; float fxs;
    float4 pr0;
    float4 pr1;
    uint np; int wa; int wb; int ch;
    uint w; uint h; uint substeps; uint simw;
    uint simh; uint seedbase; float simt; uint pad0;
};

// One level of the bloom pyramid: full-frame size, the level written, and the
// scale from accumulator units to density.
struct Level {
    uint w; uint h; uint level; float inv;
};

static const float PI = 3.14159265f;

// Log-density tone, chromatic fringe, seven-level bloom, the opening line,
// grain and vignette, packed to RGBA8.
ConstantBuffer<Params> P : register(b0);
RWStructuredBuffer<uint> acc : register(u1);
RWStructuredBuffer<float4> pa : register(u2);
RWStructuredBuffer<float4> pb : register(u3);
RWStructuredBuffer<uint> frame : register(u4);

float hash2(float2 p) { return frac(sin(dot(p, float2(127.1f, 311.7f))) * 43758.5453f); }
uint hashu(uint x0) {
    uint x = x0;
    x = x ^ (x >> 16u);
    x = x * 0x7feb352du;
    x = x ^ (x >> 15u);
    x = x * 0x846ca68bu;
    x = x ^ (x >> 16u);
    return x;
}
// The bloom pyramid: level l is max(1, size >> l) on each side. Odd levels live
// in one buffer and even levels in another, each packed after the earlier
// levels of the same parity, so a pass reads one buffer and writes the other.
uint levelDim(uint n, uint l) { return max(1u, n >> l); }
uint levelBase(uint w, uint h, uint l) {
    uint o = 0u;
    for (uint j = 2u - (l % 2u); j < l; j = j + 2u) {
        o = o + levelDim(w, j) * levelDim(h, j);
    }
    return o;
}
float4 texel(uint l, uint base, uint lw, uint x, uint y) {
    if (l == 0u) {
        const uint i = (y * P.w + x) * 4u;
        return float4(float(acc[i]), float(acc[i + 1u]), float(acc[i + 2u]), float(acc[i + 3u])) / P.fxs;
    }
    if (l % 2u == 1u) { return pa[base + y * lw + x]; }
    return pb[base + y * lw + x];
}
float4 bilin(uint l, float2 u) {
    const uint lw = levelDim(P.w, l);
    const uint lh = levelDim(P.h, l);
    const uint base = levelBase(P.w, P.h, l);
    const float2 q = clamp(u * float2(float(lw), float(lh)) - 0.5f, ((float2)(0.0f)), float2(float(lw) - 1.0f, float(lh) - 1.0f));
    const uint x0 = uint(q.x);
    const uint y0 = uint(q.y);
    const uint x1 = min(x0 + 1u, lw - 1u);
    const uint y1 = min(y0 + 1u, lh - 1u);
    const float fx = q.x - float(x0);
    const float fy = q.y - float(y0);
    const float4 top = lerp(texel(l, base, lw, x0, y0), texel(l, base, lw, x1, y0), fx);
    const float4 bottom = lerp(texel(l, base, lw, x0, y1), texel(l, base, lw, x1, y1), fx);
    return lerp(top, bottom, fy);
}
float3 tone(float4 a) {
    const float3 hue = a.xyz / max(a.w, 1e-6f);
    const float l = log(1.0f + a.w * P.expo) / log(1.0f + P.expo * 40.0f);
    return hue * pow(max(l, 0.0f), 0.85f);
}
[numthreads(16, 16, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    if (gid.x >= P.w || gid.y >= P.h) { return; }
    const float fw = float(P.w);
    const float fh = float(P.h);
    const float2 uv = (float2(float(gid.x), float(gid.y)) + 0.5f) / float2(fw, fh);
    const float2 d = uv - 0.5f;
    const float rise = smoothstep(0.4f, 3.0f, P.t);
    const float fall = 1.0f - smoothstep(P.dur - 5.0f, P.dur - 3.6f, P.t);
    const float vy = max(min(rise, fall), 0.002f);
    const float vx = max(1.0f - smoothstep(P.dur - 3.7f, P.dur - 3.1f, P.t), 0.002f);
    const float2 u = float2(0.5f + (uv.x - 0.5f) / vx, 0.5f + (uv.y - 0.5f) / vy);
    const float ca = 0.0008f + 0.004f * P.spec;
    float3 c = float3(tone(bilin(0u, u + d * ca)).x, tone(bilin(0u, u)).y, tone(bilin(0u, u - d * ca)).z);
    float3 b = ((float3)(0.0f));
    for (uint l = 1u; l < 8u; l++) {
        b = b + tone(bilin(l, u)) * (0.12f + 0.05f * float(l));
    }
    c = c + b * 0.12f;
    if (abs(u.x - 0.5f) > 0.5f || abs(u.y - 0.5f) > 0.5f) { c = ((float3)(0.0f)); }
    const float t0 = (P.t - 1.0f) / 0.5f;
    const float t1 = (P.t - P.dur + 4.2f) / 0.5f;
    const float glow = (1.0f - smoothstep(0.0f, 0.003f, abs(uv.y - 0.5f))) * (exp(-t0 * t0) + exp(-t1 * t1)) * 3.0f;
    const float t2 = (P.t - P.dur + 3.2f) / 0.25f;
    const float dotEnd = exp(-length(d * float2(fw / fh, 1.0f)) / 0.004f) * exp(-t2 * t2) * 6.0f;
    c = c + float3(0.85f, 0.95f, 1.0f) * (glow + dotEnd);
    c = 1.0f - exp(-c * 1.6f);
    c = c + (hash2(float2(float(gid.x), float(gid.y)) + frac(P.t * 7.13f) * 97.0f) - 0.5f) * 0.035f;
    c = c * (1.0f - 0.6f * dot(d, d) * 2.0f);
    c = clamp(c, ((float3)(0.0f)), ((float3)(1.0f)));
    const uint r = uint(c.x * 255.0f + 0.5f);
    const uint g = uint(c.y * 255.0f + 0.5f);
    const uint bl = uint(c.z * 255.0f + 0.5f);
    frame[gid.y * P.w + gid.x] = r | (g << 8u) | (bl << 16u) | (255u << 24u);
}
