// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/threads.wgsl. Do not edit.
// WGSL sha256 5619d32eb7ffc812cfa5223c4a910b199b86a6650e9f865dd3941ebb06be7ba2
// Pass: threads_decay

// Threads: particles flow along the zero set of a form field and leave luminous
// trails, tone-mapped by log density. A creative module: it has no CPU
// reference and writes no certificate (docs/architecture/adr/0010-web-host.md).
//
// One shader source for every backend. WebGPU runs it as written (web/ and the
// wasm build); D3D12 runs src/renderer/gpu/shaders/hlsl/threads_*.hlsl, which
// scripts/wgsl_to_hlsl.py generates from it. The code before the first pass
// marker is shared by every pass. Ported from a GLSL thread renderer: same
// fields, same motion and the same finish. Splats are integer atomics into a
// fixed-point accumulator instead of additive point blending, so the same
// passes run on a backend with compute only.

struct Params {
    float t; float dt; float fr; float aspect;
    float u; float ta; float tb; float spacing;
    float nlev; float gain; float scale; float keep;
    float expo; float spec; float dur; float fxs;
    float4 pr0;
    float4 pr1;
    uint np; int wa; int wb; int ch;
    uint w; uint h; uint substeps; uint simw;
    uint simh; uint seedbase; float simt; uint pad0;
};

// One level of the bloom pyramid: full-frame size, the level written, and the
// scale from accumulator units to density.
struct Level {
    uint w; uint h; uint level; float inv;
};

static const float PI = 3.14159265f;

// Persistence: every accumulator cell keeps P.keep of its value.
ConstantBuffer<Params> P : register(b0);
RWStructuredBuffer<uint> acc : register(u1);

float hash1(float n) { return frac(sin(n * 12.9898f) * 43758.5453f); }
float hash2(float2 p) { return frac(sin(dot(p, float2(127.1f, 311.7f))) * 43758.5453f); }
uint hashu(uint x0) {
    uint x = x0;
    x = x ^ (x >> 16u);
    x = x * 0x7feb352du;
    x = x ^ (x >> 15u);
    x = x * 0x846ca68bu;
    x = x ^ (x >> 16u);
    return x;
}
float vnoise(float2 p) {
    const float2 i = floor(p);
    float2 f = frac(p);
    f = f * f * (3.0f - 2.0f * f);
    return lerp(lerp(hash2(i), hash2(i + float2(1.0f, 0.0f)), f.x), lerp(hash2(i + float2(0.0f, 1.0f)), hash2(i + float2(1.0f, 1.0f)), f.x), f.y);
}
float fbm(float2 p0) {
    float2 p = p0;
    float s = 0.0f;
    float a = 0.5f;
    for (int i = 0; i < 4; i++) {
        s = s + a * vnoise(p);
        p = p * 2.03f + float2(1.7f, 9.2f);
        a = a * 0.5f;
    }
    return s;
}
// GLSL mat2(c, -s, s, c) * p.
float2 rotv(float2 p, float a) {
    const float c = cos(a);
    const float s = sin(a);
    return float2(c * p.x + s * p.y, c * p.y - s * p.x);
}
// GLSL mod: the remainder takes the sign of the divisor.
float fmodf(float x, float y) { return x - y * floor(x / y); }
float seg(float2 p, float2 a, float2 b) {
    const float2 pa = p - a;
    const float2 ba = b - a;
    const float h = clamp(dot(pa, ba) / dot(ba, ba), 0.0f, 1.0f);
    return length(pa - ba * h);
}
float ring(float2 p, float2 c, float r) { return abs(length(p - c) - r); }
float box2(float2 p, float2 b) {
    const float2 d = abs(p) - b;
    return length(max(d, ((float2)(0.0f)))) + min(max(d.x, d.y), 0.0f);
}
float figure(float2 p0, float lean) {
    const float2 p = rotv(p0, lean);
    float d = ring(p, float2(0.0f, 0.17f), 0.035f);
    d = min(d, seg(p, float2(0.0f, 0.13f), float2(0.0f, 0.0f)));
    d = min(d, seg(p, float2(0.0f, 0.11f), float2(-0.09f, 0.03f)));
    d = min(d, seg(p, float2(0.0f, 0.11f), float2(0.09f, 0.03f)));
    d = min(d, seg(p, float2(0.0f, 0.0f), float2(-0.045f, -0.16f)));
    d = min(d, seg(p, float2(0.0f, 0.0f), float2(0.045f, -0.16f)));
    return d;
}

// The fifteen worlds. Each returns a signed, distance-like scalar whose zero
// set the particles trace. Squares are written as products: GLSL pow() of a
// negative base is undefined, and the drivers the original ran on folded it.
float fKomorebi(float2 p, float t) {
    const float2 w = float2(sin(t * 0.4f), cos(t * 0.31f)) * 0.03f;
    const float l = fbm((p + w) * 3.2f + float2(t * 0.04f, 0.0f));
    return (l - 0.55f) * 0.35f;
}
float fDroste(float2 p, float t) {
    const float sc = log(4.0f);
    float2 lz = float2(log(max(length(p), 1e-3f)), atan2(p.y, p.x));
    const float al = atan(sc / (2.0f * PI));
    lz = rotv(lz, al) / cos(al);
    lz.x = fmodf(lz.x - t * 0.25f, sc);
    float2 q = exp(lz.x) * float2(cos(lz.y), sin(lz.y)) * 2.2f;
    const float m = 0.5f + 0.5f * sin(t * 0.15f);
    q = q + m * 0.3f * float2(sin(q.y * PI), sin(q.x * PI));
    const float2 f = abs(frac(q) - 0.5f);
    return (0.5f - max(f.x, f.y)) * 0.08f * length(p) / exp(lz.x);
}
float fVoices(float2 p, float t) {
    float2 q = p * 1.3f;
    q.x = abs(q.x);
    const float2 w = float2(fbm(q * 2.1f + t * 0.06f), fbm(q * 2.1f - float2(t * 0.05f, 3.1f)));
    return (fbm(q * 1.6f + w * 1.6f) - 0.5f) * 0.3f + max(length(p * float2(0.7f, 1.0f)) - 0.8f, 0.0f);
}
float fMaking(float2 p, float t0) {
    const float t = t0 - 3.0f;
    const float rise = smoothstep(12.0f, 17.0f, t);
    float d = figure(p + float2(0.0f, 0.05f), (1.0f - rise) * 1.45f);
    float2 a = float2(0.0f, 0.6f);
    const float strike = floor(t / 3.1f);
    const float fade = ((t - strike * 3.1f > 0.6f) ? (0.3f) : (0.0f));
    for (int k = 0; k < 10; k++) {
        const float2 b = a + float2((hash1(strike * 13.0f + float(k)) - 0.5f) * 0.12f, -0.055f);
        d = min(d, seg(p, a, b) + 0.02f + fade);
        a = b;
    }
    const float hy = 0.62f - 0.3f * smoothstep(2.0f, 9.0f, t);
    d = min(d, seg(p, float2(0.3f, 0.7f), float2(0.3f, hy)));
    d = min(d, ring(p, float2(0.3f, hy - 0.03f), 0.02f));
    for (int k = 0; k < 6; k++) {
        const float fk = float(k);
        const float2 ph = float2(-0.75f + fk * 0.3f, 0.7f - fmodf(t * 0.05f + hash1(fk) * 1.4f, 1.5f));
        d = min(d, abs(box2(rotv(p - ph, sin(t * 0.8f + fk) * 0.6f), float2(0.035f, 0.045f))));
    }
    return d;
}
float fEye(float2 p, float t) {
    const float open = smoothstep(0.0f, 3.0f, t);
    const float ex = p.x / 0.55f;
    const float lid = 0.22f * (1.0f - ex * ex) * open;
    float d = abs(abs(p.y) - lid) + max(abs(p.x) - 0.55f, 0.0f);
    const float2 look = 0.04f * float2(sin(t * 0.7f), 0.4f * cos(t * 0.5f));
    const float r = length(p - look);
    d = min(d, abs(r - 0.18f));
    d = min(d, abs(r - 0.055f));
    const float a = atan2(p.y - look.y, p.x - look.x);
    d = min(d, max(abs(sin(a * 60.0f)) * r * 0.05f, max(r - 0.18f, 0.06f - r)));
    const float2 va = float2(0.0f, 0.62f);
    const float2 vb = float2(-0.9f, -0.42f);
    const float2 vc = float2(0.9f, -0.42f);
    d = min(d, min(min(seg(p, va, vb), seg(p, vb, vc)), seg(p, vc, va)));
    return d;
}
float puppetString(float2 p, float2 bar, float k, float2 j, float pull) {
    const float2 top = bar + float2(k * 0.06f, 0.0f);
    return seg(p, top, lerp(j, top, pull)) + 0.0015f;
}
float fStrings(float2 p, float t0) {
    const float t = t0 - 3.0f;
    const float sw = sin(t * 1.3f);
    const float cut = smoothstep(15.0f, 15.4f, t);
    const float2 bar = float2(0.15f * sw, 0.55f);
    const float slump = cut * (1.0f - smoothstep(16.5f, 19.0f, t)) * 0.07f;
    const float2 sl = float2(0.0f, slump);
    const float2 j0 = float2(0.0f, 0.08f) - sl;
    const float2 j1 = float2(-0.1f, sw * 0.03f * (1.0f - cut)) - sl;
    const float2 j2 = float2(0.1f, -sw * 0.03f * (1.0f - cut)) - sl;
    const float2 j3 = float2(-0.05f, -0.24f) - sl;
    const float2 j4 = float2(0.05f, -0.24f) - sl;
    float d = ring(p, j0 + float2(0.0f, 0.05f), 0.035f);
    const float2 hip = float2(0.0f, -0.1f - slump);
    d = min(d, seg(p, j0, hip));
    d = min(d, seg(p, j0, j1));
    d = min(d, seg(p, j0, j2));
    d = min(d, seg(p, hip, j3));
    d = min(d, seg(p, hip, j4));
    const float pull = cut * smoothstep(15.0f, 16.0f, t);
    d = min(d, puppetString(p, bar, -2.0f, j0, pull));
    d = min(d, puppetString(p, bar, -1.0f, j1, pull));
    d = min(d, puppetString(p, bar, 0.0f, j2, pull));
    d = min(d, puppetString(p, bar, 1.0f, j3, pull));
    d = min(d, puppetString(p, bar, 2.0f, j4, pull));
    d = min(d, seg(p, bar - float2(0.15f, 0.0f), bar + float2(0.15f, 0.0f)));
    const float lie = max(smoothstep(4.0f, 4.3f, t) * (1.0f - smoothstep(6.0f, 6.5f, t)), smoothstep(8.0f, 8.3f, t) * (1.0f - smoothstep(11.0f, 11.5f, t)));
    const float2 ns = j0 + float2(0.03f, 0.05f);
    d = min(d, seg(p, ns, ns + float2(0.04f + 0.24f * lie, 0.0f)));
    d = min(d, seg(p, ns + float2(0.0f, -0.03f), ns + float2(0.3f, -0.03f)) + 0.004f);
    const float2 tr = p - float2(-0.6f, -0.05f);
    d = min(d, seg(tr, float2(0.0f, -0.45f), float2(0.02f, 0.2f)) + (1.0f - smoothstep(8.0f, 10.0f, t) * (1.0f - smoothstep(12.0f, 14.0f, t))) * 0.5f);
    return d;
}
float fStream(float2 p, float t) {
    const float bend = 0.08f * sin(p.x * 2.2f + t * 0.5f);
    const float bx = lerp(-1.0f, 1.0f, smoothstep(0.0f, 18.0f, t));
    const float dx = p.x - bx;
    const float w = 0.09f + 0.06f * exp(-dx * dx * 20.0f);
    float d = abs(abs(p.y - bend) - w);
    for (int k = 0; k < 9; k++) {
        const float xk = -0.88f + float(k) * 0.22f;
        d = min(d, abs(length(float2((p.x - xk) * 5.0f, p.y - bend)) - 0.2f));
    }
    return d;
}
float fBelly(float2 p, float t) {
    float d = 1000.0f;
    for (int k = 0; k < 9; k++) {
        const float depth = frac((float(k) - t * 0.3f) / 9.0f) * 9.0f + 0.6f;
        const float2 q = p * depth;
        const float2 e = float2(q.x * 0.8f, max(q.y + 0.1f, 0.0f) * 1.1f + min(q.y + 0.1f, 0.0f) * 3.0f);
        d = min(d, abs(length(e) - 0.9f) / depth);
    }
    d = min(d, ring(p, float2(0.03f * sin(t * 0.4f), -0.14f), 0.008f));
    return d;
}
float prob(int k, float4 a, float4 b) {
    if (k == 0) { return a.x; }
    if (k == 1) { return a.y; }
    if (k == 2) { return a.z; }
    if (k == 3) { return a.w; }
    if (k == 4) { return b.x; }
    return b.y;
}
float fDraw(float2 p, float t, int ch, float4 pa, float4 pb) {
    const float ro = 0.15f;
    const float grow = smoothstep(4.0f, 9.0f, t);
    const float pick = smoothstep(12.6f, 12.9f, t);
    const float chaos = 1.0f - smoothstep(2.0f, 6.0f, t);
    float d = abs(length(p) - ro * (1.0f + 0.08f * chaos * sin(atan2(p.y, p.x) * 23.0f + t * 9.0f)));
    d = min(d, abs(length(p) - 0.33f) + 0.004f);
    for (int k = 0; k < 6; k++) {
        const float ang = radians(215.0f + 110.0f * float(k) / 5.0f);
        const float2 dir = float2(cos(ang), sin(ang));
        const float boost = ((k == ch) ? (1.0f + pick) : (1.0f - 0.8f * pick));
        const float reach = ro * (0.3f + 3.4f * sqrt(prob(k, pa, pb))) * grow * boost;
        d = min(d, seg(p, dir * ro * 0.9f, dir * (ro * 0.9f + reach)));
    }
    return d;
}
float fElements(float2 p, float t) {
    const float app = smoothstep(0.0f, 14.0f, t);
    const float2 sp = float2(0.0f, 0.62f - 0.32f * app);
    const float sr = 0.06f + 0.2f * app;
    float d = abs(length(p - sp) - sr);
    const float2 core = float2(0.0f, -0.2f);
    for (int k = 0; k < 4; k++) {
        const float fk = float(k);
        const float sx = (((k % 2) == 1) ? (1.0f) : (-1.0f));
        const float2 pk = float2(sx * ((k >= 2) ? (0.22f) : (0.42f)), ((k >= 2) ? (-0.34f) : (-0.22f)));
        const float open = smoothstep(5.0f + fk * 1.6f, 6.5f + fk * 1.6f, t);
        const float2 q = p - pk;
        d = min(d, abs(max(abs(q.x) * 1.4f + q.y * 0.5f - 0.06f, max(-q.y - 0.07f, q.y - 0.11f))));
        d = min(d, seg(p, pk + float2(0.0f, 0.1f), core) + (1.0f - open) * 0.5f);
    }
    d = min(d, seg(p, core, sp) + (1.0f - smoothstep(11.5f, 12.5f, t)) * 0.5f);
    return d;
}
float fBurden(float2 p, float t) {
    const float ys = -0.34f + 0.36f * (p.x + 0.9f) / 1.8f;
    float d = abs(p.y - ys) * 0.95f;
    const float fx = lerp(-0.2f, 0.0f, smoothstep(0.0f, 18.0f, t));
    const float2 foot = float2(fx, -0.34f + 0.36f * (fx + 0.9f) / 1.8f);
    d = min(d, figure(p - foot - float2(0.03f, 0.16f), -0.55f));
    const float2 bc = float2(fx + 0.19f, -0.34f + 0.36f * (fx + 1.09f) / 1.8f + 0.095f);
    d = min(d, abs(length(p - bc) - 0.095f));
    d = min(d, abs(box2(p - float2(-0.48f, 0.15f), float2(0.045f, 0.21f))));
    d = min(d, ring(p, float2(0.42f, 0.1f), 0.17f));
    return d;
}
float fSwing(float2 p, float t) {
    const float2 pl = float2(-0.25f, 0.25f);
    const float2 pr = float2(0.17f, 0.25f);
    float d = min(seg(p, pl, pr), min(seg(p, pl, pl - float2(0.08f, 0.6f)), seg(p, pr, pr + float2(0.08f, -0.6f))));
    const float ang = 0.35f * sin(t * 1.1f) * (1.0f - smoothstep(12.0f, 17.0f, t) * 0.7f);
    const float2 piv = float2(-0.04f, 0.25f);
    const float2 seat = piv + rotv(float2(0.0f, -0.45f), ang);
    d = min(d, min(seg(p, piv + float2(-0.04f, 0.0f), seat + float2(-0.04f, 0.0f)), seg(p, piv + float2(0.04f, 0.0f), seat + float2(0.04f, 0.0f))));
    d = min(d, figure(rotv(p - seat, -ang) - float2(0.0f, 0.11f), 0.0f));
    const float2 lamp = float2(0.3f, 0.35f);
    d = min(d, seg(p, float2(0.3f, -0.35f), lamp));
    d = min(d, min(seg(p, lamp, lamp + float2(-0.3f, -0.7f)), seg(p, lamp, lamp + float2(0.3f, -0.7f))) + 0.01f);
    d = min(d, abs(p.y + 0.35f) + 0.004f);
    return d;
}
float fForest(float2 p, float t) {
    const float logY = -0.18f + 0.03f * sin(p.x * 3.0f);
    float d = abs(abs(p.y - logY) - 0.07f) + max(abs(p.x) - 0.85f, 0.0f);
    d = min(d, abs(p.y + 0.27f) + 0.003f);
    for (int k = 0; k < 6; k++) {
        const float x = -0.9f + float(k) * 0.36f;
        d = min(d, abs(p.x - x - 0.01f * sin(p.y * 7.0f + float(k))) + max(-0.1f - p.y, 0.0f));
    }
    for (int k = 0; k < 5; k++) {
        const float sx = -0.5f + float(k) * 0.25f;
        const float hh = 0.35f * smoothstep(5.0f + float(k) * 1.5f, 16.0f + float(k), t);
        d = min(d, seg(p, float2(sx, logY + 0.07f), float2(sx, logY + 0.07f + hh)) + ((hh < 0.01f) ? (1.0f) : (0.0f)));
    }
    const float my = abs(frac(fbm(p * 7.0f + 5.0f) * 6.0f) - 0.5f) * 0.04f + max(p.y + 0.27f, 0.0f) * 2.0f;
    d = min(d, my + (1.0f - smoothstep(2.0f, 14.0f, t)) * 0.2f);
    const float2 sd = lerp(float2(-0.3f, 0.6f), float2(0.05f, logY + 0.08f), smoothstep(3.0f, 13.0f, t));
    d = min(d, ring(p, sd, 0.008f));
    d = min(d, seg(p, float2(0.05f, logY + 0.08f), float2(0.05f, logY + 0.08f + 0.22f * smoothstep(13.0f, 18.0f, t))) + ((t < 13.0f) ? (1.0f) : (0.0f)));
    return d;
}
float fMany(float2 p, float t) {
    const float tile = exp(-3.0f * smoothstep(0.0f, 10.0f, t)) * 0.9f;
    const float2 f = frac(p / tile + 0.5f) - 0.5f;
    float d = abs(length(f) - 0.3f) * tile;
    d = min(d, abs(max(abs(f.x), abs(f.y)) - 0.45f) * tile);
    return d + smoothstep(9.0f, 11.0f, t) * length(p) * 0.3f;
}
float3 spectral(float l) {
    return clamp(float3(1.5f - abs(4.0f * l - 3.0f), 1.5f - abs(4.0f * l - 2.0f), 1.5f - abs(4.0f * l - 1.0f)), ((float3)(0.0f)), ((float3)(1.0f)));
}
float3 palette(int w, float2 p, float s, float lam) {
    if (w == 0) { return lerp(float3(1.0f, 0.85f, 0.5f), float3(0.45f, 0.75f, 0.3f), s); }
    if (w == 1) { return lerp(float3(0.95f, 0.88f, 0.74f), float3(0.66f, 0.33f, 0.2f), step(0.85f, s)); }
    if (w == 2) { return ((p.x < 0.0f) ? (float3(0.4f, 0.85f, 1.0f)) : (float3(1.0f, 0.35f, 0.65f))); }
    if (w == 3) { return lerp(float3(1.0f, 0.45f, 0.12f), float3(0.95f, 0.2f, 0.45f), s); }
    if (w == 4) { return lerp(float3(0.6f, 0.8f, 1.0f), ((float3)(1.0f)), s); }
    if (w == 5) { return lerp(float3(0.9f, 0.1f, 0.12f), float3(1.0f, 0.75f, 0.35f), s); }
    if (w == 6) { return lerp(float3(0.85f, 0.55f, 0.25f), float3(0.95f, 0.9f, 0.8f), step(0.6f, s)); }
    if (w == 7) { return lerp(float3(0.55f, 0.35f, 1.0f), spectral(lam), 0.5f); }
    if (w == 8) { return lerp(float3(0.75f, 0.3f, 0.22f), float3(1.0f, 0.65f, 0.3f), step(0.92f, s)); }
    if (w == 9) { return lerp(float3(1.0f, 0.9f, 0.75f), float3(1.0f, 0.28f, 0.08f), step(0.9f, s)); }
    if (w == 10) {
        const int k = int(s * 4.0f);
        if (k == 0) { return float3(0.55f, 0.9f, 0.3f); }
        if (k == 1) { return float3(0.3f, 0.7f, 1.0f); }
        if (k == 2) { return float3(0.9f, 0.95f, 1.0f); }
        return float3(1.0f, 0.45f, 0.1f);
    }
    if (w == 11) { return lerp(float3(0.85f, 0.08f, 0.05f), float3(1.0f, 0.5f, 0.2f), s); }
    if (w == 12) { return lerp(float3(0.8f, 0.85f, 1.0f), float3(1.0f, 0.8f, 0.45f), step(0.75f, s)); }
    if (w == 13) { return lerp(float3(0.35f, 0.7f, 0.25f), float3(0.95f, 0.92f, 0.85f), step(0.7f, s)); }
    return spectral(lam);
}
// The bloom pyramid: level l is max(1, size >> l) on each side. Odd levels live
// in one buffer and even levels in another, each packed after the earlier
// levels of the same parity, so a pass reads one buffer and writes the other.
uint levelDim(uint n, uint l) { return max(1u, n >> l); }
uint levelBase(uint w, uint h, uint l) {
    uint o = 0u;
    for (uint j = 2u - (l % 2u); j < l; j = j + 2u) {
        o = o + levelDim(w, j) * levelDim(h, j);
    }
    return o;
}
[numthreads(16, 16, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    if (gid.x >= P.w || gid.y >= P.h) { return; }
    const uint i = (gid.y * P.w + gid.x) * 4u;
    acc[i] = uint(float(acc[i]) * P.keep);
    acc[i + 1u] = uint(float(acc[i + 1u]) * P.keep);
    acc[i + 2u] = uint(float(acc[i + 2u]) * P.keep);
    acc[i + 3u] = uint(float(acc[i + 3u]) * P.keep);
}
