// Generated by scripts/wgsl_to_hlsl.py from src/renderer/gpu/shaders/threads.wgsl. Do not edit.
// WGSL sha256 2b4d8c239a8394e8a4155d5642e68641d7c17764320b3fb32fdef22b1eeb1bca
// Pass: threads_pyr_first

// Threads: particles flow along the zero set of a form field and leave luminous
// trails, tone-mapped by log density. A creative module: it has no CPU
// reference and writes no certificate (docs/architecture/adr/0010-web-host.md).
//
// One shader source for every backend. WebGPU runs it as written (web/ and the
// wasm build); D3D12 runs src/renderer/gpu/shaders/hlsl/threads_*.hlsl, which
// scripts/wgsl_to_hlsl.py generates from it. The code before the first pass
// marker is shared by every pass. Ported from a GLSL thread renderer: same
// fields, same motion and the same finish. Splats are integer atomics into a
// fixed-point accumulator instead of additive point blending, so the same
// passes run on a backend with compute only.

struct Params {
    float t; float dt; float fr; float aspect;
    float u; float ta; float tb; float spacing;
    float nlev; float gain; float scale; float keep;
    float expo; float spec; float dur; float fxs;
    float4 pr0;
    float4 pr1;
    uint np; int wa; int wb; int ch;
    uint w; uint h; uint substeps; uint simw;
    uint simh; uint seedbase; float simt; uint pad0;
};

// One level of the bloom pyramid: full-frame size, the level written, and the
// scale from accumulator units to density.
struct Level {
    uint w; uint h; uint level; float inv;
};

static const float PI = 3.14159265f;

// Bloom level 1 from the accumulator: a 2 x 2 box, in density units.
ConstantBuffer<Level> L : register(b0);
RWStructuredBuffer<uint> acc : register(u1);
RWStructuredBuffer<float4> dst : register(u2);

float hash2(float2 p) { return frac(sin(dot(p, float2(127.1f, 311.7f))) * 43758.5453f); }
uint hashu(uint x0) {
    uint x = x0;
    x = x ^ (x >> 16u);
    x = x * 0x7feb352du;
    x = x ^ (x >> 15u);
    x = x * 0x846ca68bu;
    x = x ^ (x >> 16u);
    return x;
}
// The bloom pyramid: level l is max(1, size >> l) on each side. Odd levels live
// in one buffer and even levels in another, each packed after the earlier
// levels of the same parity, so a pass reads one buffer and writes the other.
uint levelDim(uint n, uint l) { return max(1u, n >> l); }
uint levelBase(uint w, uint h, uint l) {
    uint o = 0u;
    for (uint j = 2u - (l % 2u); j < l; j = j + 2u) {
        o = o + levelDim(w, j) * levelDim(h, j);
    }
    return o;
}
float4 accAt(uint x, uint y) {
    const uint i = (min(y, L.h - 1u) * L.w + min(x, L.w - 1u)) * 4u;
    return float4(float(acc[i]), float(acc[i + 1u]), float(acc[i + 2u]), float(acc[i + 3u]));
}
[numthreads(16, 16, 1)]
void main(uint3 gid : SV_DispatchThreadID) {
    const uint dw = levelDim(L.w, 1u);
    const uint dh = levelDim(L.h, 1u);
    if (gid.x >= dw || gid.y >= dh) { return; }
    const uint x = gid.x * 2u;
    const uint y = gid.y * 2u;
    const float4 s = accAt(x, y) + accAt(x + 1u, y) + accAt(x, y + 1u) + accAt(x + 1u, y + 1u);
    dst[gid.y * dw + gid.x] = s * (0.25f * L.inv);
}
