// The native D3D12 backend. The compute passes are the WGSL passes translated to
// HLSL by scripts/wgsl_to_hlsl.py (src/gpu/hlsl/) and compiled to DXIL by the
// Windows SDK's DXC at build time; this file only needs d3d12.dll and dxgi.dll.
// Every pass binds its buffers as root descriptors (root parameter i is WGSL
// binding i), so no descriptor heaps are needed. One command list records the
// whole frame: upload, six dispatches with UAV barriers between them, and the
// copies into one read-back buffer.
#include "raw/gpu.hpp"
#include "d3d12_device.hpp"
#include "frame_pack.hpp"
#include "hlsl/passes.hpp"
#include "raw_d3d12_dxil.hpp"   // generated by cmake/gpu.cmake: kDxil[] per pass
#include <cstring>
#include <map>
#include <string>
#include <vector>
namespace raw {
namespace {
using namespace gpu_host;
using d3d12::Device; using d3d12::hrError; using Microsoft::WRL::ComPtr;
struct Pipe { ComPtr<ID3D12RootSignature> rs; ComPtr<ID3D12PipelineState> pso; const d3d12_passes::PassInfo* info{}; };
std::map<std::string, Pipe>& pipes(){ static std::map<std::string, Pipe> p; return p; }

const Pipe* pipeline(const std::string& name, std::string& err){
    if (auto it = pipes().find(name); it != pipes().end()) return &it->second;
    const d3d12_passes::PassInfo* info = nullptr;
    for (const auto& p : d3d12_passes::kPasses) if (name == p.name) info = &p;
    const DxilBlob* dxil = nullptr;
    for (const auto& b : kDxil) if (name == b.name) dxil = &b;
    if (!info || !dxil){ err = "pass " + name + " is not compiled into this build"; return nullptr; }
    D3D12_ROOT_PARAMETER params[8] = {};
    for (int i = 0; i < info->bindCount; ++i){
        params[i].ParameterType = info->binds[i] == d3d12_passes::Bind::Cbv ? D3D12_ROOT_PARAMETER_TYPE_CBV
                                                                           : D3D12_ROOT_PARAMETER_TYPE_UAV;
        params[i].Descriptor.ShaderRegister = info->binds[i] == d3d12_passes::Bind::Cbv ? 0u : (UINT)i;
        params[i].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;
    }
    D3D12_ROOT_SIGNATURE_DESC rd = {};
    rd.NumParameters = (UINT)info->bindCount; rd.pParameters = params;
    ComPtr<ID3DBlob> blob, msg;
    HRESULT hr = D3D12SerializeRootSignature(&rd, D3D_ROOT_SIGNATURE_VERSION_1, &blob, &msg);
    if (FAILED(hr)){ err = hrError("root signature for pass " + name, hr) + (msg ? ": " + std::string((const char*)msg->GetBufferPointer(), msg->GetBufferSize()) : ""); return nullptr; }
    Pipe p; p.info = info;
    if (FAILED(hr = Device::get().device->CreateRootSignature(0, blob->GetBufferPointer(), blob->GetBufferSize(), IID_PPV_ARGS(&p.rs)))){
        err = hrError("CreateRootSignature " + name, hr); return nullptr; }
    D3D12_COMPUTE_PIPELINE_STATE_DESC pd = {};
    pd.pRootSignature = p.rs.Get();
    pd.CS = {dxil->bytes, dxil->size};
    if (FAILED(hr = Device::get().device->CreateComputePipelineState(&pd, IID_PPV_ARGS(&p.pso)))){
        err = hrError("CreateComputePipelineState " + name, hr); return nullptr; }
    return &(pipes()[name] = std::move(p));
}
struct Pass { const char* name; std::vector<ID3D12Resource*> binds; UINT gx, gy; };
// Every buffer one render uses, released together when the frame goes out of scope.
struct Frame {
    ComPtr<ID3D12Resource> upload, readback, T, SF, SI, depth, pos, nrm, am, mot, ss, rt, frame, hdr;
    std::vector<ID3D12Resource*> uavs() const {
        return {T.Get(), SF.Get(), SI.Get(), depth.Get(), pos.Get(), nrm.Get(), am.Get(), mot.Get(), ss.Get(), rt.Get(), frame.Get(), hdr.Get()};
    }
};
D3D12_RESOURCE_BARRIER transition(ID3D12Resource* r, D3D12_RESOURCE_STATES a, D3D12_RESOURCE_STATES b){
    D3D12_RESOURCE_BARRIER x = {};
    x.Type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
    x.Transition.pResource = r; x.Transition.Subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;
    x.Transition.StateBefore = a; x.Transition.StateAfter = b;
    return x;
}
void transitionAll(ID3D12GraphicsCommandList* cl, const std::vector<ID3D12Resource*>& rs, D3D12_RESOURCE_STATES a, D3D12_RESOURCE_STATES b){
    std::vector<D3D12_RESOURCE_BARRIER> v;
    for (ID3D12Resource* r : rs) if (r) v.push_back(transition(r, a, b));
    if (!v.empty()) cl->ResourceBarrier((UINT)v.size(), v.data());
}
bool record(ID3D12GraphicsCommandList* cl, const Frame& b, uint64_t trisBytes, const std::vector<Pass>& passes,
            const std::vector<std::pair<ID3D12Resource*, uint64_t>>& reads, std::string& err){
    transitionAll(cl, {b.T.Get()}, D3D12_RESOURCE_STATE_COMMON, D3D12_RESOURCE_STATE_COPY_DEST);
    cl->CopyBufferRegion(b.T.Get(), 0, b.upload.Get(), d3d12::kParamsBytes, trisBytes);
    transitionAll(cl, {b.T.Get()}, D3D12_RESOURCE_STATE_COPY_DEST, D3D12_RESOURCE_STATE_UNORDERED_ACCESS);
    std::vector<ID3D12Resource*> rest = b.uavs(); rest.erase(rest.begin());
    transitionAll(cl, rest, D3D12_RESOURCE_STATE_COMMON, D3D12_RESOURCE_STATE_UNORDERED_ACCESS);
    D3D12_RESOURCE_BARRIER uav = {};
    uav.Type = D3D12_RESOURCE_BARRIER_TYPE_UAV;   // pResource null: every UAV write before, every access after
    for (const Pass& ps : passes){
        const Pipe* p = pipeline(ps.name, err);
        if (!p) return false;
        if ((int)ps.binds.size() != p->info->bindCount){ err = std::string("pass ") + ps.name + ": binding count differs from the WGSL"; return false; }
        cl->SetComputeRootSignature(p->rs.Get());
        cl->SetPipelineState(p->pso.Get());
        for (int i = 0; i < p->info->bindCount; ++i){
            const D3D12_GPU_VIRTUAL_ADDRESS va = ps.binds[i]->GetGPUVirtualAddress();
            if (p->info->binds[i] == d3d12_passes::Bind::Cbv) cl->SetComputeRootConstantBufferView((UINT)i, va);
            else cl->SetComputeRootUnorderedAccessView((UINT)i, va);
        }
        cl->Dispatch(ps.gx, ps.gy, 1);
        cl->ResourceBarrier(1, &uav);
    }
    std::vector<ID3D12Resource*> src;
    for (const auto& rd : reads) if (rd.second) src.push_back(rd.first);
    transitionAll(cl, src, D3D12_RESOURCE_STATE_UNORDERED_ACCESS, D3D12_RESOURCE_STATE_COPY_SOURCE);
    uint64_t off = 0;
    for (const auto& rd : reads){ if (rd.second) cl->CopyBufferRegion(b.readback.Get(), off, rd.first, 0, rd.second); off += rd.second; }
    return true;
}
}  // namespace

bool gpuCompiled(){ return true; }
const char* gpuBackendName(){ return "d3d12"; }
bool gpuInit(GpuAdapterInfo& info, std::string& err){ return Device::init(info, err); }

bool renderGpu(const Scene& scene, int w, int h, const Mat4& prevVP,
               const RenderOptions& opts, FrameResult& r, std::string& err, bool frameOnly){
    GpuAdapterInfo info;
    if (!gpuInit(info, err)) return false;
    Device& dev = Device::get();
    const std::vector<float> tris = packTriangles(scene);
    const uint32_t ntri = (uint32_t)(tris.size() / 24), N = (uint32_t)w * (uint32_t)h;
    const Mat4 vp = mul(scene.camera.proj(), scene.camera.view());
    float pf[48] = {};
    packParams(pf, scene, vp, prevVP, w, h, ntri, opts.rtao);
    const uint64_t trisBytes = tris.size() * 4, n4 = N * 4ull, n16 = N * 16ull;
    Frame b;
    bool ok = dev.buffer(d3d12::kParamsBytes + trisBytes, D3D12_HEAP_TYPE_UPLOAD, b.upload, err)
        && dev.buffer(trisBytes, D3D12_HEAP_TYPE_DEFAULT, b.T, err) && dev.buffer(ntri * 64ull, D3D12_HEAP_TYPE_DEFAULT, b.SF, err)
        && dev.buffer(ntri * 16ull, D3D12_HEAP_TYPE_DEFAULT, b.SI, err) && dev.buffer(n4, D3D12_HEAP_TYPE_DEFAULT, b.depth, err)
        && dev.buffer(n16, D3D12_HEAP_TYPE_DEFAULT, b.pos, err) && dev.buffer(n16, D3D12_HEAP_TYPE_DEFAULT, b.nrm, err)
        && dev.buffer(n16, D3D12_HEAP_TYPE_DEFAULT, b.am, err) && dev.buffer(n16, D3D12_HEAP_TYPE_DEFAULT, b.mot, err)
        && dev.buffer(n4, D3D12_HEAP_TYPE_DEFAULT, b.ss, err) && dev.buffer(n4, D3D12_HEAP_TYPE_DEFAULT, b.rt, err)
        && dev.buffer(n16, D3D12_HEAP_TYPE_DEFAULT, b.frame, err) && dev.buffer(n16, D3D12_HEAP_TYPE_DEFAULT, b.hdr, err);
    if (!ok) return false;
    if (!dev.write(b.upload.Get(), 0, pf, sizeof pf, err) || !dev.write(b.upload.Get(), d3d12::kParamsBytes, tris.data(), trisBytes, err)) return false;
    ID3D12Resource* const P = b.upload.Get();
    const UINT gx = (UINT)(w + 7) / 8, gy = (UINT)(h + 7) / 8;
    std::vector<Pass> passes = {{"setup", {P, b.T.Get(), b.SF.Get(), b.SI.Get()}, (ntri + 63) / 64, 1},
        {"raster", {P, b.T.Get(), b.SF.Get(), b.SI.Get(), b.depth.Get(), b.pos.Get(), b.nrm.Get(), b.am.Get()}, gx, gy},
        {"motion", {P, b.pos.Get(), b.am.Get(), b.mot.Get()}, gx, gy},
        {"ssao", {P, b.pos.Get(), b.nrm.Get(), b.am.Get(), b.ss.Get()}, gx, gy}};
    if (opts.rtao) passes.push_back({"rtao", {P, b.T.Get(), b.pos.Get(), b.nrm.Get(), b.am.Get(), b.rt.Get()}, gx, gy});
    passes.push_back({"shade", {P, b.nrm.Get(), b.am.Get(), opts.rtao ? b.rt.Get() : b.ss.Get(), b.frame.Get(), b.hdr.Get()}, gx, gy});
    ID3D12Resource* const chan[kChannels] = {b.depth.Get(), b.pos.Get(), b.nrm.Get(), b.am.Get(), b.mot.Get(),
                                             b.ss.Get(), b.rt.Get(), b.frame.Get(), b.hdr.Get()};
    std::vector<std::pair<ID3D12Resource*, uint64_t>> reads;
    uint64_t total = 0;
    for (int i = 0; i < kChannels; ++i){ reads.push_back({chan[i], readBytes(i, w, h, opts.rtao, frameOnly)}); total += reads.back().second; }
    if (!dev.buffer(total, D3D12_HEAP_TYPE_READBACK, b.readback, err)) return false;
    ID3D12GraphicsCommandList* cl = dev.begin(err);
    if (!cl || !record(cl, b, trisBytes, passes, reads, err) || !dev.submitAndWait(err)) return false;
    const unsigned char* bytes = nullptr;
    D3D12_RANGE range{0, (SIZE_T)total};
    HRESULT hr = b.readback->Map(0, &range, (void**)&bytes);
    if (FAILED(hr)){ err = hrError("readback Map", hr); return false; }
    const float* f[kChannels]; uint64_t off = 0;
    for (int i = 0; i < kChannels; ++i){ f[i] = reads[i].second ? (const float*)(bytes + off) : nullptr; off += reads[i].second; }
    unpackFrame(r, f, w, h, vp, opts, frameOnly);
    D3D12_RANGE none{0, 0};
    b.readback->Unmap(0, &none);
    return true;
}
}
